namespace: "kube-system"

workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

grafana:
  dashboard:
    enabled: true
    dashboards:
      - name: etcd
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/etcd/dashboards/kubernetes-etcd.json"
        folder: "System"
