workload:
  type: "StatefulSet"
  image:
    registry: ghcr.io
    repository: home-operations/sonarr
    tag: 4.0.14
  envsSecret:
    - name: SONARR__POSTGRES__HOST
      secret: sonarr-postgres-app
      key: host
    - name: SONARR__POSTGRES__USER
      secret: sonarr-postgres-app
      key: username
    - name: SONARR__POSTGRES__PASSWORD
      secret: sonarr-postgres-app
      key: password
  envs:
    - name: "SONARR__POSTGRES__PORT"
      value: "5432"
  probes:
    readinessProbe:
      type: tcpSocket
      port: 8989
    livenessProbe:
      type: tcpSocket
      port: 8989
  storage:
    - name: config
      type: emptyDir
      mountPath: /config

service:
  ports:
    - name: http
      port: 8989
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: newsonarr.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "sonarr"
          port: 8989

autoscaling:
  enabled: false
  