workload:
  type: DaemonSet
  image:
    repository: grafana/promtail
    tag: 3.3.2
  args:
    - '-config.file=/etc/promtail/config.yaml'
    - '-client.url=http://loki.loki.svc.cluster.local:3100/api/prom/push'
  resources:
    preset: micro
  # securityContext:
  #   runAsGroup: 0
  #   runAsNonRoot: false
  #   runAsUser: 0
  storage:
    - name: config
      type: configMap
      mountPath: /etc/promtail
      configMapName: promtail
    - name: logs
      type: hostPath
      mountPath: /var/log
      hostPath: /var/log

pdb:
  enabled: false

autoscaling:
  enabled: false

service:
  ports:
    - name: http
      port: 9080
      protocol: TCP

configMap:
  enabled: true
  data:
    config.yaml: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0

      clients:
      - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

      positions:
        filename: /tmp/positions.yaml
      target_config:
        sync_period: 10s
      scrape_configs:
      - job_name: pod-logs
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: __host__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_pod_name
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - nodes
            - nodes/proxy
            - services
            - endpoints
            - pods
          verbs:
            - get
            - watch
            - list

ingress:
  enabled: true
  entryPoints:
    - internalwebsecure
    - internalweb
  port: http
  prefix: promtail
  tls: true

