namespace: "media"

workload:
  type: "StatefulSet"
  image:
    registry: ghcr.io
    repository: home-operations/sabnzbd
    tag: 4.5.1
  envs:
    - name: "SABNZBD__HOST_WHITELIST_ENTRIES"
      value: "newsabnzbd.projectwhitebox.com"
  probes:
    readinessProbe:
      type: tcpSocket
      port: 8080
    livenessProbe:
      type: tcpSocket
      port: 8080
  storage:
    - name: sabnzbd-data
      type: pvcTemplate
      mountPath: /config
      accessModes:
        - "ReadWriteOnce"
      storageClass: "longhorn2x"
      size: "10Gi"
      readOnly: false
    - name: media-1
      type: pvc
      mountPath: /data/media1
      claimName: "media-1"
    - name: media-2
      type: pvc
      mountPath: /data/media2
      claimName: "media-2"
    - name: downloads
      type: pvc
      mountPath: /data/downloads
      claimName: "media-2"
    - name: tmp
      type: emptyDir
      mountPath: /tmp
      ramDisk: false
      readOnly: false

service:
  ports:
    - name: http
      port: 8080
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: newsabnzbd.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "sabnzbd"
          port: 8080

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: media-1
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 7.81Ti
      storageClassName: longhorn-static
      volumeName: media-1
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: media-2
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 7.81Ti
      storageClassName: longhorn-static
      volumeName: media-2
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: downloads
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 350Gi
      storageClassName: longhorn-static
      volumeName: downloads
