kind: Deployment
replicas: 2
leaderElection:
  enabled: true
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: descheduler
        topologyKey: kubernetes.io/hostname
deschedulerPolicy:
  evictDaemonSetPods: false
  profiles:
    - name: default
      pluginConfig:
        - name: DefaultEvictor
          args:
            evictSystemCriticalPods: true
            evictFailedBarePods: true
            evictLocalStoragePods: true
            nodeFit: true
            minReplicas: 0
        - name: RemoveDuplicates
        - name: LowNodeUtilization
          args:
            thresholds:
              cpu: 20
              memory: 20
              pods: 20
            targetThresholds:
              cpu: 50
              memory: 50
              pods: 50
            metricsUtilization:
              metricsServer: true
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 100
            includingInitContainers: true
        - name: "RemoveFailedPods"
          args:
            exitCodes:
            - 1
            includingInitContainers: true
            excludeOwnerKinds:
            - "Job"
            minPodLifetimeSeconds: 3600
        - name: PodLifeTime
          args:
            maxPodLifeTimeSeconds: 86400
            states:
            - "Pending"
            - "PodInitializing"
      plugins:
        balance:
          enabled:
            - RemoveDuplicates
            - LowNodeUtilization
        deschedule:
          enabled:
            - RemovePodsHavingTooManyRestarts
            - RemoveFailedPods
            - PodLifeTime
