workload:
  image:
    registry: "registry.k8s.io"
    repository: "descheduler/descheduler"
    tag: "v0.31.0"
  command:
    - '/bin/descheduler'
  args:
    - '--v=3'
    - '--policy-config-file=/config/policy.yaml'
    - '--descheduling-interval=5m'
    - '--leader-elect=true'
    - '--leader-elect-resource-namespace=descheduler'
  priorityClassName: "system-cluster-critical"
  resources:
    preset: "nano"
  probes:
    readinessProbe:
      type: httpGet
      path: "/healthz"
      port: 10258
      scheme: "HTTPS"
    livenessProbe:
      type: httpGet
      path: "/healthz"
      port: 10258
      scheme: "HTTPS"
  storage:
    - name: config
      type: configMap
      mountPath: /config
      configMapName: descheduler
      items:
        - key: policy.yaml
          path: policy.yaml

service:
  ports:
    - name: https-metrics
      protocol: TCP
      port: 10258

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - events.k8s.io
          resources:
            - events
          verbs:
            - create
            - update
        - apiGroups:
            - ''
          resources:
            - nodes
          verbs:
            - get
            - watch
            - list
        - apiGroups:
            - ''
          resources:
            - namespaces
          verbs:
            - get
            - watch
            - list
        - apiGroups:
            - ''
          resources:
            - pods
          verbs:
            - get
            - watch
            - list
            - delete
        - apiGroups:
            - ''
          resources:
            - pods/eviction
          verbs:
            - create
        - apiGroups:
            - scheduling.k8s.io
          resources:
            - priorityclasses
          verbs:
            - get
            - watch
            - list
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
            - update
        - apiGroups:
            - coordination.k8s.io
          resourceNames:
            - descheduler
          resources:
            - leases
          verbs:
            - get
            - patch
            - delete
