installCRDs: true

workload:
  image:
    registry: "ghcr.io"
    repository: "cloudnative-pg/cloudnative-pg"
    tag: "1.25.0"
  command:
    - '/manager'
  args:
    - 'controller'
    - '--leader-elect'
    - '--max-concurrent-reconciles=10'
    - '--webhook-port=9443'
  storage:
    - name: webhook-certificates
      type: secret
      optional: true
      mountPath: "/run/secrets/cnpg.io/webhook"
      secretName: cnpg-webhook-cert

service:
  name: cnpg-webhook-service
  ports:
    - name: webhook
      protocol: TCP
      port: 9443
    - name: metrics
      protocol: TCP
      port: 8080

serviceMonitor:
  enabled: true

rbac:
  enabled: true
  type: "ClusterRole"
  rules:
    - apiGroups:
        - ''
      resources:
        - nodes
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - admissionregistration.k8s.io
      resources:
        - mutatingwebhookconfigurations
        - validatingwebhookconfigurations
      verbs:
        - get
        - patch
    - apiGroups:
        - postgresql.cnpg.io
      resources:
        - clusterimagecatalogs
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ''
      resources:
        - configmaps
        - secrets
        - services
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - ''
      resources:
        - configmaps/status
        - secrets/status
      verbs:
        - get
        - patch
        - update
    - apiGroups:
        - ''
      resources:
        - events
      verbs:
        - create
        - patch
    - apiGroups:
        - ''
      resources:
        - persistentvolumeclaims
        - pods
        - pods/exec
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - watch
    - apiGroups:
        - ''
      resources:
        - pods/status
      verbs:
        - get
    - apiGroups:
        - ''
      resources:
        - serviceaccounts
      verbs:
        - create
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - apps
      resources:
        - deployments
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - batch
      resources:
        - jobs
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - watch
    - apiGroups:
        - coordination.k8s.io
      resources:
        - leases
      verbs:
        - create
        - get
        - update
    - apiGroups:
        - monitoring.coreos.com
      resources:
        - podmonitors
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - watch
    - apiGroups:
        - policy
      resources:
        - poddisruptionbudgets
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - postgresql.cnpg.io
      resources:
        - backups
        - clusters
        - databases
        - poolers
        - publications
        - scheduledbackups
        - subscriptions
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - postgresql.cnpg.io
      resources:
        - backups/status
        - databases/status
        - publications/status
        - scheduledbackups/status
        - subscriptions/status
      verbs:
        - get
        - patch
        - update
    - apiGroups:
        - postgresql.cnpg.io
      resources:
        - imagecatalogs
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - postgresql.cnpg.io
      resources:
        - clusters/finalizers
        - poolers/finalizers
      verbs:
        - update
    - apiGroups:
        - postgresql.cnpg.io
      resources:
        - clusters/status
        - poolers/status
      verbs:
        - get
        - patch
        - update
        - watch
    - apiGroups:
        - rbac.authorization.k8s.io
      resources:
        - rolebindings
        - roles
      verbs:
        - create
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - snapshot.storage.k8s.io
      resources:
        - volumesnapshots
      verbs:
        - create
        - get
        - list
        - patch
        - watch
    - apiGroups:
        - postgresql.cnpg.io
      resources:
        - backups
        - clusters
        - databases
        - poolers
        - publications
        - scheduledbackups
        - subscriptions
      verbs:
        - create
        - delete
        - deletecollection
        - patch
        - update
        - get
        - list
        - watch
