workload:
  image:
    registry: registry.k8s.io
    repository: metrics-server/metrics-server
    tag: v0.7.2
  args:
    - '--secure-port=10250'
    - '--cert-dir=/tmp'
    - '--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname'
    - '--kubelet-use-node-status-port'
    - '--metric-resolution=15s'
  resources:
    preset: micro
  storage:
    - mountPath: /tmp
      name: tmp
      ramDisk: false
      readOnly: false
      type: emptyDir

service:
  ports:
    - name: https-metrics
      port: 10250
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - nodes/metrics
          verbs:
            - get
        - apiGroups:
            - ''
          resources:
            - pods
            - nodes
            - namespaces
            - configmaps
          verbs:
            - get
            - list
            - watch
