workload:
  image:
    registry: registry.k8s.io
    repository: metrics-server/metrics-server
    tag: v0.7.2
  args:
    - '--secure-port=10250'
    - '--cert-dir=/tmp'
    - '--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname'
    - '--kubelet-use-node-status-port'
    - '--metric-resolution=15s'
  resources:
    preset: micro
  storage:
    - mountPath: /tmp
      name: tmp
      ramDisk: false
      readOnly: false
      type: emptyDir

service:
  ports:
    - name: https-metrics
      port: 10250
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - nodes/metrics
          verbs:
            - get
        - apiGroups:
            - ''
          resources:
            - pods
            - nodes
            - namespaces
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - metrics.k8s.io
          resources:
            - pods
            - nodes
          verbs:
            - get
            - list
            - watch

extraObjects:
  - |
    apiVersion: apiregistration.k8s.io/v1
    kind: APIService
    metadata:
      labels:
        app.kubernetes.io/instance: ms
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: metrics-server
        app.kubernetes.io/version: 0.7.2
        argocd.argoproj.io/instance: ms
        helm.sh/chart: metrics-server-3.12.2
      name: v1beta1.metrics.k8s.io
    spec:
      group: metrics.k8s.io
      groupPriorityMinimum: 100
      insecureSkipTLSVerify: true
      service:
        name: metrics-server
        namespace: metrics-server
        port: 10250
      version: v1beta1
      versionPriority: 100
