helm:
  parameters:
  - name: image.name
    value: quay.io/jetstack/cert-manager-controller
    forcestring: true
  - name: cert-manager-controller.workload.image.tag
    value: v1.18.1
    forcestring: true
