workload:
  enabled: true
  image:
    registry: "docker.io"
  replicaCount: 2
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: true

service:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

pdb:
  enabled: true
  maxUnavailable: "1" 

serviceAccount:
  enabled: true
  automountServiceAccountToken: true
