namespace: "cert-manager"

workload:
  annotations:
    match-regex.version-checker.io/cert-manager-webhook: 'v(\d+)\.(\d+)\.(\d+)'
  image:
    registry: "quay.io"
    repository: "jetstack/cert-manager-webhook"
    tag: "v1.17.2"
  args:
    - '--v=2'
    - '--secure-port=10250'
    - '--dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)'
    - '--dynamic-serving-ca-secret-name=cert-manager-webhook-ca'
    - '--dynamic-serving-dns-names=cert-manager-webhook'
    - '--dynamic-serving-dns-names=cert-manager-webhook.$(POD_NAMESPACE)'
    - '--dynamic-serving-dns-names=cert-manager-webhook.$(POD_NAMESPACE).svc'
  probes:
    readinessProbe:
      path: "/livez"
      port: 6080
    livenessProbe:
      path: "/livez"
      port: 6080

service:
  ports:
    - name: https
      protocol: TCP
      port: 10250
    - name: healthcheck
      protocol: TCP
      port: 6080
    - name: http-metrics
      protocol: TCP
      port: 9402

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - cert-manager.io
          resources:
            - clusterissuers
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - cert-manager.io
          resources:
            - certificates
            - certificaterequests
            - issuers
          verbs:
            - create
            - delete
            - deletecollection
            - patch
            - update
        - apiGroups:
            - cert-manager.io
          resources:
            - certificates/status
          verbs:
            - update
        - apiGroups:
            - acme.cert-manager.io
          resources:
            - challenges
            - orders
          verbs:
            - create
            - delete
            - deletecollection
            - patch
            - update
        - apiGroups:
            - cert-manager.io
          resources:
            - certificates
            - certificaterequests
            - issuers
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - acme.cert-manager.io
          resources:
            - challenges
            - orders
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - authorization.k8s.io
          resources:
            - subjectaccessreviews
          verbs:
            - create
        - apiGroups:
            - ''
          resourceNames:
            - cert-manager
          resources:
            - serviceaccounts/token
          verbs:
            - create
        - apiGroups:
            - ''
          resourceNames:
            - cert-manager-webhook-ca
          resources:
            - secrets
          verbs:
            - get
            - list
            - watch
            - update
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - create

extraObjects:
  - |
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    metadata:
      annotations:
        cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-ca
      labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: webhook
        app.kubernetes.io/version: v1.16.2
        argocd.argoproj.io/instance: cert-manager
        helm.sh/chart: cert-manager-v1.16.2
      name: cert-manager-webhook
    webhooks:
      - admissionReviewVersions:
          - v1
        clientConfig:
          service:
            name: cert-manager-webhook
            namespace: cert-manager
            path: /mutate
            port: 10250
        failurePolicy: Fail
        matchPolicy: Equivalent
        name: webhook.cert-manager.io
        rules:
          - apiGroups:
              - cert-manager.io
            apiVersions:
              - v1
            operations:
              - CREATE
            resources:
              - certificaterequests
        sideEffects: None
        timeoutSeconds: 30
  - |
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      annotations:
        cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-ca
      labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: webhook
        app.kubernetes.io/version: v1.16.2
        argocd.argoproj.io/instance: cert-manager
        helm.sh/chart: cert-manager-v1.16.2
      name: cert-manager-webhook
    webhooks:
      - admissionReviewVersions:
          - v1
        clientConfig:
          service:
            name: cert-manager-webhook
            namespace: cert-manager
            path: /validate
            port: 10250
        failurePolicy: Fail
        matchPolicy: Equivalent
        name: webhook.cert-manager.io
        namespaceSelector:
          matchExpressions:
            - key: cert-manager.io/disable-validation
              operator: NotIn
              values:
                - 'true'
        rules:
          - apiGroups:
              - cert-manager.io
              - acme.cert-manager.io
            apiVersions:
              - v1
            operations:
              - CREATE
              - UPDATE
            resources:
              - '*/*'
        sideEffects: None
        timeoutSeconds: 30
