workload:
  type: DaemonSet
  image:
    registry: "quay.io"
    repository: "prometheuscommunity/smartctl-exporter"
    tag: "v0.14.0"
    digest: "sha256:a13840e6df4e3c6a3b25c46e15d5156f7c5109acad97f9b92a6955bd658b62c3"
  args:
    - '--smartctl.path=/usr/sbin/smartctl'
    - '--smartctl.interval=120s'
    - '--web.listen-address=0.0.0.0:9633'
    - '--web.telemetry-path=/metrics'
  probes:
    readinessProbe:
      path: "/metrics"
      port: 9633
    livenessProbe:
      path: "/metrics"
      port: 9633
  storage:
    - name: dev
      type: hostPath
      mountPath: /hostdev
      hostPath: /dev
      readOnly: true

service:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9633

grafana:
  dashboard:
    enabled: true
    dashboards:
      - name: smartctl-exporter
        title: "Disk S.M.A.R.T"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/smartctl-exporter/dashboards/smartctl-exporter.json"
        folder: "System"
