workload:
  type: "StatefulSet"
  image:
    repository: ghcr.io/maxdorninger/mediamanager/mediamanager
    tag: v1.7.0
  envsSecret:
    - name: DATABASE__HOST
      secret: media-manager-postgres-app
      key: host
    - name: DATABASE__USER
      secret: media-manager-postgres-app
      key: username
    - name: DATABASE__PASSWORD
      secret: media-manager-postgres-app
      key: password
  envs:
    - name: "DATABASE__PORT"
      value: "5432"
    - name: DATABASE__DBNAME
      value: "media-manager"
  strategy:
    type: OnDelete
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: false
  probes:
    readinessProbe:
      type: tcpSocket
      port: 8000
    livenessProbe:
      type: tcpSocket
      port: 8000
service:
  ports:
    - name: http
      port: 8000
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: media-manager.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "media-manager"
          port: 8000

autoscaling:
  enabled: false
