workload:
  type: "StatefulSet"
  image:
    repository: ghcr.io/maxdorninger/mediamanager/mediamanager
    tag: v1.7.0
  envsSecret:
    - name: DATABASE__HOST
      secret: radarr-postgres-app
      key: host
    - name: DATABASE__USER
      secret: radarr-postgres-app
      key: username
    - name: DATABASE__PASSWORD
      secret: radarr-postgres-app
      key: password
  envs:
    - name: "DATABASE__PORT"
      value: "5432"
    - name: DATABASE__DBNAME
      value: "media-manager"
  strategy:
    type: OnDelete
  probes:
    readinessProbe:
      type: tcpSocket
      port: 8000
    livenessProbe:
      type: tcpSocket
      port: 8000
  extraContainers:
    - name: exportarr
      image: "ghcr.io/onedr0p/exportarr:v2.2.0"
      ports:
        - containerPort: 9707
          name: http-metrics
          protocol: TCP
      env:
        - name: "PORT"
          value: "9707"
        - name: "URL"
          value: "http://localhost:7878"
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: radarr
              key: API_KEY
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      args:
        - radarr
service:
  ports:
    - name: http
      port: 8000
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: media-manager.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "media-manager"
          port: 8000

autoscaling:
  enabled: false
