workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

grafana:
  dashboard:
    enabled: true
    dashboards:
      - name: argocd
        title: "ArgoCD"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/argocd/dashboards/argocd.json"
        folder: "System"
