namespace: "argocd"
installCRDs: true

workload:
  image:
    registry: quay.io
    repository: argoproj/argocd
    tag: v2.14.2
  command:
    - /usr/local/bin/argocd-server
  args:
    - '--port=8080'
    - '--metrics-port=8083'
  probes:
    readinessProbe:
      type: httpGet
      path: "/healthz"
      port: 8080
      scheme: "HTTP"
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
      initialDelaySeconds: 15
    livenessProbe:
      type: httpGet
      path: "/healthz?full=true"
      port: 8080
      scheme: "HTTP"
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
      initialDelaySeconds: 15
  resources:
    preset: nano

service:
  ports:
    - name: http-metrics
      port: 8083
      protocol: TCP

expose:
  enabled: true
  type: NodePort
  ports:
    - name: http
      nodePort: 30180
      port: 8080
      protocol: TCP

rbac:
  enabled: true
  roles:
    role:
      rules:
        - apiGroups:
            - ''
          resources:
            - secrets
            - configmaps
          verbs:
            - create
            - get
            - list
            - watch
            - update
            - patch
            - delete
        - apiGroups:
            - argoproj.io
          resources:
            - applications
            - applicationsets
            - appprojects
          verbs:
            - create
            - get
            - list
            - watch
            - update
            - delete
            - patch
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - create
            - list 
    clusterRole:
      rules:
        - apiGroups:
            - '*'
          resources:
            - '*'
          verbs:
            - delete
            - get
            - patch
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - list
            - create
        - apiGroups:
            - ''
          resources:
            - pods
            - pods/log
          verbs:
            - get
        - apiGroups:
            - argoproj.io
          resources:
            - applications
            - applicationsets
          verbs:
            - get
            - list
            - update
            - watch
        - apiGroups:
            - batch
          resources:
            - jobs
          verbs:
            - create
        - apiGroups:
            - argoproj.io
          resources:
            - workflows
          verbs:
            - create
