namespace: "argocd"

workload:
  image:
    registry: quay.io
    repository: argoproj/argocd
    tag: v2.14.2
  args:
    - /usr/local/bin/argocd-server
    - '--port'
    - '8080'
    - '--metrics-port'
    - '8083'
    - '--repo-server'
    - argocd-repo-server:8081
    - '--logformat'
    - text
    - '--loglevel'
    - info
    - '--redis'
    - argocd-redis:6379
  envs:
    - name: ARGOCD_SERVER_NAME
      value: argocd-server
  envsSecret:
    - name: REDIS_PASSWORD
      secret: argocd-redis
      key: auth
  resources:
    preset: micro
  probes:
    readinessProbe:
      type: httpGet
      path: "/healthz"
      port: 8080
      scheme: "HTTP"
    livenessProbe:
      type: httpGet
      path: "/healthz?full=true"
      port: 8080
      scheme: "HTTP"
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /tmp
      ramDisk: false
      readOnly: false

service:
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: http-metrics
      port: 8083
      protocol: TCP

rbac:
  enabled: true
  roles:
    role:
      rules:
        - apiGroups:
            - ''
          resources:
            - secrets
            - configmaps
          verbs:
            - create
            - get
            - list
            - watch
            - update
            - patch
            - delete
        - apiGroups:
            - argoproj.io
          resources:
            - applications
            - applicationsets
            - appprojects
          verbs:
            - create
            - get
            - list
            - watch
            - update
            - delete
            - patch
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - create
            - list
    clusterRole:
      rules:
        - apiGroups:
            - '*'
          resources:
            - '*'
          verbs:
            - delete
            - get
            - patch
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - list
            - create
        - apiGroups:
            - ''
          resources:
            - pods
            - pods/log
          verbs:
            - get
        - apiGroups:
            - argoproj.io
          resources:
            - applications
            - applicationsets
          verbs:
            - get
            - list
            - update
            - watch
        - apiGroups:
            - batch
          resources:
            - jobs
          verbs:
            - create
        - apiGroups:
            - argoproj.io
          resources:
            - workflows
          verbs:
            - create

extraObjects:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cm
    data:
      admin.enabled: 'true'
      application.instanceLabelKey: argocd.argoproj.io/instance
      application.sync.impersonation.enabled: 'false'
      exec.enabled: 'false'
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
      server.rbac.log.enforce.enable: 'false'
      statusbadge.enabled: 'false'
      timeout.hard.reconciliation: 0s
      timeout.reconciliation: 180s
      url: https://argocd.example.com
