namespace: "thanos"

workload:
  annotations:
    override-url.version-checker.io/thanos-compact: quay.io/thanos/thanos
  type: Deployment
  image:
    registry: quay.io
    repository: thanos/thanos
    tag: v0.31.0
  args:
    - 'compact'
    - '--objstore.config-file=/etc/config/thanos.yaml'
    - '--data-dir=/data'
    - "--log.level=info"
    - "--retention.resolution-raw=2d"
    - "--retention.resolution-5m=10d"
    - "--retention.resolution-1h=10d"
    - "--consistency-delay=15m"
    - "--wait"
    - "--wait-interval=5m"
  probes:
    readinessProbe:
      path: "/-/ready"
      port: 10902
    livenessProbe:
      path: "/-/healthy"
      port: 10902
  storage:
    - configMapName: prometheus
      mountPath: /etc/config
      name: config
      type: configMap
    - mountPath: /data
      name: data
      ramDisk: false
      readOnly: false
      sizeLimit: 15Gi
      type: emptyDir

autoscaling:
  enabled: false

service:
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
    - name: http
      port: 10902
      protocol: TCP
    - name: cluster
      port: 19000
      protocol: TCP
