namespace: "argocd"

workload:
  image:
    registry: ghcr.io
    repository: dexidp/dex
    tag: v2.43.1
  command:
    - '/shared/argocd-dex'
  args:
    - 'rundex'
  envs:
    - name: "ARGOCD_DEX_SERVER_DISABLE_TLS"
      value: "false"
  probes:
    readinessProbe:
      path: "/healthz/ready"
      port: 5558
    livenessProbe:
      path: "/healthz/live"
      port: 5558
  storage:
    - name: static-files
      type: emptyDir
      mountPath: /shared
      ramDisk: false
      readOnly: false
    - name: dexconfig
      type: emptyDir
      mountPath: /tmp
      ramDisk: false
      readOnly: false
  initContainers:
    - name: copyutil
      image: "quay.io/argoproj/argocd:v3.0.3"
      command:
      - /bin/cp
      - -n
      - /usr/local/bin/argocd
      - /shared/argocd-dex
      volumeMounts:
      - mountPath: /shared
        name: static-files
      - mountPath: /tmp
        name: dexconfig

service:
  ports:
    - name: http
      port: 5556
      protocol: TCP
    - name: grpc
      port: 5557
      protocol: TCP
    - name: http-metrics
      port: 5558
      protocol: TCP

rbac:
  enabled: true
  roles:
    role:
      rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - configmaps
          verbs:
          - get
          - list
          - watch
