workload:
  image:
    registry: ghcr.io
    repository: mealie-recipes/mealie
    tag: v2.8.0
  probes:
    readinessProbe:
      type: tcpSocket
      port: 9000
    livenessProbe:
      type: tcpSocket
      port: 9000
  envs:
    - name: "ALLOW_SIGNUP"
      value: "false"
    - name: "PUID"
      value: "1000"
    - name: "PGID"
      value: "1000"
    - name: "TZ"
      value: "Europe/London"
    - name: "BASE_URL"
      value: "http://mealie.projectwhitebox.com"
    - name: "ALLOW_PASSWORD_LOGIN"
      valie: "false"
    - name: "DB_ENGINE"
      value: "postgres"
    - name: "POSTGRES_PORT"
      value: "5432"
    - name: "POSTGRES_DB"
      value: "mealie"
    - name: "OIDC_AUTH_ENABLED"
      value: "true"
    - name: "OIDC_SIGNUP_ENABLED"
      value: "true"
    - name: "OIDC_CONFIGURATION_URL"
      value: "https://accounts.google.com/.well-known/openid-configuration"
    - name: "OIDC_CLIENT_ID"
      value: "429988516792-hpicb5767cg7qlr32pjkgfl4ceub6lss.apps.googleusercontent.com"
    - name: "OIDC_AUTO_REDIRECT"
      value: "true"
    - name: "OIDC_PROVIDER_NAME"
      valie: "Google"
  envsSecret:
    - name: POSTGRES_SERVER
      secret: mealie-postgres-app
      key: host
    - name: POSTGRES_USER
      secret: mealie-postgres-app
      key: username
    - name: POSTGRES_PASSWORD
      secret: mealie-postgres-app
      key: password
    - name: OIDC_CLIENT_SECRET
      secret: mealie
      key: OIDC_CLIENT_SECRET
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /app/data
    - nane: data
      type: emptyDir
      mountPath: /nltk_data
service:
  ports:
  - name: http
    port: 9000
    protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
  - host: mealie.projectwhitebox.com
    path: /
    pathType: "Prefix"
    tls:
      enabled: false
    backend:
      service:
        name: "mealie"
        port: 9000

extraObjects:
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: mealie
      namespace: mealie
    spec:
      encryptedData:
        OIDC_CLIENT_SECRET: AgAe4lTZ1NNXebi9Q+PQYn0cBgHtRQUi6H27LyUtIfx9Hh1rxNVnXZX3zkRtTVofH51tTEr3+bgmNUONqHDonNTPecQNE5YqDrTyc9f4X2Xao7koqQswgXav6nhnJO/vkBc37EoS+9m2KQfm5o2gc+WN5EKkX+z3Q1HM+8UGXaRPJNtx9sIbI8OoZSkMP71NfQdvjh/WC82hDFKBvo9jbe95M+LDvqXAAdnQboEEhSYjtZwoOfB9HSIZM3zmFKAumfCcLMfDTb8IZmUw1aIQvgE6KPgh3THq30KGJmK5Zu+OaBZxfcS0KX/akGRiHlq7gjlzCBCS9FzANJrtg9aeTONaJhdftmyi10h8QtEU0fxDFSgIvawOe+Xq9G9p6tbvnO+eLN5JZOevsyvXAMov4uxPVwwv0xtWTcmCrnaT5Nm4p/Pw3+jtbE+3kjPI3bjqZXJX4r182eWryzkiezj1jDDdoFqeOarSQiCjtwCKZriIf57e4BWgimpUTJbeYKJPuCCrxUiCJ/CnTzfKlNHlJCPQyTTlFVzYPcF6GJOVaZnw3oznCIKe33MA6rWw7pu7JGrTPwYW9C4tNVwrwBRYHCHcpS4+/FQQr3r/8USGRGaWV6LRa9ATq1Giz9vEtmZ7dl0n8AlyfrfKZd8ZaB3izOzXgwalNvNYb3eVMhixSyx/RQL5bZz8jxnTYhaBaDYLBRq3+OGKo5SHUHytlBxzmIuYMRcqkZtqY9fKfPdoLDmW1My4hg==
      template:
        metadata:
          creationTimestamp: null
          name: mealie
          namespace: mealie
        type: Opaque
