global:
  chart: "kube-prometheus-stack"
  repository: "https://prometheus-community.github.io/helm-charts"
  version: "68.*.*"

crds:
  enabled: true

cleanPrometheusOperatorObjectNames: true
fullnameOverride: "t"
