namespace: "thanos"
workload:
  type: StatefulSet
  image:
    registry: quay.io
    repository: prometheus/prometheus
    tag: v3.4.1
  args:
    - '--config.file=/etc/config/prometheus.yaml'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--web.enable-lifecycle'
    - '--web.enable-admin-api'
    - "--storage.tsdb.no-lockfile"
    - "--storage.tsdb.min-block-duration=2h"
    - "--storage.tsdb.max-block-duration=2h"
    - '--storage.tsdb.path=/prometheus'
  envsSecret:
    - name: OBJSTORE_CONFIG
      secret: thanos
      key: thanos.yaml
  probes:
    readinessProbe:
      path: "/-/ready"
      port: 9090
    livenessProbe:
      path: "/-/healthy"
      port: 9090
  storage:
    - name: config
      type: configMap
      mountPath: /etc/config
      configMapName: prometheus
    - name: prometheus-data
      type: pvcTemplate
      mountPath: /prometheus
      accessModes:
        - "ReadWriteOnce"
      storageClass: "longhorn"
      size: "25Gi"
      readOnly: false
  extraContainers:
    - name: thanos
      image: "quay.io/thanos/thanos:v0.38.0"
      ports:
        - containerPort: 10901
        - containerPort: 10902
      env:
      - name: OBJSTORE_CONFIG
        valueFrom:
          secretKeyRef:
            key: thanos.yaml
            name: thanos
      args:
        - 'sidecar'
        - '--objstore.config=$(OBJSTORE_CONFIG)'
        - '--tsdb.path=/prometheus'
        - '--prometheus.url=http://localhost:9090'
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /-/ready
          port: 10902
          scheme: HTTP
        initialDelaySeconds: 15
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /-/healthy
          port: 10902
          scheme: HTTP
        initialDelaySeconds: 15
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      volumeMounts:
        - name: config
          mountPath: /etc/config
        - name: prometheus-data
          mountPath: /prometheus

service:
  clusterIP: "None"
  ports:
    - name: http
      port: 9090
      protocol: TCP
    - name: grpc
      port: 10901
      protocol: TCP

configMap:
  enabled: true
  configMaps:
    - name: "prometheus"
      data:
        prometheus.yaml: |
          global:
            scrape_interval: 5s
            evaluation_interval: 5s
            external_labels:
              cluster: prometheus-ha
              replica: ${POD_NAME}

          scrape_configs:
            # Scraper for Kubernetes services with HTTP metrics
            - job_name: 'kube-http-services'
              kubernetes_sd_configs:
                - role: endpoints
              relabel_configs:
                - source_labels: [__meta_kubernetes_endpoint_port_name]
                  regex: http-metrics
                  action: keep
                - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
                  target_label: service
                  separator: /
                  replacement: $1/$2
                - source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: instance
                - action: labeldrop
                  regex: __meta_kubernetes.*

            # Scraper for Kubernetes services with HTTPS metrics
            - job_name: 'kube-https-services'
              scheme: https
              tls_config:
                insecure_skip_verify: true
              kubernetes_sd_configs:
                - role: endpoints
              relabel_configs:
                - source_labels: [__meta_kubernetes_endpoint_port_name]
                  regex: https-metrics
                  action: keep
                - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
                  target_label: service
                  separator: /
                  replacement: $1/$2
                - source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: instance
                - action: labeldrop
                  regex: __meta_kubernetes.*

            # Scraper for kubernetes api server
            - job_name: "kube-apiserver"
              scheme: https
              metrics_path: /metrics
              authorization:
                type: Bearer
                credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_name]
                  regex: .*controlplane.*
                  action: keep
                - source_labels: [__meta_kubernetes_node_address_InternalIP]
                  regex: (.+)
                  replacement: ${1}:6443
                  target_label: __address__
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: instance

            # Scraper for kubernetes proxy
            - job_name: "kube-proxy"
              scheme: http
              metrics_path: /metrics
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_address_InternalIP]
                  regex: (.+)
                  replacement: ${1}:10249
                  target_label: __address__
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: instance

            # Scraper for kubernetes controller manager
            - job_name: "kube-controller-manager"
              scheme: https
              metrics_path: /metrics
              authorization:
                type: Bearer
                credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_name]
                  regex: .*controlplane.*
                  action: keep
                - source_labels: [__meta_kubernetes_node_address_InternalIP]
                  regex: (.+)
                  replacement: ${1}:10257
                  target_label: __address__
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: instance

            # Scraper for kubernetes scheduler
            - job_name: "kube-scheduler"
              scheme: https
              metrics_path: /metrics
              authorization:
                type: Bearer
                credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_name]
                  regex: .*controlplane.*
                  action: keep
                - source_labels: [__meta_kubernetes_node_address_InternalIP]
                  regex: (.+)
                  replacement: ${1}:10259
                  target_label: __address__
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: instance

            # Scraper for cadvisor
            - job_name: "kube-cadvisor"
              scheme: https
              metrics_path: /metrics/cadvisor
              authorization:
                type: Bearer
                credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)

            # Kubelet
            - job_name: "kubelet"
              scheme: https
              metrics_path: /metrics
              authorization:
                type: Bearer
                credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)

            # Scraper for kubernetes etcd cluster
            - job_name: "etcd"
              scheme: http
              metrics_path: /metrics
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_name]
                  regex: .*controlplane.*
                  action: keep
                - source_labels: [__meta_kubernetes_node_address_InternalIP]
                  regex: (.+)
                  replacement: ${1}:2381
                  target_label: __address__
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: instance

            # Scraper for containerd
            - job_name: "containerd"
              scheme: http
              metrics_path: /v1/metrics
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_address_InternalIP]
                  regex: (.+)
                  replacement: ${1}:11234
                  target_label: __address__
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: instance
          
            # Solution to monitor NFS usage
            - job_name: 'directory-size-exporter'
              static_configs:
                - targets: ['10.0.0.10:8000']


rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - nodes
            - nodes/proxy
            - nodes/metrics
            - services
            - endpoints
            - pods
            - ingresses
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - extensions
            - networking.k8s.io
          resources:
            - ingresses/status
            - ingresses
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - discovery.k8s.io
          resources:
            - endpointslices
          verbs:
            - get
            - list
            - watch
        - nonResourceURLs:
            - /metrics
          verbs:
            - get

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: prometheus.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "prometheus"
          port: 9090

extraObjects:
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: thanos
      namespace: thanos
    spec:
      encryptedData:
        thanos.yaml: AgApvVcpP0HXRXtuCUI9jfOPfdUXwzaB8IUOVR15vz+7hT5W653lDXGGvlFP1+rBCsoPvWRCDLSxKqUO3cESc7oNErRczC4FeLoslzGedOUl/OwjvV7EkKbpxTNWxQZ+YFXzyr/0Qx+kGRRGlKtNTcusjeWNz5D5NQgecMCojpPERyhk3hihn4ADULkJmhhOHcKcojMqNMGuP73BBwZ9RvnTPZFj3YGFUk9nmOEWFC5gzEpHDDOaXmRiu3NE+3lhKQmTwFbAQLJFcXSnZNSYlCtUgLUVb+7R/VuO+T4nE95LF+JmDSV7MyPe0Wx9oXq6G+f7bZo3eq7tLU+7wH9qNp90eCRlAy+CIsa2lm6XUTSAXS/3WQVgfhod4uU9rl3HdvBSZ6JuT5rbWFjIQTi9VJA0iqzm8quewolPHBZZy7MTagAEnJrOy6qQkZHMRH4dcRiJStaXUIeojorwlB6JuCUVtY+je2ul3zxTEf9PgP3BGpvMpja49YKF7O8u2r5jCnfG9GcaUwbkYxAmKCWZjDt5Hnl5GHxP0JwO//VcemPrAI4WSk41UUK2/uDg3G2ka+W+Z3Fj8+/2UfpgafjqLvZm6Fz7tzAgBel6kg6pFvYM56ulrYKB05Po22uCGC95Jv4w/0XNJWKTWS7YreX3WNnRuPo4SxqFREnV8iZKMkUh+zF96WN4wODg87HfvYVFXWgMjbyBNGPy/GQQB+XtdjUqDuCrktvmTeoleisUQFfasaRSonF9HNp5GvLK+Cj/jf4QF3mcPC5cZ1J4pzT3bXKiWZTIPvd6NybljuoCNmh62zZq5XooPObQIAZJp/PnNeLtBMeV31x04FZ/DcdATidlrAaKbBxYI4hAD3bOp71YLv+H0keM4bizi7T4ZNo8mlYrvH0getf3rmIYxXlngw3iQHPDpoLa/A+uEL/7JtaMC40Qz1TExBw=
      template:
        metadata:
          name: thanos
          namespace: thanos
        type: Opaque
