workload:
  replicaCount: 1
  image:
    registry: "quay.io"
    repository: "prometheus/prometheus"
    tag: "v3.1.0"
  args:
    - '--storage.tsdb.retention.time=15d'
    - '--config.file=/etc/config/prometheus.yaml'
    - '--storage.tsdb.path=/data'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--web.enable-lifecycle'
  resources:
    preset: "micro"
  storage:
    - name: config
      type: configMap
      mountPath: /etc/config
      configMapName: prometheus
    - name: data
      type: emptyDir
      mountPath: /data
      sizeLimit: 5Gi
      readOnly: false
      ramDisk: false

service:
  ports:
    - name: http
      protocol: TCP
      port: 9090

autoscaling:
  enabled: false

configMap:
  enabled: true
  data:
    prometheus.yaml: |
      global:
        evaluation_interval: 1m
        scrape_interval: 1m
        scrape_timeout: 10s
      scrape_configs:
        - job_name: 'kubernetes-services'
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            # Only keep endpoints with ports named "metrics"
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              regex: metrics
              action: keep
            # Extract the namespace and service name for better labels
            - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
              target_label: service
              separator: /
              replacement: $1/$2
            # Remove unnecessary labels
            - action: labeldrop
              regex: __meta_kubernetes.*

ingress:
  enabled: true
  entryPoints:
    - internalwebsecure
    - internalweb
  port: http
  prefix: "prometheus"
  tls: true

rbac:
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - nodes
            - nodes/proxy
            - nodes/metrics
            - services
            - endpoints
            - pods
            - ingresses
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - extensions
            - networking.k8s.io
          resources:
            - ingresses/status
            - ingresses
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - discovery.k8s.io
          resources:
            - endpointslices
          verbs:
            - get
            - list
            - watch
        - nonResourceURLs:
            - /metrics
          verbs:
            - get
