global:
  chart: "kube-prometheus-stack"
  repository: "https://prometheus-community.github.io/helm-charts"
  version: "68.*.*"

crds:
  enabled: true

alertmanager:
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

  alertmanagerSpec:
    replicas: 2
    logFormat: "json"
