workload:
  replicaCount: 1
  image:
    registry: "quay.io"
    repository: "prometheus/prometheus"
    tag: "v3.1.0"
  args:
    - '--storage.tsdb.retention.time=15d'
    - '--config.file=/etc/config/prometheus.yaml'
    - '--storage.tsdb.path=/data'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--web.enable-lifecycle'
  resources:
    preset: "micro"
  storage:
    - name: config
      type: configMap
      mountPath: /etc/config
      configMapName: prometheus
    - name: data
      type: emptyDir
      mountPath: /data
      sizeLimit: 5Gi
      readOnly: false
      ramDisk: false

service:
  ports:
    - name: http
      protocol: TCP
      port: 9090

autoscaling:
  enabled: false

configMap:
  enabled: true
  data:
    prometheus.yaml: |
      global:
        evaluation_interval: 1m
        scrape_interval: 1m
        scrape_timeout: 10s
    scrape_configs:
      - job_name: 'kubernetes-services-metrics-port'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          # Only keep endpoints where the port name is 'metrics'
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics
          # Construct the __address__ using the endpoint address and port number
          - source_labels: [__meta_kubernetes_endpoint_address_target, __meta_kubernetes_endpoint_port_number]
            action: replace
            target_label: __address__
            separator: ':'
            replacement: $1:$2
          # Set the instance label to namespace/service/port
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: replace
            target_label: instance
            separator: /
            replacement: $1/$2/$3
          # Optional: Add a job label for better identification
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: replace
            target_label: job
            separator: /
            replacement: $1/$2

ingress:
  enabled: true
  entryPoints:
    - internalwebsecure
    - internalweb
  port: http
  prefix: "prometheus"
  tls: true

rbac:
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - nodes
            - nodes/proxy
            - nodes/metrics
            - services
            - endpoints
            - pods
            - ingresses
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - extensions
            - networking.k8s.io
          resources:
            - ingresses/status
            - ingresses
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - discovery.k8s.io
          resources:
            - endpointslices
          verbs:
            - get
            - list
            - watch
        - nonResourceURLs:
            - /metrics
          verbs:
            - get
