namespace: "immich"

workload:
  image:
    registry: ghcr.io
    repository: alangrainger/immich-public-proxy
    tag: 1.11.3
  envs:
    - name: "IMMICH_URL"
      value: "http://immich-server.immich.svc.cluster.local:2283"
  probes:
    readinessProbe:
      path: "/share/healthcheck"
      port: 3000
    livenessProbe:
      path: "/share/healthcheck"
      port: 3000

service:
  ports:
    - name: http
      port: 3000
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: immich-frontend.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "immich-public-proxy"
          port: 3000

autoscaling:
  enabled: false
