namespace: "argocd"

workload:
  annotations:
    override-url.version-checker.io/argocd-applicationset-controller: quay.io/argoproj/argocd
  replicaCount: 3
  image:
    registry: quay.io
    repository: argoproj/argocd
    tag: v2.14.2
  command:
    - 'argocd-applicationset-controller'
  args:
    - '--metrics-addr=:8080'
    - '--probe-addr=:8081'
    - '--webhook-addr=:7000'
    - '--argocd-repo-server=argocd-repo-server:8081'
    - '--logformat=text'
    - '--loglevel=info'
    - '--enable-leader-election=true'
  envs:
    - name: ARGOCD_SERVER_NAME
      value: argocd-server
  probes:
    readinessProbe:
      type: tcpSocket
      port: 8081
    livenessProbe:
      type: exec
      command:
        - pgrep
        - -f
        - argocd-applicationset-controller
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /tmp
      ramDisk: false
      readOnly: false

service:
  ports:
    - name: webhook
      port: 7000
      protocol: TCP
    - name: http-metrics
      port: 8080
      protocol: TCP
    - name: healthcheck
      port: 8081
      protocol: TCP

rbac:
  enabled: true
  roles:
    role:
      rules:
        - apiGroups:
            - argoproj.io
          resources:
            - applications
            - applicationsets
            - applicationsets/finalizers
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - argoproj.io
          resources:
            - applicationsets/status
          verbs:
            - get
            - patch
            - update
        - apiGroups:
            - argoproj.io
          resources:
            - appprojects
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - create
            - get
            - list
            - patch
            - watch
        - apiGroups:
            - ''
          resources:
            - configmaps
          verbs:
            - create
            - update
            - delete
            - get
            - list
            - patch
            - watch
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
            - extensions
          resources:
            - deployments
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
