namespace: "argocd"

workload:
  image:
    registry: quay.io
    repository: argoproj/argocd
    tag: v2.14.2
  args:
    - /usr/local/bin/argocd-applicationset-controller
    - '--metrics-addr=:8080'
    - '--probe-addr=:8081'
    - '--webhook-addr=:7000'
    - '--argocd-repo-server'
    - argocd-repo-server:8081
    - '--logformat'
    - text
    - '--loglevel'
    - info
    # - --enable-leader-election=true
  envs:
    - name: ARGOCD_SERVER_NAME
      value: argocd-server
  envsSecret:
    - name: REDIS_PASSWORD
      secret: argocd-redis
      key: auth
  resources:
    preset: micro
  probes:
    readinessProbe:
      type: httpGet
      path: "/healthz"
      port: 8081
      scheme: "HTTP"
    livenessProbe:
      type: httpGet
      path: "/healthz?full=true"
      port: 8081
      scheme: "HTTP"
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /tmp
      ramDisk: false
      readOnly: false

service:
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
    - name: healthcheck
      port: 8081
      protocol: TCP
    - name: webhook
      port: 7000
      protocol: TCP
