workload:
  image:
    repository: ghcr.io/kanbn/kan
    tag: 0.2.3
  probes:
    readinessProbe:
      type: tcpSocket
      port: 3000
    livenessProbe:
      type: tcpSocket
      port: 3000
  envsSecret:
    - name: POSTGRES_URL
      secret: kan-postgres-app
      key: uri
  envs:
    - name: "NEXT_PUBLIC_BASE_URL"
      value: "https://kan.projectwhitebox.com"
    - name: "BETTER_AUTH_SECRET"
      value: "test123"
  resources:
    preset: ""
    custom:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "10000m"
        memory: "5Gi"

service:
  ports:
    - name: http
      port: 3000
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: kan.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "kan"
          port: 3000

autoscaling:
  enabled: false
