extraObjects:
  - |
    apiVersion: redis.redis.opstreelabs.in/v1beta2
    kind: RedisCluster
    metadata:
      name: argocd-redis
    spec:
      clusterSize: 3
      kubernetesConfig:
        image: quay.io/opstree/redis:v7.0.15
      persistenceEnabled: false
      podSecurityContext:
        fsGroup: 1000
        runAsUser: 1000
      port: 6379
      redisExporter:
        enabled: true
        image: quay.io/opstree/redis-exporter:v1.44.0
        imagePullPolicy: IfNotPresent
        port: 9121
      redisFollower:
        replicas: 3
      redisLeader:
        replicas: 3
      storage:
        nodeConfVolume: false
