namespace: "argocd"

workload:
  type: StatefulSet
  image:
    repository: redis
    tag: 7.0.15-alpine
  replicaCount: 1
  args:
    - "--save"
    - ""
    - "--appendonly"
    - "no"
  resources:
    preset: micro
  probes:
  readinessProbe:
    type: tcpSocket
    port: 6379
  livenessProbe:
    type: tcpSocket
    port: 6379

service:
  labels:
    argocd.argoproj.io/instance: argocd-redis
  ports:
    - name: redis
      port: 6379
      protocol: TCP
