namespace: "thanos"

workload:
  annotations:
    override-url.version-checker.io/thanos-query-frontend: quay.io/thanos/thanos
  image:
    registry: quay.io
    repository: thanos/thanos
    tag: v0.31.0
  args:
    - 'query-frontend'
    - '--http-address=0.0.0.0:9090'
    - '--query-frontend.downstream-url=http://thanos-query.thanos.svc.cluster.local:10902'
  probes:
    readinessProbe:
      type: httpGet
      path: "/-/ready"
      port: 9090
      scheme: "HTTP"
    livenessProbe:
      type: httpGet
      path: "/-/healthy"
      port: 9090
      scheme: "HTTP"
  resources:
    preset: micro

autoscaling:
  enabled: false

service:
  ports:
    - name: http
      port: 9090
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: thanos.openjamlab.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: true
        secretName: "letsencrypt-wildcard-certificate"
      backend:
        service:
          name: "thanos-query-frontend"
          port: 9090

grafana:
  datasource:
    enabled: true
    spec:
      resyncPeriod: 30s
      allowCrossNamespaceImport: true
      instanceSelector:
        matchLabels:
          dashboards: "grafana"
      datasource:
        name: thanos
        type: prometheus
        access: proxy
        basicAuth: false
        url: http://thanos-query-frontend.thanos.svc.cluster.local:9090
        isDefault: true
