namespace: "kube-system"

workload:
  enabled: false

service:
  ports:
  - name: https-metrics
    port: 10257
    protocol: TCP
    targetPort: 10257
  selector:
    app.kubernetes.io/name: kube-controller-manager

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

