workload:
  image:
    registry: "ghcr.io"
    repository: "stakater/reloader"
    tag: "v1.2.0"
  args:
    - '--log-format=json'
    - '--log-level=info'
    - '--reload-on-delete=true'
    - '--enable-ha=true'
    - '--auto-reload-all=true'
  resources:
    preset: "nano"

service:
  ports:
    - name: metrics
      protocol: TCP
      port: 9090

serviceMonitor:
  enabled: true

rbac:
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ""
          resources:
            - secrets
            - configmaps
          verbs:
            - list
            - get
            - watch
        - apiGroups:
            - "apps"
          resources:
            - deployments
            - daemonsets
            - statefulsets
          verbs:
            - list
            - get
            - update
            - patch
        - apiGroups:
            - "batch"
          resources:
            - cronjobs
          verbs:
            - list
            - get
        - apiGroups:
            - "batch"
          resources:
            - jobs
          verbs:
            - create
        - apiGroups:
            - "coordination.k8s.io"
          resources:
            - leases
          verbs:
            - create
            - get
            - update
        - apiGroups:
            - ""
          resources:
            - events
          verbs:
            - create
            - patch
