global:
  name: "reloader"
  repository: "https://stakater.github.io/stakater-charts"
  version: "1.2.*"

reloader:
  autoReloadAll: true
  reloadOnDelete: true
  syncAfterRestart: true
  logFormat: json
  enableHA: false
  readOnlyRootFileSystem: true
  deployment:
    replicas: 2
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
    