workload:
  enabled: true
  image:
    registry: "ghcr.io"
    repository: "stakater/reloader"
    tag: "v1.2.0"
  args:
    - '--log-format=json'
    - '--log-level=info'
    - '--reload-on-delete=true'
    - '--enable-ha=true'
    - '--auto-reload-all=true'
  replicaCount: 2
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
  probes:
    livenessProbe:
      type: httpGet
      path: /metrics
      port: metrics
      scheme: HTTP
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
      initialDelaySeconds: 10
    readinessProbe:
      type: httpGet
      path: /metrics
      port: metrics
      scheme: HTTP
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
      initialDelaySeconds: 10
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: reloader
            topologyKey: kubernetes.io/hostname
          weight: 100
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 1

pdb:
  enabled: true
  maxUnavailable: "1"

service:
  enabled: true
  type: ClusterIP
  ports:
    - name: metrics
      protocol: TCP
      port: 9090

serviceAccount:
  enabled: true
  automountServiceAccountToken: true

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - secrets
            - configmaps
          verbs:
            - list
            - get
            - watch
        - apiGroups:
            - apps
          resources:
            - deployments
            - daemonsets
            - statefulsets
          verbs:
            - list
            - get
            - update
            - patch
        - apiGroups:
            - batch
          resources:
            - cronjobs
          verbs:
            - list
            - get
        - apiGroups:
            - batch
          resources:
            - jobs
          verbs:
            - create
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
            - get
            - update
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - create
            - patch
