workload:
  annotations:
    override-url.version-checker.io/traefik: docker.io/traefik 
  image:
    repository: traefik
    tag: v3.2.2
  args:
    # Entrypoints
    - '--entryPoints.metrics.address=:9100/tcp'
    - '--entryPoints.traefik.address=:8080/tcp'
    - '--entryPoints.ping.address=:8082/tcp'
    - '--entryPoints.externalweb.address=:81/tcp'
    - '--entryPoints.internalweb.address=:80/tcp'
    - '--entryPoints.externalwebsecure.address=:444/tcp'
    - '--entryPoints.internalwebsecure.address=:443/tcp'
    # TLS
    - '--entryPoints.externalwebsecure.http.tls=true'
    - '--entryPoints.internalwebsecure.http.tls=true'
    # Metrics
    - '--metrics.prometheus=true'
    - '--metrics.prometheus.entrypoint=metrics'
    - '--metrics.addinternals=true'
    # Healthcheck
    - '--ping=true'
    - '--ping.entryPoint=ping'
    # Dashboard
    - '--api=true'
    - '--api.dashboard=true'
    - '--api.insecure=true'
    # Providers
    - '--providers.kubernetesingress=true'
    - '--providers.kubernetesingress.allowemptyservices=true'
    # Logs
    - '--log.format=json'
    - '--log.level=INFO'
    # Access logs
    - '--accesslog=true'
    - '--accesslog.addinternals=true'
    - '--accesslog.format=json'
    - '--accesslog.fields.defaultmode=keep'
    - '--accesslog.fields.headers.defaultmode=drop'
  probes:
    readinessProbe:
      type: httpGet
      path: "/ping"
      port: 8082
      scheme: "HTTP"
    livenessProbe:
      type: httpGet
      path: "/ping"
      port: 8082
      scheme: "HTTP"
  resources:
    preset: micro

service:
  ports:
    - name: traefik
      port: 8080
      protocol: TCP
    - name: ping
      port: 8082
      protocol: TCP
    - name: http-metrics
      port: 9100
      protocol: TCP

expose:
  enabled: true
  type: NodePort
  ports:
    - name: externalweb
      nodePort: 30081
      port: 81
      protocol: TCP
    - name: internalweb
      nodePort: 30080
      port: 80
      protocol: TCP
    - name: externalwebsecure
      nodePort: 30444
      port: 444
      protocol: TCP
    - name: internalwebsecure
      nodePort: 30443
      port: 443
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - nodes
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - services
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - discovery.k8s.io
          resources:
            - endpointslices
          verbs:
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - extensions
            - networking.k8s.io
          resources:
            - ingressclasses
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - traefik.io
          resources:
            - ingressroutes
            - ingressroutetcps
            - ingressrouteudps
            - middlewares
            - middlewaretcps
            - serverstransports
            - serverstransporttcps
            - tlsoptions
            - tlsstores
            - traefikservices
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - extensions
            - networking.k8s.io
          resources:
            - ingressclasses
            - ingresses
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - extensions
            - networking.k8s.io
          resources:
            - ingresses/status
          verbs:
            - update

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: traefik.openjamlab.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: true
        secretName: "letsencrypt-wildcard-certificate"
      backend:
        service:
          name: "traefik"
          port: 8080

ingressClass:
  enabled: true
  isDefault: true
  controller: "traefik.io/ingress-controller"

secret:
  enabled: true
  namespace: "cert-manager"

certificate:
  enabled: true
  spec:
    secretName: "letsencrypt-wildcard-certificate"
    dnsNames:
      - 'openjamlab.com'
      - '*.openjamlab.com'
    issuerRef:
      name: "traefik"
      kind: ClusterIssuer
    secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

issuer:
  enabled: true
  type: ClusterIssuer
  spec:
    acme:
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: letsencrypt-acme-key

grafana:
  dashboard:
    enabled: true
    dashboards:
      - name: traefik
        title: "Traefik"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/traefik/dashboards/traefik.json"
        folder: "System"
