global:
  chart: "traefik"
  repository: "https://traefik.github.io/charts"
  version: "34.1.*"

deployment:
  replicas: 2

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

ingressClass:
  enabled: true
  isDefaultClass: true
  name: "traefik"

gateway:
  enabled: false

gatewayClass:
  enabled: false

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: true

logs:
  general:
    format: "json"
  access:
    enabled: true
    format: "json"

globalArguments: []

additionalArguments:
  - '--entryPoints.internalweb.address=:81/tcp'
  - '--entryPoints.internalwebsecure.address=:444/tcp'
  - '--entryPoints.internalwebsecure.http.tls=true'

ports:
  traefik:
    port: 8080
    protocol: TCP
  http:
    port: 80
    exposedPort: 80
    nodePort: 30080
  https:
    port: 443
    exposedPort: 443
    nodePort: 30443
  internalhttp:
    port: 81
    exposedPort: 81
    nodePort: 30081
  internalhttps:
    port: 444
    exposedPort: 444
    nodePort: 30444

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
