service:
  type: NodePort

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: descheduler
        topologyKey: kubernetes.io/hostname

ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443

deployment:
  replicas: 2

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

ingressClass:
  enabled: false

gateway:
  enabled: false

gatewayClass:
  enabled: false

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

providers:
  kubernetesIngress:
    enabled: false

logs:
  general:
    format: "json"
    level: "INFO"
  access:
    enabled: true
    format: "json"

globalArguments: []
