namespace: "prowlarr"

service:
  enabled: false

serviceAccount:
  enabled: false

workload:
  enabled: false

pdb:
  enabled: false

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: postgresql.cnpg.io/v1
    kind: ScheduledBackup
    metadata:
      name: prowlarr
      namespace: prowlarr
    spec:
      schedule: "0 0 0 * * *"
      backupOwnerReference: self
      cluster:
        name: prowlarr-postgres
  - |
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: prowlarr-postgres
    spec:
      backup:
        retentionPolicy: "7d"
        barmanObjectStore:
          destinationPath: "s3://postgres-backups/prowlarr"
          endpointURL: https://s3.eu-central-003.backblazeb2.com
          s3Credentials:
            accessKeyId:
              name: prowlarr-postgres-s3
              key: S3_ACCESS_KEY
            secretAccessKey:
              name: prowlarr-postgres-s3
              key: S3_SECRET_KEY
          wal:
            compression: gzip
          data:
            compression: gzip
      description: "Prowlarr Database"
      imageName: ghcr.io/cloudnative-pg/postgresql:17.5
      instances: 1
      bootstrap:
        initdb:
          database: "prowlarr-main"
          owner: prowlarr
          postInitSQL:
            - CREATE DATABASE "prowlarr-log" OWNER prowlarr
            - COMMIT
      enableSuperuserAccess: false
      storage:
        pvcTemplate:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi
          storageClassName: "openebs"
          volumeMode: Filesystem
      resources:
        requests:
          cpu: "10m"
          memory: "10Mi"
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: prowlarr-postgres-s3
      namespace: prowlarr
    spec:
      encryptedData:
        S3_ACCESS_KEY: AgBBnIf+C6domDy5JqdaME6ex9Pg/8hQ/hQuPid5YZLJB/eUZIjMmcMy0kjr/MAlq/9FgE7JPSSPVEyp7pTx9uIzTohvw0xojtqODKn0ZdLIr73lBzPuAP+b+DgQbL+pTSY7XuIQ/ENO6pTZuw0Qg5xB/mkhgoM9y3dsd3nCKvKIBAQpbWNuVf3p92CZyUeTl4+RLeVe4BUTnPTPjSDSnPby4R9EgmkVANeuTwOz7GBQ+t2k5LHZx8A0V2tDtpPN17c1jQeA3MfkdMYjJiTKeboDaLylmuzBh9Q9YriRT3h5qcMEByJKvimZxxuGM2vvvCYG58+iA51BwHnsDc9AvG45KE2QCXWSsOoU6qYqrOFOfzVQLsySYaW1Sx5i1uz6CulqeNmtY1vkIXlbmFUJiufeIzvxTVRum0B4zyrv0xc8ZzAhsCVd8pWbvsfNXAAYr7wtKe0IxcRsDoKsKfOjLnnJYBVdL8wYvezS14bhydilceSt7w/iTCsOpiZNBB1jm9eJJt/sUSn4w4OM4Ex8yAKiSjX2/p/nj7DgLqQPxYWCVlz3qZIpvirw8kYBeJr+Ac6XTPMORQieZLbWU+t6N0WVJHFs1+3xockjts5kENTIxZkDlJIlxiKkWVJC3L4hRVPed7VuoMuti67y9dBcd7z5UT2K7IFNMg4zXHNvHVOLpsFsj4OipDoJfF6ekG+tzXFfCLAUUMq7wRUks6kgmrjkN8DYd3QBOcww
        S3_SECRET_KEY: AgACH4thfvtG5jIiMDtQpngtSppfv9HlNwbOAZi0DT2LX3sLtSARhuJRjspQCgY4X/P3QJxT8TAZvME9mKB2AlJZN1dQoFn7mp0NvnDQR+V42m37jS/Sw4B5pQ9vr6l+hly6xQ7XrmzUSxV/vaUdlDVfYDLbbzvPdAEe7s3l/TJMC9XXSy1/RTbdC/mHE8S6Y2HnKZ8ED5MG77sp0iY/4mW6jtTNIlsbu2+ad1/a4cWpMV5R38hFp7VZHcB+JbEf2ROwZ6SXQaf9uP1FAy3qmyuBOa/o8xCLxWsan72pbMynP5QzxJevaEYbV3qjWKnHWfg6c/khwUqa0jUDBFGMwxAWcFBu9UOaQDs8A/p0YP7lRZVgLCfWnkAjgdedb3TovPP/3vxpgmCPEoIp3jGywfeWzhcZj7xlAVyrQMklKyvofWkriK+LPIJvAIcn8dYNsSSs1OfpAqfssHBExkexstGFGHcje26UZNQcetULEOtr/kg77L2pxMMm0sNVzcHWG0ZIWFjt3cmhztZ4tIkl9cpyDbGlbbAjap7QWu5sYyVEoFyOpOFQf6O8yMAXwotlYG30oo7+GDWvhc431YiirIcX5iYkbEo5ir2XBTQxKpozZrOsCPHNyRNDr+VZTnQoPfcbmdMD/HjVFQVkC2FORIPX2yT3W5YOoiCNjQ91h3wKnreLiJVnlai3+fRmCXnaZAxolKKSeFfO3eTXYkfl6HsUY899TvW8pZmZuQE5phJD
      template:
        metadata:
          name: prowlarr-postgres-s3
          namespace: prowlarr
        type: Opaque
