namespace: "kyverno"
installCRDs: true

workload:
  image:
    registry: "reg.kyverno.io"
    repository: "kyverno/kyverno"
    tag: "v1.13.3"
  args:
    - '--caSecretName=kyverno-admission-controller.kyverno.svc.kyverno-tls-ca'
    - '--tlsSecretName=kyverno-admission-controller.kyverno.svc.kyverno-tls-pair'
    - '--backgroundServiceAccountName=system:serviceaccount:kyverno:kyverno-background-controller'
    - '--reportsServiceAccountName=system:serviceaccount:kyverno:kyverno-reports-controller'
    - '--servicePort=9443'
    - '--webhookServerPort=9443'
    - '--resyncPeriod=15m'
    - '--disableMetrics=false'
    - '--otelConfig=prometheus'
    - '--metricsPort=8000'
    - '--admissionReports=true'
    - '--maxAdmissionReports=1000'
    - '--autoUpdateWebhooks=true'
    - '--enableConfigMapCaching=true'
    - '--enableDeferredLoading=true'
    - '--dumpPayload=false'
    - '--forceFailurePolicyIgnore=false'
    - '--generateValidatingAdmissionPolicy=false'
    - '--dumpPatches=false'
    - '--maxAPICallResponseLength=2000000'
    - '--loggingFormat=text'
    - '--v=2'
    - '--omitEvents=PolicyApplied,PolicySkipped'
    - '--enablePolicyException=false'
    - '--protectManagedResources=false'
    - '--allowInsecureRegistry=false'
    - '--registryCredentialHelpers=default,google,amazon,azure,github'
    - '--enableReporting=validate,mutate,mutateExisting,imageVerify,generate'
  envs:
    - name: INIT_CONFIG
      value: kyverno-admission-controller
    - name: METRICS_CONFIG
      value: kyverno-admission-controller
    - name: KYVERNO_SERVICEACCOUNT_NAME
      value: kyverno-admission-controller
    - name: KYVERNO_ROLE_NAME
      value: kyverno:kyverno-admission-controller
    - name: KYVERNO_SVC
      value: kyverno-admission-controller
    - name: TUF_ROOT
      value: /.sigstore
    - name: KYVERNO_DEPLOYMENT
      value: kyverno-admission-controller
  envsFromField:
    - name: KYVERNO_NAMESPACE
      fieldPath: metadata.namespace
    - name: KYVERNO_POD_NAME
      fieldPath: metadata.name
  resources:
    preset: "micro"
  storage:
    - mountPath: /.sigstore
      name: sigstore
      ramDisk: false
      readOnly: false
      sizeLimit: 5Gi
      type: emptyDir
  initContainers:
    - args:
        - '--loggingFormat=text'
        - '--v=2'
      env:
        - name: KYVERNO_SERVICEACCOUNT_NAME
          value: kyverno-admission-controller
        - name: KYVERNO_ROLE_NAME
          value: kyverno-admission-controller
        - name: INIT_CONFIG
          value: kyverno-admission-controller
        - name: METRICS_CONFIG
          value: kyverno-admission-controller
        - name: KYVERNO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KYVERNO_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KYVERNO_DEPLOYMENT
          value: kyverno-admission-controller
        - name: KYVERNO_SVC
          value: kyverno-admission-controller
      image: reg.kyverno.io/kyverno/kyvernopre:v1.13.3
      imagePullPolicy: IfNotPresent
      name: kyverno-pre
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

service:
  ports:
    - name: https
      protocol: TCP
      port: 9443
    - name: http-metrics
      protocol: TCP
      port: 8000

configMap:
  enabled: true
  data:
    defaultRegistry: "docker.io"
    enableDefaultRegistryMutation: "true"
    excludeGroups: system:nodes
    generateSuccessEvents: "false"
    resourceFilters: >-
      [*/*,kyverno,*] [Event,*,*] [*/*,kube-system,*] [*/*,kube-public,*]
      [*/*,kube-node-lease,*] [Node,*,*] [Node/*,*,*] [APIService,*,*]
      [APIService/*,*,*] [TokenReview,*,*] [SubjectAccessReview,*,*]
      [SelfSubjectAccessReview,*,*] [Binding,*,*] [Pod/binding,*,*]
      [ReplicaSet,*,*] [ReplicaSet/*,*,*] [EphemeralReport,*,*]
      [ClusterEphemeralReport,*,*] [ClusterRole,*,kyverno:admission-controller]
      [ClusterRole,*,kyverno:kyverno-admission-controller]
      [ClusterRole,*,kyverno:kyverno-background-controller]
      [ClusterRole,*,kyverno:kyverno-cleanup-controller]
      [ClusterRole,*,kyverno:kyverno-reports-controller]
      [ClusterRoleBinding,*,kyverno:kyverno-admission-controller]
      [ClusterRoleBinding,*,kyverno:kyverno-background-controller]
      [ClusterRoleBinding,*,kyverno:kyverno-cleanup-controller]
      [ClusterRoleBinding,*,kyverno:kyverno-reports-controller]
      [ClusterRoleBinding,*,kyverno:kyverno:admission-controller:view]
      [ClusterRoleBinding,*,kyverno:kyverno:background-controller:view]
      [ClusterRoleBinding,*,kyverno:kyverno:cleanup-controller:view]
      [ClusterRoleBinding,*,kyverno:kyverno:reports-controller:view]
      [ServiceAccount,kyverno,kyverno-admission-controller]
      [ServiceAccount/*,kyverno,kyverno-admission-controller]
      [ServiceAccount,kyverno,kyverno-background-controller]
      [ServiceAccount/*,kyverno,kyverno-background-controller]
      [ServiceAccount,kyverno,kyverno-cleanup-controller]
      [ServiceAccount/*,kyverno,kyverno-cleanup-controller]
      [ServiceAccount,kyverno,kyverno-reports-controller]
      [ServiceAccount/*,kyverno,kyverno-reports-controller]
      [Role,kyverno,kyverno:kyverno-admission-controller]
      [Role,kyverno,kyverno:kyverno-background-controller]
      [Role,kyverno,kyverno:kyverno-cleanup-controller]
      [Role,kyverno,kyverno:kyverno-reports-controller]
      [RoleBinding,kyverno,kyverno:kyverno-admission-controller]
      [RoleBinding,kyverno,kyverno:kyverno-background-controller]
      [RoleBinding,kyverno,kyverno:kyverno-cleanup-controller]
      [RoleBinding,kyverno,kyverno:kyverno-reports-controller]
      [ConfigMap,kyverno,kyverno] [ConfigMap,kyverno,kyverno-metrics]
      [Deployment,kyverno,kyverno-admission-controller]
      [Deployment/*,kyverno,kyverno-admission-controller]
      [Deployment,kyverno,kyverno-background-controller]
      [Deployment/*,kyverno,kyverno-background-controller]
      [Deployment,kyverno,kyverno-cleanup-controller]
      [Deployment/*,kyverno,kyverno-cleanup-controller]
      [Deployment,kyverno,kyverno-reports-controller]
      [Deployment/*,kyverno,kyverno-reports-controller]
      [Pod,kyverno,kyverno-admission-controller-*]
      [Pod/*,kyverno,kyverno-admission-controller-*]
      [Pod,kyverno,kyverno-background-controller-*]
      [Pod/*,kyverno,kyverno-background-controller-*]
      [Pod,kyverno,kyverno-cleanup-controller-*]
      [Pod/*,kyverno,kyverno-cleanup-controller-*]
      [Pod,kyverno,kyverno-reports-controller-*]
      [Pod/*,kyverno,kyverno-reports-controller-*]
      [Job,kyverno,kyverno-hook-pre-delete]
      [Job/*,kyverno,kyverno-hook-pre-delete]
      [NetworkPolicy,kyverno,kyverno-admission-controller]
      [NetworkPolicy/*,kyverno,kyverno-admission-controller]
      [NetworkPolicy,kyverno,kyverno-background-controller]
      [NetworkPolicy/*,kyverno,kyverno-background-controller]
      [NetworkPolicy,kyverno,kyverno-cleanup-controller]
      [NetworkPolicy/*,kyverno,kyverno-cleanup-controller]
      [NetworkPolicy,kyverno,kyverno-reports-controller]
      [NetworkPolicy/*,kyverno,kyverno-reports-controller]
      [PodDisruptionBudget,kyverno,kyverno-admission-controller]
      [PodDisruptionBudget/*,kyverno,kyverno-admission-controller]
      [PodDisruptionBudget,kyverno,kyverno-background-controller]
      [PodDisruptionBudget/*,kyverno,kyverno-background-controller]
      [PodDisruptionBudget,kyverno,kyverno-cleanup-controller]
      [PodDisruptionBudget/*,kyverno,kyverno-cleanup-controller]
      [PodDisruptionBudget,kyverno,kyverno-reports-controller]
      [PodDisruptionBudget/*,kyverno,kyverno-reports-controller]
      [Service,kyverno,kyverno-svc] [Service/*,kyverno,kyverno-svc]
      [Service,kyverno,kyverno-svc-metrics]
      [Service/*,kyverno,kyverno-svc-metrics]
      [Service,kyverno,kyverno-background-controller-metrics]
      [Service/*,kyverno,kyverno-background-controller-metrics]
      [Service,kyverno,kyverno-cleanup-controller]
      [Service/*,kyverno,kyverno-cleanup-controller]
      [Service,kyverno,kyverno-cleanup-controller-metrics]
      [Service/*,kyverno,kyverno-cleanup-controller-metrics]
      [Service,kyverno,kyverno-reports-controller-metrics]
      [Service/*,kyverno,kyverno-reports-controller-metrics]
      [ServiceMonitor,kyverno,kyverno-admission-controller]
      [ServiceMonitor,kyverno,kyverno-background-controller]
      [ServiceMonitor,kyverno,kyverno-cleanup-controller]
      [ServiceMonitor,kyverno,kyverno-reports-controller]
      [Secret,kyverno,kyverno-svc.kyverno.svc.*]
      [Secret,kyverno,kyverno-cleanup-controller.kyverno.svc.*]
    updateRequestThreshold: "1000"
    webhookAnnotations: '{"admissions.enforcer/disabled":"true"}'
    webhooks: >-
      {"namespaceSelector":{"matchExpressions":[{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["kube-system"]},{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["kyverno"]}],"matchLabels":null}}
    bucketBoundaries: 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15, 20, 25, 30
    metricsExposure: >-
      {"kyverno_admission_requests_total":{"disabledLabelDimensions":["resource_namespace"]},"kyverno_admission_review_duration_seconds":{"disabledLabelDimensions":["resource_namespace"]},"kyverno_cleanup_controller_deletedobjects_total":{"disabledLabelDimensions":["resource_namespace","policy_namespace"]},"kyverno_policy_execution_duration_seconds":{"disabledLabelDimensions":["resource_namespace","resource_request_operation"]},"kyverno_policy_results_total":{"disabledLabelDimensions":["resource_namespace","policy_namespace"]},"kyverno_policy_rule_info_total":{"disabledLabelDimensions":["resource_namespace","policy_namespace"]}}
    namespaces: '{"exclude":[],"include":[]}'

rbac:
  enabled: true
  roles:
    role:
      rules:
        - apiGroups:
            - ''
          resources:
            - secrets
            - serviceaccounts
          verbs:
            - get
            - list
            - watch
            - patch
            - create
            - update
            - delete
        - apiGroups:
            - ''
          resourceNames:
            - kyverno-admission-controller
          resources:
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
            - delete
            - get
            - patch
            - update
        - apiGroups:
            - apps
          resources:
            - deployments
            - deployments/scale
          verbs:
            - get
            - list
            - watch
            - patch
            - update
    clusterRole:
      rules:
        - apiGroups:
            - apiextensions.k8s.io
          resources:
            - customresourcedefinitions
          verbs:
            - get
        - apiGroups:
            - admissionregistration.k8s.io
          resources:
            - mutatingwebhookconfigurations
            - validatingwebhookconfigurations
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
            - deletecollection
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - roles
            - clusterroles
            - rolebindings
            - clusterrolebindings
          verbs:
            - list
            - watch
        - apiGroups:
            - kyverno.io
          resources:
            - policies
            - policies/status
            - clusterpolicies
            - clusterpolicies/status
            - updaterequests
            - updaterequests/status
            - globalcontextentries
            - globalcontextentries/status
            - policyexceptions
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
            - deletecollection
        - apiGroups:
            - reports.kyverno.io
          resources:
            - ephemeralreports
            - clusterephemeralreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
            - deletecollection
        - apiGroups:
            - wgpolicyk8s.io
          resources:
            - policyreports
            - policyreports/status
            - clusterpolicyreports
            - clusterpolicyreports/status
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
            - deletecollection
        - apiGroups:
            - ''
            - events.k8s.io
          resources:
            - events
          verbs:
            - create
            - update
            - patch
        - apiGroups:
            - authorization.k8s.io
          resources:
            - subjectaccessreviews
          verbs:
            - create
        - apiGroups:
            - ''
          resources:
            - configmaps
            - namespaces
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
            - update
            - patch
            - get
            - list
            - watch

extraObjects:
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: kyverno-admission-controller:view
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view
    subjects:
      - kind: ServiceAccount
        name: kyverno-admission-controller
        namespace: kyverno
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        rbac.authorization.k8s.io/aggregate-to-view: 'true'
      name: kyverno:rbac:view:updaterequests
    rules:
      - apiGroups:
          - kyverno.io
        resources:
          - updaterequests
        verbs:
          - get
          - list
          - watch
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        rbac.authorization.k8s.io/aggregate-to-view: 'true'
      name: kyverno:rbac:view:reports
    rules:
      - apiGroups:
          - reports.kyverno.io
        resources:
          - ephemeralreports
          - clusterephemeralreports
        verbs:
          - get
          - list
          - watch
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        rbac.authorization.k8s.io/aggregate-to-view: 'true'
      name: kyverno:rbac:view:policyreports
    rules:
      - apiGroups:
          - wgpolicyk8s.io
        resources:
          - policyreports
          - clusterpolicyreports
        verbs:
          - get
          - list
          - watch
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        rbac.authorization.k8s.io/aggregate-to-view: 'true'
      name: kyverno:rbac:view:policies
    rules:
      - apiGroups:
          - kyverno.io
        resources:
          - cleanuppolicies
          - clustercleanuppolicies
          - policies
          - clusterpolicies
        verbs:
          - get
          - list
          - watch
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        rbac.authorization.k8s.io/aggregate-to-admin: 'true'
      name: kyverno:rbac:admin:updaterequests
    rules:
      - apiGroups:
          - kyverno.io
        resources:
          - updaterequests
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        rbac.authorization.k8s.io/aggregate-to-admin: 'true'
      name: kyverno:rbac:admin:reports
    rules:
      - apiGroups:
          - reports.kyverno.io
        resources:
          - ephemeralreports
          - clusterephemeralreports
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        rbac.authorization.k8s.io/aggregate-to-admin: 'true'
      name: kyverno:rbac:admin:policyreports
    rules:
      - apiGroups:
          - wgpolicyk8s.io
        resources:
          - policyreports
          - clusterpolicyreports
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        rbac.authorization.k8s.io/aggregate-to-admin: 'true'
      name: kyverno:rbac:admin:policies
    rules:
      - apiGroups:
          - kyverno.io
        resources:
          - cleanuppolicies
          - clustercleanuppolicies
          - policies
          - clusterpolicies
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch

grafana:
  dashboard:
    enabled: true
    dashboards:
      - name: kyverno
        title: "Kyverno"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/kyverno-admission-controller/dashboards/kyverno-admission-controller.json"
        folder: "System"
