workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

extraObjects:
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: adguard-config
    spec:
      capacity:
        storage: 1Ti
      accessModes:
        - ReadWriteMany
      nfs:
        server: 10.0.0.10
        path: "/mnt/data-pool/adguard"
      mountOptions:
        - nfsvers=4.1 
        - hard      
        - noatime
        - rsize=1048576 
        - wsize=1048576 
        - proto=tcp
        - async
        - nconnect=8
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: adguard-config
      namespace: adguard
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: ""
      resources:
        requests:
          storage: 1Ti
      volumeName: adguard-config
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        app.kubernetes.io/name: adguard
      labels:
        app.kubernetes.io/instance: adguard
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: adguard
        app.kubernetes.io/version: v0.107.62
        helm.sh/chart: adguard-v0.107.62
      name: adguard
      namespace: adguard
    spec:
      progressDeadlineSeconds: 600
      replicas: 3
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app.kubernetes.io/instance: adguard
          app.kubernetes.io/name: adguard
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
        type: RollingUpdate
      template:
        metadata:
          annotations:
            app.kubernetes.io/name: adguard
            override-url.version-checker.io/adguard: docker.io/adguard/adguardhome
          creationTimestamp: null
          labels:
            app.kubernetes.io/instance: adguard
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: adguard
            app.kubernetes.io/version: v0.107.62
            helm.sh/chart: adguard-v0.107.62
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - adguard
                  topologyKey: kubernetes.io/hostname
          containers:
            - env:
                - name: NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: OPERATOR_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: HOST_IP_ADDRESS
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.hostIP
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
              image: docker.io/adguard/adguardhome:v0.107.62
              ports:
                - name: http
                  containerPort: 30004
                  hostPort: 30004
                  protocol: TCP
                - name: dns-udp
                  containerPort: 53
                  hostPort: 53
                  protocol: UDP
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 30004
                timeoutSeconds: 5
              name: adguard
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 30004
                timeoutSeconds: 5
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                privileged: false
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsNonRoot: false
                runAsUser: 0
                seccompProfile:
                  type: RuntimeDefault
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /opt/adguardhome/conf
                  name: config
                - mountPath: /opt/adguardhome/work
                  name: data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 0
            fsGroupChangePolicy: Always
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          terminationGracePeriodSeconds: 30
          topologySpreadConstraints:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: adguard
              maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: adguard-config
            - emptyDir: {}
              name: data
