namespace: "kyverno"

workload:
  image:
    registry: "reg.kyverno.io"
    repository: "kyverno/cleanup-controller"
    tag: "v1.13.3"
  args:
    - '--caSecretName=kyverno-cleanup-controller.kyverno.svc.kyverno-tls-ca'
    - '--tlsSecretName=kyverno-cleanup-controller.kyverno.svc.kyverno-tls-pair'
    - '--servicePort=9443'
    - '--cleanupServerPort=9443'
    - '--webhookServerPort=9443'
    - '--resyncPeriod=15m'
    - '--disableMetrics=false'
    - '--otelConfig=prometheus'
    - '--metricsPort=8000'
    - '--enableDeferredLoading=true'
    - '--dumpPayload=false'
    - '--maxAPICallResponseLength=2000000'
    - '--loggingFormat=text'
    - '--v=2'
    - '--protectManagedResources=false'
    - '--ttlReconciliationInterval=1m'
  env:
    - name: KYVERNO_DEPLOYMENT
      value: kyverno-cleanup-controller
    - name: INIT_CONFIG
      value: kyverno-admission-controller
    - name: METRICS_CONFIG
      value: kyverno-admission-controller
    - name: KYVERNO_SERVICEACCOUNT_NAME
      value: kyverno-cleanup-controller
    - name: KYVERNO_ROLE_NAME
      value: kyverno:cleanup-controller
    - name: KYVERNO_SVC
      value: kyverno-cleanup-controller
  envsFromField:
    - name: KYVERNO_NAMESPACE
      fieldPath: metadata.namespace
    - name: KYVERNO_POD_NAME
      fieldPath: metadata.name
  resources:
    preset: "micro"

service:
  ports:
    - name: https
      protocol: TCP
      port: 9443
    - name: http-metrics
      protocol: TCP
      port: 8000
