namespace: "kyverno"

workload:
  annotations:
    override-url.version-checker.io/kyverno-cleanup-controller: reg.kyverno.io/kyverno/cleanup-controller
  image:
    registry: "reg.kyverno.io"
    repository: "kyverno/cleanup-controller"
    tag: "v1.13.3"
  args:
    - '--caSecretName=kyverno-cleanup-controller.kyverno.svc.kyverno-tls-ca'
    - '--tlsSecretName=kyverno-cleanup-controller.kyverno.svc.kyverno-tls-pair'
    - '--servicePort=9443'
    - '--cleanupServerPort=9443'
    - '--webhookServerPort=9443'
    - '--resyncPeriod=15m'
    - '--disableMetrics=false'
    - '--otelConfig=prometheus'
    - '--metricsPort=8000'
    - '--enableDeferredLoading=true'
    - '--dumpPayload=false'
    - '--maxAPICallResponseLength=2000000'
    - '--loggingFormat=text'
    - '--v=2'
    - '--protectManagedResources=false'
    - '--ttlReconciliationInterval=1m'
  envs:
    - name: KYVERNO_DEPLOYMENT
      value: kyverno-cleanup-controller
    - name: INIT_CONFIG
      value: kyverno-admission-controller
    - name: METRICS_CONFIG
      value: kyverno-admission-controller
    - name: KYVERNO_SERVICEACCOUNT_NAME
      value: kyverno-cleanup-controller
    - name: KYVERNO_ROLE_NAME
      value: kyverno-cleanup-controller
    - name: KYVERNO_SVC
      value: kyverno-cleanup-controller
  envsFromField:
    - name: KYVERNO_NAMESPACE
      fieldPath: metadata.namespace
    - name: KYVERNO_POD_NAME
      fieldPath: metadata.name
  resources:
    preset: "micro"

service:
  ports:
    - name: https
      protocol: TCP
      port: 9443
    - name: http-metrics
      protocol: TCP
      port: 8000

rbac:
  enabled: true
  roles:
    role:
      rules:
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - create
        - apiGroups:
            - ''
          resourceNames:
            - kyverno-cleanup-controller.kyverno.svc.kyverno-tls-ca
            - kyverno-cleanup-controller.kyverno.svc.kyverno-tls-pair
          resources:
            - secrets
          verbs:
            - delete
            - get
            - list
            - update
            - watch
        - apiGroups:
            - ''
          resourceNames:
            - kyverno-admission-controller
          resources:
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
        - apiGroups:
            - coordination.k8s.io
          resourceNames:
            - kyverno-cleanup-controller
          resources:
            - leases
          verbs:
            - delete
            - get
            - patch
            - update
        - apiGroups:
            - apps
          resources:
            - deployments
          verbs:
            - get
            - list
            - watch
    clusterRole:
      rules:
        - apiGroups:
            - apiextensions.k8s.io
          resources:
            - customresourcedefinitions
          verbs:
            - get
        - apiGroups:
            - admissionregistration.k8s.io
          resources:
            - validatingwebhookconfigurations
          verbs:
            - create
            - delete
            - get
            - list
            - update
            - watch
        - apiGroups:
            - ''
          resources:
            - namespaces
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - kyverno.io
          resources:
            - clustercleanuppolicies
            - cleanuppolicies
          verbs:
            - list
            - watch
        - apiGroups:
            - kyverno.io
          resources:
            - globalcontextentries
            - globalcontextentries/status
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
            - deletecollection
        - apiGroups:
            - kyverno.io
          resources:
            - clustercleanuppolicies/status
            - cleanuppolicies/status
          verbs:
            - update
        - apiGroups:
            - ''
          resources:
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
            - events.k8s.io
          resources:
            - events
          verbs:
            - create
            - patch
            - update
        - apiGroups:
            - authorization.k8s.io
          resources:
            - subjectaccessreviews
          verbs:
            - create
