{
 "title": "Trivy - Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Container Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CRITICAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vuln_id, image_digest) (\n    trivy_vulnerability_id{cluster=~\"$cluster\", severity=\"Critical\", namespace=~\"$namespace\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIGH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vuln_id, image_digest) (\n    trivy_vulnerability_id{cluster=~\"$cluster\", severity=\"High\", namespace=~\"$namespace\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEDIUM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vuln_id, image_digest) (\n    trivy_vulnerability_id{cluster=~\"$cluster\", severity=\"Medium\", namespace=~\"$namespace\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vuln_id, image_digest) (\n    trivy_vulnerability_id{cluster=~\"$cluster\", severity=\"Low\", namespace=~\"$namespace\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vuln_id, image_digest) (\n    trivy_vulnerability_id{cluster=~\"$cluster\", severity=\"Unknown\", namespace=~\"$namespace\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vuln_id, image_digest) (\n    trivy_vulnerability_id{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(\n  count by (vuln_id, image_repository, image_tag) (\n    trivy_vulnerability_id{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  )\n) by (image_digest, image_registry, image_repository, image_tag)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "count(\n  count by (vuln_id, image_repository, image_tag) (\n    trivy_vulnerability_id{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n  )\n) by (image_digest, image_registry, image_repository, image_tag)\n",
     "legendFormat": "{{image_repository}} - {{image_tag}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(trivy_vulnerability_id{vuln_id=~\"CVE.*\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (namespace, image_repository, image_tag, vuln_id, severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Config Audit Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CRITICAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Critical\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIGH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"High\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEDIUM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Medium\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Low\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RBAC Assessments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CRITICAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"Critical\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIGH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"High\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEDIUM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"Medium\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"Low\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(trivy_role_rbacassessments{namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Detailed Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(trivy_rbacassessments_info{namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (namespace, severity, rbac_assessment_category, rbac_assessment_description, rbac_assessment_id, resource_kind, resource_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Exposed Secrets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Total Exposed Secrets by Namespaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(trivy_image_exposedsecrets{cluster=~\"$cluster\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Detailed Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(trivy_exposedsecrets_info{namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (namespace, image_repository, image_tag, vuln_id, severity, secret_category, secret_rule_id, secret_target, secret_title)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}