namespace: "thanos"

workload:
  image:
    registry: quay.io
    repository: thanos/thanos
    tag: v0.38.0
    digest: "sha256:365873d05a2f59dbaf3d40f526d3b8a2e66b9882dd6cab9396d16e8410aa46e6"
  args:
    - 'query'
    - '--grpc-address=0.0.0.0:10901'
    - '--http-address=0.0.0.0:10902'
    - '--log.level=info'
    - '--log.format=logfmt'
    - '--query.replica-label=replica'
    - '--endpoint=dns+prometheus-0.prometheus.thanos.svc.cluster.local:10901'
    - '--endpoint=dns+prometheus-1.prometheus.thanos.svc.cluster.local:10901'
    - '--endpoint=dns+thanos-store-0.thanos-store.thanos.svc.cluster.local:10901'
    - '--endpoint=dns+thanos-store-1.thanos-store.thanos.svc.cluster.local:10901'
    - '--query.auto-downsampling'
  probes:
    readinessProbe:
      path: "/-/ready"
      port: 10902
    livenessProbe:
      path: "/-/healthy"
      port: 10902

service:
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
    - name: http
      port: 10902
      protocol: TCP
