namespace: "thanos"

workload:
  image:
    registry: quay.io
    repository: thanos/thanos
    tag: v0.31.0
  replicaCount: 1
  args:
    - 'query'
    - '--grpc-address=0.0.0.0:10901'
    - '--http-address=0.0.0.0:9090'
    - '--log.level=info'
    - '--log.format=logfmt'
    - '--endpoint=dnssrv+_grpc._tcp.prometheus.prometheus.svc.cluster.local:10901'
    - '--query.auto-downsampling'
  resources:
    preset: micro
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: false

autoscaling:
  enabled: false

service:
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
    - name: http
      port: 9090
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: thanos.openjamlab.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: true
        secretName: "letsencrypt-wildcard-certificate"
      backend:
        service:
          name: "thanos-query"
          port: 9090
