namespace: "authentik"

workload:
  image:
    registry: ghcr.io
    repository: goauthentik/server
    tag: 2025.6.3
  args:
    - server
  probes:
    readinessProbe:
      type: tcpSocket
      port: 9000
    livenessProbe:
      type: tcpSocket
      port: 9000
  storage:
    - name: media
      type: pvc
      mountPath: /media
      claimName: "authentik-media"
  envsSecret:
    - name: AUTHENTIK_POSTGRESQL__HOST
      secret: authentik-postgres-app
      key: host
    - name: AUTHENTIK_POSTGRESQL__USER
      secret: authentik-postgres-app
      key: username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      secret: authentik-postgres-app
      key: password
    - name: AUTHENTIK_POSTGRESQL__NAME
      secret: authentik-postgres-app
      key: dbname
    - name: AUTHENTIK_SECRET_KEY
      secret: authentik
      key: AUTHENTIK_SECRET_KEY
  envs:
    - name: "AUTHENTIK_REDIS__HOST"
      value: "authentik-redis.authentik.svc.cluster.local"
  resources:
    preset: ""
    custom:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "10000m"
        memory: "5Gi"

service:
  ports:
    - name: http
      port: 9000
      protocol: TCP
    - name: https
      port: 9443
      protocol: TCP
    - name: http-metrics
      port: 9300
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: auth.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "authentik-server"
          port: 9000

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: authentik
      namespace: authentik
    spec:
      encryptedData:
        AUTHENTIK_SECRET_KEY: AgA5FyRcJeyhhpbwRn4ta73LlkM87cKjs50jhbXDZlqezRZlPan8rNZDWHIE9GtBZWyNXvFSW7piYXDwpcqCuN2jQg/qU7ZEbpc3OwcvjikUr1gvQrJRFriSqMBPlEk9+4eFuYcELlR1IGhbzoDyQrNNCJ6r2E4lMaIb9JY/dmExOcFIO0dUdGgkBJKDMU1RRyQZIMvtxLwmSokjX9+sZG1PHiMTYPWODdrie8I9WvX3VKFx5vVidQkcfT3MOLDNtjIu4CzZq29vKNGDxFvBWCBN1Nz/JWSw2+zlMaCNwKpN4Ow+U4vDlEUiws4ihLUGjDqLVs/Y/KXz7eZHca2R8ZW8/0hX4gHD2UNUt/P2DTTMFGgCHfTh/wi1vCvk/L64a096PaQ0COSzjMdnyVjHlw0/64Cv2jstnadGOkigVEFFHuvXhViyLv4tlrQriQYu13RkxETSapIfRqcPO9o/1ms44LTj5ay2ha7vXL8tGV7d3oiPX8IHOO9knqpBeDGO8c8jAJniUwLaiZTPf+UlaEh684DCLqbFQi9wTWhJn9wDHYvpXZflyylsVdJexd6eCS4UqcR1ZhSvCxlJ9ep4Vu+uIfyWWZ2owF3fSRwiTv2hXJBXxxa76hTRvtjOu5gW7PmeG/LPlp3xEDE1GmIw4x1+BmW7V1LwZgRK4cp8hTnJ11clKJBSFPpzJS0ES+9pAF0NaGGCO+6fLKlBXyGaN6XJBgxYeiqsgU2gFNAFyFnVH8TaYqkd6WuyqDu/XktM0IYPztk08pxIXsTjCzQ5NTSV9g54D2tQaMC2WzzN5uOb/V0=
        AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: AgAllUnro5LWdDu3GjgYwJ3hLvry3terZx2qWddXMrHeMGLgWmNBd8VnWVGLcCfvheJ6dpF6xgcAssO/4mD5uZo4ygd1On///GYBJTCuFo03y9HvG1cayClb56puJvKKodZ7o9Sb1u1GsvAzYTrg8CN98WFFZCG8jOfCkp29m7Vl0Yl46P44BTSsoo2Mx2QbukEAmU+JDQ3XpCuqCLFrk2ou/wz17YtXI1pG41tL850W8m4cuOr/fPVd4e7nKNMIc5/Tyz7KqhhwM2CgwrqYSr7bjywrx2X0In742Y3yFbhgdmJVVnrzENeXp6aMe6WpP4BgEC73+9tT0HmQGgMcO5Ap5JHHrKEsycBLs8+e1NoxzcYk/48GuIcaKlk4Vkz20qvtXeF9dDyNveKYTd/eaiw/mayjLPn5FXa56Hf/e7oINoJhgG2VOT3MQ71W0wSRRt6NmcbfmU0oy6gh4mkciK9S6PCJcpjK+EaevzBSXb6seTpaMfNQtneTzchv3FFoV2XVD8xof3MAl9syjU24HuyEAVjm2PWcfSYRxEkiG5Z5BjMKMFoe+KN6P/DoBGJJxADyjnKbZ9NrIuBeIMUdfeaRUah2YzYsbO0U7F9q5dfAmBEFT4vFu4K7Jipil3ytb0Z9mQ6TGMKv1/sSIQjoZrH8aAhFy1Zl6NTUYOiuUI2oTwB0OzHWimoJD0bRsATm69AjmpfcptRT+jUcsL1i3tzhD1YS0w==
        AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: AgAkhXfmXQp5ndY/ivQou8U+u1Yvyqy/VSyjZ+xtpB0eNzgIUmVqPBaGL2pvli+7vlJBnl6QyMYxIna3pdpd/fCpRMkXX49Ud/qJZjDUsfocy6H2E/WrPRhJqsQkin2IoKqUGTPPAsdmvS9PSfYrrvymwv15wb+SXwlaQfX5UPc3BnzOWNGdZ58B3w+kIe3hLMUFe/MyRFqxZ9coMwR6y0fiX6hvUETuSOsmO6I5GSQq8D63VHbPrpHpJHAWg1gXXr5zKBMgt3mqgxitkmQhd10tlk+QAHzRP/9SSHZgMaoAz3bGAUGTyV+klOWjNnQVYREG5t4nGaX+SzSbB54KQxB7eOKIUr4dF+oFX7ZeTGEYUsNal20yySOLvYCg2YJetynMQG7UshIA+hDKT803UjlGivWOSDVFlpborYaWcO7WxgHLbK81AqcItsqo24FC+byumaDElByHELc3qPScy9QI7bV3KMfsWaTg5fSBJEdHPm7JvV37O5tn4+WgN+LqeDBHbEERlej5zSZpo4JlB0q7gPvTi5hnBNxHKCM2hQkQaPk39mzGe04QEK/ik0yYaxDySeUnSd8T14upnqvDrOYvaNgf5fumDYRfDiA/bp8JcsZbXjgSw+M9sHOZjt9avPSs+Q1Pn2ctDpXNNNJ6O2lBb/NI6VNajflpFaQeRGSZ8JYIOlU8kKcAEoUh2KWEQTrwheIE9tqyOzaJbf4jiPm+2wMGqJatuDKDnwZLgSBkJ2sxk6yvYB+y
      template:
        metadata:
          name: authentik
          namespace: authentik
        type: Opaque
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: authentik-media
    spec:
      capacity:
        storage: 1Ti
      accessModes:
        - ReadWriteMany
      nfs:
        server: 10.0.0.10
        path: "/mnt/data-pool/authentik-media"
      mountOptions:
        - nfsvers=4.1 
        - hard      
        - noatime
        - rsize=1048576 
        - wsize=1048576 
        - proto=tcp
        - async
        - nconnect=8
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: authentik-media
      namespace: authentik
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: ""
      resources:
        requests:
          storage: 1Ti
      volumeName: authentik-media
