namespace: "authentik"

workload:
  image:
    registry: ghcr.io
    repository: goauthentik/server
    tag: 2025.6.3
  args:
    - server
  probes:
    readinessProbe:
      type: tcpSocket
      port: 9000
    livenessProbe:
      type: tcpSocket
      port: 9000
  envsSecret:
    - name: AUTHENTIK_POSTGRESQL__HOST
      secret: authentik-postgres-app
      key: host
    - name: AUTHENTIK_POSTGRESQL__USER
      secret: authentik-postgres-app
      key: username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      secret: authentik-postgres-app
      key: password
    - name: AUTHENTIK_POSTGRESQL__NAME
      secret: authentik-postgres-app
      key: dbname
    - name: AUTHENTIK_SECRET_KEY
      secret: authentik
      key: AUTHENTIK_SECRET_KEY
    - name: AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY
      secret: authentik
      key: AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY
    - name: AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY
      secret: authentik
      key: AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY
  envs:
    - name: "AUTHENTIK_REDIS__HOST"
      value: "authentik-redis.authentik.svc.cluster.local"
    - name: "AUTHENTIK_STORAGE__MEDIA__BACKEND"
      value: "s3"
    - name: "AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME"
      value: "authentik-media"
    - name: "AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT"
      value: "http://authentik-media.minio.svc.cluster.local"
    - name: "AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN"
      value: "minio.projectwhitebox.com/authentik-media"
    - name: "AUTHENTIK_STORAGE__MEDIA__S3__REGION"
      value: "us-east-1"
  resources:
    preset: ""
    custom:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "10000m"
        memory: "5Gi"

service:
  ports:
    - name: http
      port: 9000
      protocol: TCP
    - name: https
      port: 9443
      protocol: TCP
    - name: http-metrics
      port: 9300
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: auth.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "authentik-server"
          port: 9000

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: authentik
      namespace: authentik
    spec:
      encryptedData:
        AUTHENTIK_SECRET_KEY: AgB5Kg3lm4iv0DATuKgvSkTnfGLPOYVJisNWU+eSdgf31ngvisln4tPk3WiH3H/k5MfIfKK3yMyuV6iUkI+4fnO7djQouG21fsIrRPkdJCo48bS8v821zY92lVIPaWqvGaUW7Q6Wj/MwWAsrJhtpulMOhzCZTzMqzLTfFfkHAVhFOyjEDtxmCfCpZmYKsREynYnqMMHdRN7dJPqjGjnbozBcFhhUR1+VHmBoW3eguhGWOqs3bmAFmenjnEDi4B2t1slRnbyXh+DwbrSwMcPxdcjyK1VEtyKJXQjav6zDuerMn2Tx97B/aQTb9BsOAaZ3M8w/dprjaN+krUOFP+qNUMvF7oeazJH44Mcc8RSUV2H5be63ZIYCggsq9cS4RrxSl0BskVpBml1HC+YlFgdYkynB6JByH5w/8ZLr5Gbl39XR79Yb8yeqP8oc0XtA7nBT24JOxrC1xlgwsuNm6SmRLT1iyuHvdKhQmvtj9CK3+3YCaPpXNbqnoeMIzBh40j7R7lyq2PnWk919javc3G5Bv2TEuvQFtIexuWXMwGWOCXhYxpPXM4oAczVn+R7wIi18zfSOkZB2A3doexwzsyjR2CHiNRqCx3cVWkGcZvSQ6jeY7CUKCe1wkS04CaXYBLKH5RhVayuQ0MgTf0yQRNZRiQOF9BjiSnm0Q1xM7iXA3pUoI3jOM+6/C7mXctobJb/IBs0NJey40tdZuPmNcF/7L5wd2yccxRRuk4frn4U3Bo9tCKQZgxBBncffmrNIVeIYCeiMpVfiiKSWHAvyBNhXHNyFDnnijEDzwvYvlnzHqe+Uu9Q=
        AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: AgA3ZVecX66M1jrHJ3qbOpCl0z+2T0EhPP+imQ9eXR/oMYHcGFGtSWqDpJ98VDrQzwbfwziNII72g3Mp07rLlyb3cbiMxslOVi8dVIdV2tA15UXj1U4qGa6HocdeuTdCmDkkQSLCTnzfMAVl8jONJlwZYPMwYjD6s57+qYWvEvxn1xrSHt7zaXkY+6lwH6gDfURB3QpCO6mdVp803OxEHZNQ306A9bQVRS+h2oG2fSORPxENi5ve44f0IyjLgeGMlG8UByRcCCvz9YULoSkP8F3hGs/n0DIkY70fn248s9tWTfiFDjWXucFaPtFJ7DfTOHnFd6pqX3eHqDv0Zqq837aoj5xZqk7WHx4HjKYYh1I231LzEEpiYj/5HEXu0w9QCsarda1LrpFlZfomDABph0mk6Se3w3upNeRV1WTtr0jVUvl+lqtLOqvMr2Ndleck6EXwndITfJLwiZL7cOLPMWM60rHwM86GHo0hXz6sqsZ8QpcNeRmo6Mtt3Ej0jc1pNvDvU9p+BeY/iZEpiSDEhBzMGgI/b7fMyP4iQE4StLD56c+oI2mhLIPIn/Ywfnw75itEokBs5ZVJUeJaTEFH7sikfSUQBsecyn+eUir9O1a4hzreDiQFGUZTgtPdUuOqdMGfZ5FAoMF3HMBTCRz7cEABE9Kxo8yPXxK7nPtFQGJ2b1wYkFcqw6BrkhjdUDWCTHzPRjk+0IHqTJO1kDraQ8OWIgBHdZg=
        AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: AgAaN3AmCa4vcSY6IhgVunT7s+FwT9TUjhX2J6VKM1aDjBmV4ZkHxbTl10gpANeAFpaEx77E39Hq5huXYa+DTaSy9JNrAxPymrXKj7DI//mmVM7pMZcnm5mEbh1Cm/0gWDipACGVQRIZoSMfJPUR7EkDvtNjqE/L3EMmfTz3Mxx3uPKAH+UQEExLiV4DrLrkqeINtum9DjN0up2p/rM+gttGG237AD7+Xjogg3lX4T3kNdmkCpaGNLErj8Rw8F7qMZeK/f531cYZbzyKlinXb25l8YG1ISO9ZPg+T781JtkikggYt2ECUEeFm0WDzbK1q/3e4fBe8u/2BZ/4Gve+/oMt2ZJnPZVMtHdaFt3tohdXW+x6HBiTH2ODQheqgO+y++BQl+TyujQKkKTDgV9kjxxFlOeuGgLTWW5BcoUn0TD2SphCyvBVqjQdS9D+VhpeLUMxNWZhPXE8TO8H13H43zTsZL0daPeVSUSLBqxM9KcWQZlb9+NDN4fmDDWEEZ1y1qAuD/tDxfLuDBSYgmCxgnOQo9tCuSK4VFU310AvYZT8uu3wd/Ejmrkdv6M+o1cnNKWHgo/QR5mplWUxOj0F8E7FjXD+pPo6tY3SSyRz2Zn54fr/z0ZHxg9sL/oACtHYJDbhB+FAPeyCDhHG0gWOZALHMsiSHkK7wdLQ+Alxr4h/85Q/6yvyho5qwoRP/z2iCgcwxx2SVzFLpll7LxIzrHlZY19gnZYnwwGcSxdLT4u7dO4cOkmAfvXBhA==
      template:
        metadata:
          name: authentik
          namespace: authentik
        type: Opaque
