namespace: "kube-image-keeper"

workload:
  image:
    registry: "docker.io"
    repository: registry
    tag: 3.0.0
  envs:
    - name: REGISTRY_STORAGE_DELETE_ENABLED
      value: "true"
    - name: REGISTRY_STORAGE
      value: s3
    - name: REGISTRY_STORAGE_S3_BUCKET
      value: kuik
    - name: REGISTRY_STORAGE_S3_REGION
      value: us-east-1
    - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
      value: http://minio.svc.cluster.local
    - name: REGISTRY_STORAGE_REDIRECT_DISABLE
      value: "true"
    - name: OTEL_TRACES_EXPORTER
      value: "none"
  envsSecret:
    - name: REGISTRY_STORAGE_S3_ACCESSKEY
      secret: kube-image-keeper
      key: S3_ACCESS_KEY
    - name: REGISTRY_STORAGE_S3_SECRETKEY
      secret: kube-image-keeper
      key: S3_SECRET_KEY
  probes:
    readinessProbe:
      path: "/v2"
      port: 5000
    livenessProbe:
      path: "/v2"
      port: 5000

service:
  ports:
    - name: http
      port: 5000
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
    role:
      rules:
        - apiGroups:
            - apps
            - extensions
          resourceNames:
            - kube-image-keeper-registry
          resources:
            - statefulsets
            - deployments
          verbs:
            - get
            - patch
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - pods
          verbs:
            - list
        - apiGroups:
            - ''
          resources:
            - pods/exec
          verbs:
            - create

extraObjects:
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: kube-image-keeper
      namespace: kube-image-keeper
    spec:
      encryptedData:
        S3_ACCESS_KEY: AgAdEJI1Gdab49VxyJtg7gstK9qErBaqSZP90ZLxXoiihOPeC7vGptZ70ZOCqVQRKRCAG0a+nY6opKwbxY6z6qnEIed6LETZzICzbq21ntVTmo4PhCQP47DfjN451fTNd7PIoszaL48S8rl6rwN5NcoixN3jT2Luw5buAHN+EosbGe8iaEPaT2Fj8f0OTEE9DAwCfbMiScTcciC3A8fpxTGeDgW039HLINe1SRpdk+qcX6MHvSJPqAsS15rbEHLhDHiYuHZbhXsfxmBgXf3ryqnZXm+vrEwa5mUlOQ0RfgSiKFUaZoXFxFJKdm9beupFGci4gUZd8foQjWYC79vR14nhzqswwbbji8NerfbQ1Du/arbiZlxjUXgN4NnpFhYIyYKeI3407JfrTwsqpYOHRqlEUkznX3hKq4/ht8gqDTWMjrFeFbmkydifT7YN3lQ2zSC5YuDqcIrv7WG3cWf0TtUR3NK9AUPZmtiSK4Y4oCcvxdw4T6Z3d2Gt2zvy15bbT9ar3OmWn51biUgTeJa9Kg/iFggoaua1A1dmTVeWhyKoSeNfi2FzpcJu/lVrv0X4HW2mawjSlPIVRPmCrPocuqrXzHukewb9TZiCQhfwzTzWmwr8RBfj3fQ1AFfokhCbkOL+eXQEoKQTHZAGWwmiYs71d050iR1fff58EYJQV8LRTWZ4i6Oa7JSag76Hx0SNrzDh8wOjGZ7nOHUZcpG6oCEY8JPtmxM=
        S3_SECRET_KEY: AgBTH6kfjWL71xDPKaQMMbvOCkuKnxJiXzJ7CyyO8WmLLWx9cxyTM/7kaGHfKJRyHarfutzkVzPUl5+ylVN55bSc5GTOb0QI35UsF1UBA7/+zv7Ll5DBYHSrB8fFMrMCWFIRMqxuUi7uhmVRaemEQYhf4OOTQ1n7Q0Ee7bEs2rpCPpDghSX7jPm80aw5V9Fc0N8QLWfbUCVEV8QTLvgbfAOSg+M7JEFPYGfda68GPWNisaZorCo+8y7CAgqImZa7BTFjHCMXvpqdnIKMOs3NNn1JKfM5NL15nOKsQPvyshs4sY4khz/Kv+7/2an+K9RjG8ftE1P+gpZR34VY+XuAZy8q7NRXehMn9xI5GAfN74TSQ9QPhmoFCVio6lK9+J8HKYwQmBSTcu4QmRHPtEs26dgr/A7aoIeHz6oXmJ/sxVNpftQiDHkR8WWKV5Oj+oWOVfHO4K53e0hrLg9wyuo03CLgVCUnTn2zIdEL1Sklyd2j9anyuG7tBFx3JoONtXhOitOcUIjRfJuCxzbvkX4f/2BvP/krjKBoUbks5q7HK/RhbxWlWp8ra+DRvUKb8mMr5h8e8V1w0/0eQFy7WPPfS3gNACUpHY9b+wI3Ft25r06Cd963w022LN+xXj16XXZcHqgVV4YZy1T/5E14A0MCXeeERbEMi9oqkI9E11WbpZQXL/d+lRUWZskQHvrjwBXMyABCVPR2T8QJfACDhDwv2nMiLTgTqQ5eV5Dk/vB6dObDcEIzHe152rKxkA==
      template:
        metadata:
          name: kube-image-keeper
          namespace: kube-image-keeper
        type: Opaque
