namespace: "kube-image-keeper"

workload:
  annotations:
    override-url.version-checker.io/kube-image-registry: ghcr.io/enix/kube-image-registry
  image:
    repository: registry
    tag: 2.8.1
  envs:
    - name: REGISTRY_STORAGE_DELETE_ENABLED
      value: true
  resources:
    preset: nano
  probes:
    readinessProbe:
      type: httpGet
      path: "/v2"
      port: 5000
      scheme: "HTTP"
    livenessProbe:
      type: httpGet
      path: "/v2"
      port: 5000
      scheme: "HTTP"
  storage:
    - name: data
      type: emptyDir
      mountPath: /var/lib/registry

service:
  ports:
    - name: http
      port: 5000
      protocol: TCP
    - name: http-metrics
      port: 5001
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
    role:
      rules:
        - apiGroups:
            - apps
            - extensions
          resourceNames:
            - kube-image-keeper-registry
          resources:
            - statefulsets
            - deployments
          verbs:
            - get
            - patch
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - pods
          verbs:
            - list
        - apiGroups:
            - ''
          resources:
            - pods/exec
          verbs:
            - create
