namespace: "kube-image-keeper"

workload:
  image:
    repository: registry
    tag: 2.8.3
  envs:
    - name: REGISTRY_STORAGE_DELETE_ENABLED
      value: true
  probes:
    readinessProbe:
      path: "/v2"
      port: 5000
    livenessProbe:
      path: "/v2"
      port: 5000
  storage:
    - name: data
      type: emptyDir
      mountPath: /var/lib/registry

service:
  ports:
    - name: http
      port: 5000
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
    role:
      rules:
        - apiGroups:
            - apps
            - extensions
          resourceNames:
            - kube-image-keeper-registry
          resources:
            - statefulsets
            - deployments
          verbs:
            - get
            - patch
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - pods
          verbs:
            - list
        - apiGroups:
            - ''
          resources:
            - pods/exec
          verbs:
            - create
