namespace: "kube-image-keeper"

workload:
  image:
    repository: registry
    tag: 3.0.0
  envs:
    - name: REGISTRY_STORAGE_DELETE_ENABLED
      value: "true"
    - name: REGISTRY_STORAGE
      value: s3
    - name: REGISTRY_STORAGE_S3_BUCKET
      value: kuik
    - name: REGISTRY_STORAGE_S3_REGION
      value: us-east-1
    - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
      value: http://minio-hl.minio.svc.cluster.local:9000
    - name: REGISTRY_STORAGE_REDIRECT_DISABLE
      value: "true"
  envsSecret:
    - name: REGISTRY_STORAGE_S3_ACCESSKEY
      secret: secret-name
      key: accessKey
    - name: REGISTRY_STORAGE_S3_SECRETKEY
      secret: secret-name
      key: secretKey
  probes:
    readinessProbe:
      path: "/v2"
      port: 5000
    livenessProbe:
      path: "/v2"
      port: 5000

service:
  ports:
    - name: http
      port: 5000
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
    role:
      rules:
        - apiGroups:
            - apps
            - extensions
          resourceNames:
            - kube-image-keeper-registry
          resources:
            - statefulsets
            - deployments
          verbs:
            - get
            - patch
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - pods
          verbs:
            - list
        - apiGroups:
            - ''
          resources:
            - pods/exec
          verbs:
            - create
