installCRDs: true

workload:
  image:
    registry: mirror.gcr.io
    repository: "aquasec/trivy-operator"
    tag: "0.26.1"
  probes:
    readinessProbe:
      port: 9090
    livenessProbe:
      path: "/healthz"
      port: 9090
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /tmp
  envs:
    - name: OPERATOR_TARGET_NAMESPACES
      value: ''
    - name: OPERATOR_EXCLUDE_NAMESPACES
      value: ''
    - name: OPERATOR_TARGET_WORKLOADS
      value: >-
        pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job
    - name: OPERATOR_SERVICE_ACCOUNT
      value: trivy-operator
    - name: "CONTROLLER_CACHE_SYNC_TIMEOUT"
      value: "5m"
    - name: "OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS"
      value: "true"
    - name: "OPERATOR_BATCH_DELETE_DELAY"
      value: "10s"
    - name: "OPERATOR_BATCH_DELETE_LIMIT"
      value: "10"
    - name: "OPERATOR_BUILT_IN_TRIVY_SERVER"
      value: "false"
    - name: "OPERATOR_CACHE_REPORT_TTL"
      value: "120h"
    - name: "OPERATOR_CLUSTER_COMPLIANCE_ENABLED"
      value: "true"
    - name: "OPERATOR_CLUSTER_SBOM_CACHE_ENABLED"
      value: "false"
    - name: "OPERATOR_CONCURRENT_NODE_COLLECTOR_LIMIT"
      value: "1"
    - name: "OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT"
      value: "10"
    - name: "OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS"
      value: "true"
    - name: "OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_HEALTH_PROBE_BIND_ADDRESS"
      value: ":9090"
    - name: "OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_LOG_DEV_MODE"
      value: "false"
    - name: "OPERATOR_MERGE_RBAC_FINDING_WITH_CONFIG_AUDIT"
      value: "false"
    - name: "OPERATOR_METRICS_BIND_ADDRESS"
      value: ":8080"
    - name: "OPERATOR_METRICS_CLUSTER_COMPLIANCE_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_CONFIG_AUDIT_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_EXPOSED_SECRET_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_FINDINGS_ENABLED"
      value: "true"
    - name: "OPERATOR_METRICS_IMAGE_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_INFRA_ASSESSMENT_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_RBAC_ASSESSMENT_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_VULN_ID_ENABLED"
      value: "false"
    - name: "OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES"
      value: "{}"
    - name: "OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_SBOM_GENERATION_ENABLED"
      value: "true"
    - name: "OPERATOR_SCANNER_REPORT_TTL"
      value: "24h"
    - name: "OPERATOR_SCAN_JOB_RETRY_AFTER"
      value: "30s"
    - name: "OPERATOR_SCAN_JOB_TIMEOUT"
      value: "5m"
    - name: "OPERATOR_SCAN_JOB_TTL"
      value: ""
    - name: "OPERATOR_SEND_DELETED_REPORTS"
      value: "false"
    - name: "OPERATOR_VULNERABILITY_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS"
      value: "true"
    - name: "OPERATOR_WEBHOOK_BROADCAST_CUSTOM_HEADERS"
      value: ""
    - name: "OPERATOR_WEBHOOK_BROADCAST_TIMEOUT"
      value: "30s"
    - name: "OPERATOR_WEBHOOK_BROADCAST_URL"
      value: ""
    - name: "TRIVY_SERVER_HEALTH_CHECK_CACHE_EXPIRATION"
      value: "10h"

service:
  ports:
    - name: healthcheck
      protocol: TCP
      port: 9090
    - name: http-metrics
      protocol: TCP
      port: 8080

configMap:
  enabled: true
  configMaps:
    - name: "trivy-operator"
      data:
        compliance.failEntriesLimit: '10'
        configAuditReports.scanner: Trivy
        node.collector.imageRef: ghcr.io/aquasecurity/node-collector:0.3.1
        node.collector.nodeSelector: 'true'
        nodeCollector.volumeMounts: >-
          [{"mountPath":"/var/lib/etcd","name":"var-lib-etcd","readOnly":true},{"mountPath":"/var/lib/kubelet","name":"var-lib-kubelet","readOnly":true},{"mountPath":"/var/lib/kube-scheduler","name":"var-lib-kube-scheduler","readOnly":true},{"mountPath":"/var/lib/kube-controller-manager","name":"var-lib-kube-controller-manager","readOnly":true},{"mountPath":"/etc/systemd","name":"etc-systemd","readOnly":true},{"mountPath":"/lib/systemd/","name":"lib-systemd","readOnly":true},{"mountPath":"/etc/kubernetes","name":"etc-kubernetes","readOnly":true},{"mountPath":"/etc/cni/net.d/","name":"etc-cni-netd","readOnly":true}]
        nodeCollector.volumes: >-
          [{"hostPath":{"path":"/var/lib/etcd"},"name":"var-lib-etcd"},{"hostPath":{"path":"/var/lib/kubelet"},"name":"var-lib-kubelet"},{"hostPath":{"path":"/var/lib/kube-scheduler"},"name":"var-lib-kube-scheduler"},{"hostPath":{"path":"/var/lib/kube-controller-manager"},"name":"var-lib-kube-controller-manager"},{"hostPath":{"path":"/etc/systemd"},"name":"etc-systemd"},{"hostPath":{"path":"/lib/systemd"},"name":"lib-systemd"},{"hostPath":{"path":"/etc/kubernetes"},"name":"etc-kubernetes"},{"hostPath":{"path":"/etc/cni/net.d/"},"name":"etc-cni-netd"}]
        policies.bundle.insecure: 'false'
        policies.bundle.oci.ref: mirror.gcr.io/aquasec/trivy-checks:1
        report.recordFailedChecksOnly: 'true'
        scanJob.compressLogs: 'true'
        scanJob.podTemplateContainerSecurityContext: >-
          {"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true}
        scanJob.useGCRServiceAccount: 'true'
        vulnerabilityReports.scanner: Trivy
    - name: "trivy-operator-trivy-config"
      data:
        trivy.additionalVulnerabilityReportFields: ''
        trivy.command: image
        trivy.dbRepository: mirror.gcr.io/aquasec/trivy-db
        trivy.dbRepositoryInsecure: 'false'
        trivy.filesystemScanCacheDir: /var/trivyoperator/trivy-db
        trivy.imagePullPolicy: IfNotPresent
        trivy.imageScanCacheDir: /tmp/trivy/.cache
        trivy.includeDevDeps: 'false'
        trivy.javaDbRepository: mirror.gcr.io/aquasec/trivy-java-db
        trivy.mode: Standalone
        trivy.repository: mirror.gcr.io/aquasec/trivy
        trivy.resources.limits.cpu: 500m
        trivy.resources.limits.memory: 500M
        trivy.resources.requests.cpu: 100m
        trivy.resources.requests.memory: 100M
        trivy.sbomSources: ''
        trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
        trivy.skipJavaDBUpdate: 'false'
        trivy.slow: 'true'
        trivy.supportedConfigAuditKinds: >-
          Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
        trivy.tag: 0.62.1
        trivy.timeout: 5m0s
        trivy.useBuiltinRegoPolicies: 'false'
        trivy.useEmbeddedRegoPolicies: 'true'

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - limitranges
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - nodes
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - pods
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - pods/log
          verbs:
            - get
            - list
        - apiGroups:
            - ''
          resources:
            - replicationcontrollers
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - resourcequotas
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - services
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apiextensions.k8s.io
          resources:
            - customresourcedefinitions
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
          resources:
            - daemonsets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
          resources:
            - deployments
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
          resources:
            - replicasets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
          resources:
            - statefulsets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps.openshift.io
          resources:
            - deploymentconfigs
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustercompliancedetailreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustercompliancereports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustercompliancereports/status
          verbs:
            - get
            - patch
            - update
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clusterconfigauditreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clusterinfraassessmentreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clusterrbacassessmentreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustersbomreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustervulnerabilityreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - configauditreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - exposedsecretreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - infraassessmentreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - rbacassessmentreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - sbomreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - vulnerabilityreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - batch
          resources:
            - cronjobs
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - batch
          resources:
            - jobs
          verbs:
            - create
            - delete
            - get
            - list
            - watch
        - apiGroups:
            - networking.k8s.io
          resources:
            - ingresses
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - networking.k8s.io
          resources:
            - networkpolicies
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - clusterrolebindings
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - clusterroles
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - rolebindings
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - roles
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - create
            - get
            - update
        - apiGroups:
            - ''
          resources:
            - serviceaccounts
          verbs:
            - get
        - apiGroups:
            - ''
          resources:
            - nodes/proxy
          verbs:
            - get
    role:
      rules:
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
            - get
            - update
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - create
        - apiGroups:
            - ''
          resources:
            - configmaps
          verbs:
            - create
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - create
            - get
            - delete
