installCRDs: true
autoPatching:
  enabled: true
  annotations:
    argocd-image-updater.argoproj.io/image-list: "trivy-operator=mirror.gcr.io/aquasec/trivy-operator:~v0"
workload:
  image:
    repository: "mirror.gcr.io/aquasec/trivy-operator"
    tag: "0.27.3"
  strategy:
    type: "Recreate"
  probes:
    readinessProbe:
      port: 9090
    livenessProbe:
      path: "/healthz"
      port: 9090
  resources:
    preset: ""
    custom:
      requests:
        cpu: "200m"
        memory: "512Mi"
        ephemeral-storage: "2Gi"
      limits:
        memory: "512Mi"
        ephemeral-storage: "2Gi"
  storage:
  - name: tmp
    type: emptyDir
    mountPath: /tmp
  envs:
  - name: OPERATOR_TARGET_NAMESPACES
    value: ''
  - name: OPERATOR_EXCLUDE_NAMESPACES
    value: ''
  - name: OPERATOR_TARGET_WORKLOADS
    value: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job"
  - name: OPERATOR_SERVICE_ACCOUNT
    value: trivy-operator
  envsConfigMap:
  - configMap: trivy-operator-config
service:
  ports:
  - name: healthcheck
    protocol: TCP
    port: 9090
  - name: http-metrics
    protocol: TCP
    port: 8080
configMap:
  enabled: true
  configMaps:
  - name: trivy-operator
    data:
      nodeCollector.volumes: "[{\"hostPath\":{\"path\":\"/var/lib/etcd\"},\"name\":\"var-lib-etcd\"},{\"hostPath\":{\"path\":\"/var/lib/kubelet\"},\"name\":\"var-lib-kubelet\"},{\"hostPath\":{\"path\":\"/var/lib/kube-scheduler\"},\"name\":\"var-lib-kube-scheduler\"},{\"hostPath\":{\"path\":\"/var/lib/kube-controller-manager\"},\"name\":\"var-lib-kube-controller-manager\"},{\"hostPath\":{\"path\":\"/etc/systemd\"},\"name\":\"etc-systemd\"},{\"hostPath\":{\"path\":\"/lib/systemd\"},\"name\":\"lib-systemd\"},{\"hostPath\":{\"path\":\"/etc/kubernetes\"},\"name\":\"etc-kubernetes\"},{\"hostPath\":{\"path\":\"/etc/cni/net.d/\"},\"name\":\"etc-cni-netd\"}]"
      nodeCollector.volumeMounts: "[{\"mountPath\":\"/var/lib/etcd\",\"name\":\"var-lib-etcd\",\"readOnly\":true},{\"mountPath\":\"/var/lib/kubelet\",\"name\":\"var-lib-kubelet\",\"readOnly\":true},{\"mountPath\":\"/var/lib/kube-scheduler\",\"name\":\"var-lib-kube-scheduler\",\"readOnly\":true},{\"mountPath\":\"/var/lib/kube-controller-manager\",\"name\":\"var-lib-kube-controller-manager\",\"readOnly\":true},{\"mountPath\":\"/etc/systemd\",\"name\":\"etc-systemd\",\"readOnly\":true},{\"mountPath\":\"/lib/systemd/\",\"name\":\"lib-systemd\",\"readOnly\":true},{\"mountPath\":\"/etc/kubernetes\",\"name\":\"etc-kubernetes\",\"readOnly\":true},{\"mountPath\":\"/etc/cni/net.d/\",\"name\":\"etc-cni-netd\",\"readOnly\":true}]"
      scanJob.useGCRServiceAccount: "true"
      scanJob.podTemplateContainerSecurityContext: "{\"allowPrivilegeEscalation\":false,\"capabilities\":{\"drop\":[\"ALL\"]},\"privileged\":false,\"readOnlyRootFilesystem\":true}"
      scanJob.compressLogs: "true"
      scanJob.tolerations: "[{\"key\":\"node-role.kubernetes.io/control-plane\",\"operator\":\"Exists\",\"effect\":\"NoSchedule\"}]"
      vulnerabilityReports.scanner: "Trivy"
      vulnerabilityReports.scanJobsInSameNamespace: "false"
      configAuditReports.scanner: "Trivy"
      compliance.failEntriesLimit: "10"
      report.recordFailedChecksOnly: "true"
      node.collector.imageRef: "ghcr.io/aquasecurity/node-collector:0.3.1"
      policies.bundle.oci.ref: "mirror.gcr.io/aquasec/trivy-checks:1"
      policies.bundle.insecure: "false"
      node.collector.nodeSelector: "true"
  - name: trivy-operator-config
    data:
      OPERATOR_LOG_DEV_MODE: "false"
      OPERATOR_SCAN_JOB_TTL: ""
      OPERATOR_SCAN_JOB_TIMEOUT: "5m"
      OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT: "10"
      OPERATOR_CONCURRENT_NODE_COLLECTOR_LIMIT: "1"
      OPERATOR_SCAN_JOB_RETRY_AFTER: "30s"
      OPERATOR_BATCH_DELETE_LIMIT: "10"
      OPERATOR_BATCH_DELETE_DELAY: "10s"
      OPERATOR_METRICS_BIND_ADDRESS: ":8080"
      OPERATOR_METRICS_FINDINGS_ENABLED: "true"
      OPERATOR_METRICS_VULN_ID_ENABLED: "true"
      OPERATOR_HEALTH_PROBE_BIND_ADDRESS: ":9090"
      OPERATOR_VULNERABILITY_SCANNER_ENABLED: "true"
      OPERATOR_SBOM_GENERATION_ENABLED: "true"
      OPERATOR_CLUSTER_SBOM_CACHE_ENABLED: "false"
      OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS: "true"
      OPERATOR_SCANNER_REPORT_TTL: "24h"
      OPERATOR_CACHE_REPORT_TTL: "120h"
      CONTROLLER_CACHE_SYNC_TIMEOUT: "5m"
      OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED: "true"
      OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED: "true"
      OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED: "true"
      OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS: "true"
      OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED: "true"
      OPERATOR_METRICS_EXPOSED_SECRET_INFO_ENABLED: "true"
      OPERATOR_METRICS_CONFIG_AUDIT_INFO_ENABLED: "true"
      OPERATOR_METRICS_RBAC_ASSESSMENT_INFO_ENABLED: "true"
      OPERATOR_METRICS_INFRA_ASSESSMENT_INFO_ENABLED: "true"
      OPERATOR_METRICS_IMAGE_INFO_ENABLED: "true"
      OPERATOR_METRICS_CLUSTER_COMPLIANCE_INFO_ENABLED: "true"
      OPERATOR_WEBHOOK_BROADCAST_URL: ""
      OPERATOR_WEBHOOK_BROADCAST_TIMEOUT: "30s"
      OPERATOR_WEBHOOK_BROADCAST_CUSTOM_HEADERS: ""
      OPERATOR_SEND_DELETED_REPORTS: "false"
      OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES: "{}"
      OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS: "true"
      OPERATOR_BUILT_IN_TRIVY_SERVER: "false"
      TRIVY_SERVER_HEALTH_CHECK_CACHE_EXPIRATION: "10h"
      OPERATOR_MERGE_RBAC_FINDING_WITH_CONFIG_AUDIT: "false"
      OPERATOR_CLUSTER_COMPLIANCE_ENABLED: "true"
  - name: trivy-operator-trivy-config
    data:
      trivy.resources.requests.cpu: "50m"
      trivy.resources.requests.memory: "1Gi"
      trivy.resources.requests.ephemeral-storage: "3Gi"
      trivy.resources.limits.memory: "1Gi"
      trivy.resources.limits.ephemeral-storage: "3Gi"
      trivy.repository: "mirror.gcr.io/aquasec/trivy"
      trivy.tag: "0.64.1"
      trivy.imagePullPolicy: "IfNotPresent"
      trivy.additionalVulnerabilityReportFields: ""
      trivy.severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
      trivy.slow: "true"
      trivy.skipJavaDBUpdate: "false"
      trivy.includeDevDeps: "false"
      trivy.imageScanCacheDir: "/tmp/trivy/.cache"
      trivy.filesystemScanCacheDir: "/var/trivyoperator/trivy-db"
      trivy.dbRepository: "mirror.gcr.io/aquasec/trivy-db"
      trivy.javaDbRepository: "mirror.gcr.io/aquasec/trivy-java-db"
      trivy.command: "image"
      trivy.sbomSources: ""
      trivy.dbRepositoryInsecure: "false"
      trivy.useBuiltinRegoPolicies: "false"
      trivy.useEmbeddedRegoPolicies: "true"
      trivy.supportedConfigAuditKinds: "Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota"
      trivy.timeout: "5m0s"
      trivy.mode: "Standalone"
rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - limitranges
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/log
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - replicationcontrollers
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - resourcequotas
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - clustercompliancedetailreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - clustercompliancereports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - clustercompliancereports/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - clusterconfigauditreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - clusterinfraassessmentreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - clusterrbacassessmentreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - clustersbomreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - clustervulnerabilityreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - configauditreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - exposedsecretreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - infraassessmentreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - rbacassessmentreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - sbomreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aquasecurity.github.io
          resources:
          - vulnerabilityreports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - cronjobs
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - get
          - update
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
        - apiGroups:
            - ""
          resources:
            - nodes/proxy
          verbs:
            - get
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - configauditreports
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - exposedsecretreports
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - vulnerabilityreports
          verbs:
            - get
            - list
            - watch
    role:
      rules:
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
            - get
            - update
        - apiGroups:
            - ""
          resources:
            - events
          verbs:
            - create
        - apiGroups:
            - ""
          resources:
            - configmaps
          verbs:
            - create
            - get
            - list
            - watch
        - apiGroups:
            - ""
          resources:
            - secrets
          verbs:
            - create
            - get
            - delete
            - update

grafana:
  dashboard:
    enabled: true
    dashboards:
    - name: trivy
      title: "Trivy"
      url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/trivy-operator/dashboards/trivy.json"
      folder: "System"
    - name: trivy2
      title: "Trivy2"
      url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/trivy-operator/dashboards/trivy2.json"
      folder: "System"
