installCRDs: true

workload:
  image:
    registry: mirror.gcr.io
    repository: "aquasec/trivy-operator"
    tag: "0.26.1"
  probes:
    readinessProbe:
      port: 9090
    livenessProbe:
      path: "/healthz"
      port: 9090
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /tmp
  envs:
    - name: OPERATOR_TARGET_NAMESPACES
      value: ''
    - name: OPERATOR_EXCLUDE_NAMESPACES
      value: ''
    - name: OPERATOR_TARGET_WORKLOADS
      value: >-
        pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job
    - name: OPERATOR_SERVICE_ACCOUNT
      value: trivy-operator
    - name: "CONTROLLER_CACHE_SYNC_TIMEOUT"
      value: "5m"
    - name: "OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS"
      value: "true"
    - name: "OPERATOR_BATCH_DELETE_DELAY"
      value: "10s"
    - name: "OPERATOR_BATCH_DELETE_LIMIT"
      value: "10"
    - name: "OPERATOR_BUILT_IN_TRIVY_SERVER"
      value: "false"
    - name: "OPERATOR_CACHE_REPORT_TTL"
      value: "120h"
    - name: "OPERATOR_CLUSTER_COMPLIANCE_ENABLED"
      value: "true"
    - name: "OPERATOR_CLUSTER_SBOM_CACHE_ENABLED"
      value: "false"
    - name: "OPERATOR_CONCURRENT_NODE_COLLECTOR_LIMIT"
      value: "1"
    - name: "OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT"
      value: "10"
    - name: "OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS"
      value: "true"
    - name: "OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_HEALTH_PROBE_BIND_ADDRESS"
      value: ":9090"
    - name: "OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_LOG_DEV_MODE"
      value: "false"
    - name: "OPERATOR_MERGE_RBAC_FINDING_WITH_CONFIG_AUDIT"
      value: "false"
    - name: "OPERATOR_METRICS_BIND_ADDRESS"
      value: ":8080"
    - name: "OPERATOR_METRICS_CLUSTER_COMPLIANCE_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_CONFIG_AUDIT_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_EXPOSED_SECRET_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_FINDINGS_ENABLED"
      value: "true"
    - name: "OPERATOR_METRICS_IMAGE_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_INFRA_ASSESSMENT_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_RBAC_ASSESSMENT_INFO_ENABLED"
      value: "false"
    - name: "OPERATOR_METRICS_VULN_ID_ENABLED"
      value: "false"
    - name: "OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES"
      value: "{}"
    - name: "OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_SBOM_GENERATION_ENABLED"
      value: "true"
    - name: "OPERATOR_SCANNER_REPORT_TTL"
      value: "24h"
    - name: "OPERATOR_SCAN_JOB_RETRY_AFTER"
      value: "30s"
    - name: "OPERATOR_SCAN_JOB_TIMEOUT"
      value: "5m"
    - name: "OPERATOR_SCAN_JOB_TTL"
      value: ""
    - name: "OPERATOR_SEND_DELETED_REPORTS"
      value: "false"
    - name: "OPERATOR_VULNERABILITY_SCANNER_ENABLED"
      value: "true"
    - name: "OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS"
      value: "true"
    - name: "OPERATOR_WEBHOOK_BROADCAST_CUSTOM_HEADERS"
      value: ""
    - name: "OPERATOR_WEBHOOK_BROADCAST_TIMEOUT"
      value: "30s"
    - name: "OPERATOR_WEBHOOK_BROADCAST_URL"
      value: ""
    - name: "TRIVY_SERVER_HEALTH_CHECK_CACHE_EXPIRATION"
      value: "10h"

service:
  ports:
    - name: healthcheck
      protocol: TCP
      port: 9090
    - name: http-metrics
      protocol: TCP
      port: 8080

configMap:
  enabled: true
  configMaps:
    - name: trivy-operator-trivy-config
      data:
        trivy.repository: "mirror.gcr.io/aquasec/trivy"
        trivy.tag: "0.62.1"
        trivy.imagePullPolicy: "IfNotPresent"
        trivy.severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
        trivy.timeout: "5m0s"
        trivy.mode: "Standalone"
        trivy.resources.requests.cpu: "100m"
        trivy.resources.requests.memory: "100M"
        trivy.resources.limits.cpu: "500m"
        trivy.resources.limits.memory: "500M"

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - limitranges
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - nodes
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - pods
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - pods/log
          verbs:
            - get
            - list
        - apiGroups:
            - ''
          resources:
            - replicationcontrollers
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - resourcequotas
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - services
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apiextensions.k8s.io
          resources:
            - customresourcedefinitions
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
          resources:
            - daemonsets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
          resources:
            - deployments
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
          resources:
            - replicasets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps
          resources:
            - statefulsets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - apps.openshift.io
          resources:
            - deploymentconfigs
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustercompliancedetailreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustercompliancereports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustercompliancereports/status
          verbs:
            - get
            - patch
            - update
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clusterconfigauditreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clusterinfraassessmentreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clusterrbacassessmentreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustersbomreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - clustervulnerabilityreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - configauditreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - exposedsecretreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - infraassessmentreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - rbacassessmentreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - sbomreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - aquasecurity.github.io
          resources:
            - vulnerabilityreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - batch
          resources:
            - cronjobs
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - batch
          resources:
            - jobs
          verbs:
            - create
            - delete
            - get
            - list
            - watch
        - apiGroups:
            - networking.k8s.io
          resources:
            - ingresses
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - networking.k8s.io
          resources:
            - networkpolicies
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - clusterrolebindings
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - clusterroles
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - rolebindings
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - roles
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - create
            - get
            - update
        - apiGroups:
            - ''
          resources:
            - serviceaccounts
          verbs:
            - get
        - apiGroups:
            - ''
          resources:
            - nodes/proxy
          verbs:
            - get
    role:
      rules:
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
            - get
            - update
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - create
        - apiGroups:
            - ''
          resources:
            - configmaps
          verbs:
            - create
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - create
            - get
            - delete
