namespace: "immich"

workload:
  image:
    registry: ghcr.io
    repository: ghcr.io/immich-app/immich-machine-learning
    tag: v1.138.1
  envsSecret:
    - name: DB_HOSTNAME
      secret: immich-postgres-app
      key: host
    - name: DB_USERNAME
      secret: immich-postgres-app
      key: username
    - name: DB_PASSWORD
      secret: immich-postgres-app
      key: password
  resources:
    preset: ""
    custom:
      requests:
        cpu: "25m"
        memory: "512Mi"
        ephemeral-storage: "16Mi"
      limits:
        memory: "512Mi"
        ephemeral-storage: "16Mi"
  envs:
    - name: "DB_DATABASE_NAME"
      value: "immich"
    - name: "IMMICH_MACHINE_LEARNING_URL"
      value: "http://immich-machine-learning.immich.svc.cluster.local:3003"
    - name: "REDIS_HOSTNAME"
      value: "immich-redis.immich.svc.cluster.local"
    - name: TRANSFORMERS_CACHE
      value: /cache
  probes:
    readinessProbe:
      path: "/ping"
      port: 3003
    livenessProbe:
      path: "/ping"
      port: 3003
  # storage:
  #   - name: cache
  #     type: emptyDir
  #     mountPath: /cache
  #   - name: tmp
  #     type: emptyDir
  #     mountPath: /tmp
  securityContext:
    readOnlyRootFilesystem: false

service:
  ports:
    - name: http
      port: 3003
      protocol: TCP

ingress:
  enabled: false

autoscaling:
  enabled: false
