namespace: "media"

workload:
  type: "StatefulSet"
  image:
    registry: "ghcr.io"
    repository: home-operations/emby
    tag: 4.8.11
  envs:
    - name: "TZ"
      value: "Europe/London"
  probes:
    readinessProbe:
      type: tcpSocket
      port: 8096
    livenessProbe:
      type: tcpSocket
      port: 8096
  storage:
    - name: emby-data
      type: pvcTemplate
      mountPath: /config
      accessModes:
        - "ReadWriteOnce"
      storageClass: "longhorn2x"
      size: "50Gi"
      readOnly: false
    - name: media-1
      type: pvc
      mountPath: /data/media1
      claimName: "media-1"
    - name: media-2
      type: pvc
      mountPath: /data/media2
      claimName: "media-2"
    - name: tmp
      type: emptyDir
      mountPath: /tmp
      ramDisk: false
      readOnly: false

service:
  ports:
    - name: http
      port: 8096
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: emby.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "emby"
          port: 8096

autoscaling:
  enabled: false
