namespace: "minio"

workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: minio.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "minio-console"
          port: 9090

extraObjects:
  - |
    apiVersion: minio.min.io/v2
    kind: Tenant
    metadata:
      labels:
        app: minio
      name: minio
      namespace: minio
    spec:
      env:
        - name: "MINIO_IDENTITY_OPENID_DISPLAY_NAME"
          value: "Google"
        - name: "MINIO_IDENTITY_OPENID_ROLE_POLICY"
          value: "consoleAdmin"
        - name: MINIO_IDENTITY_OPENID_CONFIG_URL
          value: "https://accounts.google.com/.well-known/openid-configuration"
        - name: MINIO_IDENTITY_OPENID_CLIENT_ID
          value: "429988516792-n90gu7jaur1njs5c7o51m3ne81h6mkqs.apps.googleusercontent.com"
        - name: MINIO_IDENTITY_OPENID_SCOPES
          value: "openid,profile,email"
        - name: "MINIO_IDENTITY_OPENID_REDIRECT_URI"
          value: "https://minio.projectwhitebox.com/oauth_callback"
      buckets:
        - name: thanos
        - name: kuik
        - name: media
        - name: maybe
        - name: ezbookkeeping
      configuration:
        name: minio
      features:
        bucketDNS: true
        enableSFTP: false
      image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
      imagePullPolicy: IfNotPresent
      mountPath: /export
      podManagementPolicy: Parallel
      pools:
        - name: pool
          servers: 3
          volumesPerServer: 2
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              storageClassName: minio-operator
              accessModes:
                - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 9.09Ti
      poolsMetadata:
        annotations: {}
        labels: {}
      prometheusOperator: false
      requestAutoCert: false
      subPath: /data
