namespace: "minio"

workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: minio.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "minio-console"
          port: 9090

extraObjects:
  - |
    apiVersion: sts.min.io/v1alpha1
    kind: PolicyBinding
    metadata:
      name: kube-image-keepr
      namespace: minio
    spec:
      application:
        namespace: kube-image-keeper
        serviceaccount: kube-image-keeper
      policies:
        - readwrite
  - |
    apiVersion: minio.min.io/v2
    kind: Tenant
    metadata:
      labels:
        app: minio
      name: minio
      namespace: minio
    spec:
      buckets:
        - name: thanos
        - name: kuik
        - name: media
      configuration:
        name: minio
      features:
        bucketDNS: true
        enableSFTP: false
      image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
      imagePullPolicy: IfNotPresent
      mountPath: /export
      podManagementPolicy: Parallel
      pools:
        - name: pool
          servers: 4
          volumesPerServer: 1
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 500Gi
      poolsMetadata:
        annotations: {}
        labels: {}
      prometheusOperator: false
      requestAutoCert: false
      subPath: /data
      users:
        - name: thanos
