namespace: "minio"

workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

extraObjects:
  - |
    apiVersion: minio.min.io/v2
    kind: Tenant
    metadata:
      labels:
        app: minio
      name: minio
      namespace: minio
    spec:
      buckets:
        - name: thanos
        - name: kuik
        - name: media
      configuration:
        name: minio
      features:
        bucketDNS: true
        enableSFTP: false
      image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
      imagePullPolicy: IfNotPresent
      mountPath: /export
      podManagementPolicy: Parallel
      pools:
        - name: pool
          servers: 3
          volumesPerServer: 2
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              storageClassName: minio-local-filesystem-sc
              accessModes:
                - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 9.09Ti
      poolsMetadata:
        annotations: {}
        labels: {}
      prometheusOperator: false
      requestAutoCert: false
      subPath: /data
      users:
        - name: thanos
