namespace: "minio"

workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

# extraObjects:
#   - |
#     apiVersion: minio.min.io/v2
#     kind: Tenant
#     metadata:
#       labels:
#         app: minio
#       name: minio
#       namespace: minio
#     spec:
#       buckets:
#         - name: thanos
#         - name: kuik
#         - name: media
#       configuration:
#         name: minio
#       features:
#         bucketDNS: true
#         enableSFTP: false
#       image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
#       imagePullPolicy: IfNotPresent
#       mountPath: /export
#       podManagementPolicy: Parallel
#       pools:
#         - name: pool
#           servers: 3
#           volumesPerServer: 2
#           volumeClaimTemplate:
#             metadata:
#               name: data # Name prefix for the PVCs (e.g., data-my-minio-tenant-pool-0-0-0)
#             spec:
#               storageClassName: minio-local-block-sc # Must match your StorageClass
#               accessModes:
#                 - ReadWriteOnce
#               volumeMode: Block # Important: Must match the PVs
#               resources:
#                 requests:
#                   storage: 9.09Ti # PVCs request storage, must be satisfiable by your PVs
#       poolsMetadata:
#         annotations: {}
#         labels: {}
#       prometheusOperator: false
#       requestAutoCert: false
#       subPath: /data
#       users:
#         - name: thanos
