namespace: "minio"

workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

extraObjects:
  - |
    apiVersion: minio.min.io/v2
    kind: Tenant
    metadata:
      labels:
        app: minio
      name: minio
      namespace: minio
    spec:
      buckets:
        - name: thanos
        - name: kuik
        - name: media
      configuration:
        name: minio
      features:
        bucketDNS: true
        enableSFTP: false
      image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
      imagePullPolicy: IfNotPresent
      mountPath: /export
      podManagementPolicy: Parallel
      pools:
        - name: pool-0
          servers: 4
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 500Gi
              storageClassName: openebs-three-replica-hdd
          volumesPerServer: 1
      poolsMetadata:
        annotations: {}
        labels: {}
      prometheusOperator: false
      requestAutoCert: false
      subPath: /data
      users:
        - name: thanos
