namespace: "authentik"

workload:
  image:
    registry: ghcr.io
    repository: goauthentik/server
    tag: 2025.6.3
  args:
    - worker
  probes:
    readinessProbe:
      type: exec
      command: ["ak", "healthcheck"]
    livenessProbe:
      type: exec
      command: ["ak", "healthcheck"]
  storage:
    - name: templates
      type: emptyDir
      mountPath: /templates
    - name: certs
      type: emptyDir
      mountPath: /certs
  envsSecret:
    - name: AUTHENTIK_POSTGRESQL__HOST
      secret: authentik-postgres-app
      key: host
    - name: AUTHENTIK_POSTGRESQL__USER
      secret: authentik-postgres-app
      key: username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      secret: authentik-postgres-app
      key: password
    - name: AUTHENTIK_POSTGRESQL__NAME
      secret: authentik-postgres-app
      key: dbname
    - name: AUTHENTIK_SECRET_KEY
      secret: authentik
      key: AUTHENTIK_SECRET_KEY
    - name: AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY
      secret: authentik
      key: AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY
    - name: AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY
      secret: authentik
      key: AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY
  envs:
    - name: "AUTHENTIK_REDIS__HOST"
      value: "authentik-redis.authentik.svc.cluster.local"
    - name: "AUTHENTIK_STORAGE__MEDIA__BACKEND"
      value: "s3"
    - name: "AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME"
      value: "authentik-media"
    - name: "AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT"
      value: "http://minio.minio.svc.cluster.local"
    - name: "AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN"
      value: "minio.projectwhitebox.com/authentik-media"
    - name: "AUTHENTIK_STORAGE__MEDIA__S3__REGION"
      value: "us-east-1"
  resources:
    preset: ""
    custom:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "10000m"
        memory: "5Gi"

service:
  enabled: false

ingress:
  enabled: false

autoscaling:
  enabled: false
