namespace: "argocd"

workload:
  type: StatefulSet
  image:
    registry: quay.io
    repository: argoproj/argocd
    tag: v2.14.2
  args:
    - /usr/local/bin/argocd-application-controller
    - '--status-processors=20'
    - '--operation-processors=10'
    - '--app-resync=180'
    - '--self-heal-timeout-second=5'
    - '--repo-server'
    - argocd-repo-server:8081
    - '--logformat'
    - text
    - '--loglevel'
    - info
    - '--redis'
    - argocd-redis:6379
  envs:
    - name: ARGOCD_APPLICATION_CONTROLLER_NAME
      value: argocd-application-controller
    - name: ARGOCD_CONTROLLER_REPLICAS
      value: '1'
  envsSecret:
    - name: REDIS_PASSWORD
      secret: argocd-redis
      key: auth
  resources:
    preset: micro
  probes:
    readinessProbe:
      type: httpGet
      path: "/healthz"
      port: 8082
      scheme: "HTTP"
    livenessProbe:
      type: httpGet
      path: "/healthz?full=true"
      port: 8082
      scheme: "HTTP"
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /tmp
      ramDisk: false
      readOnly: false

service:
  ports:
    - name: http-metrics
      port: 8082
      protocol: TCP
