namespace: "argocd"

workload:
  type: StatefulSet
  # Sharding is only done on a cluster level, as we run argocd per cluster multiple replicas doesn't actually do anything at the moment.
  replicaCount: 1
  image:
    registry: quay.io
    repository: argoproj/argocd
    tag: v2.14.2
  command:
    - 'argocd-application-controller'
  args:
    - '--status-processors=5' # concurrent checking
    - '--operation-processors=5' # concurrent deployment
    - '--app-resync=180'
    - '--self-heal-timeout-seconds=5'
    - '--repo-server=argocd-repo-server:8081'
    - '--redis=argocd-redis:6379'
    - '--logformat=text'
    - '--loglevel=info'
  envs:
    - name: ARGOCD_APPLICATION_CONTROLLER_NAME
      value: argocd-application-controller
    - name: ARGOCD_CONTROLLER_REPLICAS
      value: 1
  probes:
    readinessProbe:
      path: "/healthz"
      port: 8082
    livenessProbe:
      path: "/healthz?full=true"
      port: 8082
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /tmp
      ramDisk: false
      readOnly: false

service:
  ports:
    - name: http-metrics
      port: 8082
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - '*'
          resources:
            - '*'
          verbs:
            - '*'
        - nonResourceURLs:
            - '*'
          verbs:
            - '*'
