namespace: "radarr"

service:
  enabled: false

serviceAccount:
  enabled: false

workload:
  enabled: false

pdb:
  enabled: false

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: radarr-postgres
    spec:
      description: "Radarr Database"
      imageName: ghcr.io/cloudnative-pg/postgresql:17.5
      instances: 1
      bootstrap:
        initdb:
          database: "radarr-main"
          owner: radarr
          postInitSQL:
            - CREATE DATABASE "radarr-log" OWNER radarr
            - COMMIT
      enableSuperuserAccess: false
      storage:
        pvcTemplate:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi
          storageClassName: "openebs"
          volumeMode: Filesystem
      resources:
        requests:
          cpu: "10m"
          memory: "256Mi"
        limits:
          memory: "256Mi"
