namespace: "argocd"

workload:
  image:
    registry: quay.io
    repository: argoproj/argocd
    tag: v3.0.3
    digest: "sha256:204287a6b59982127c03f8c4b5e748ad843fdb7b14d28c08796846c35f097bce"
  command:
    - 'argocd-repo-server'
  args:
    - '--port=8081'
    - '--metrics-port=8084'
    - '--logformat=text'
    - '--loglevel=info'
    - '--redis=argocd-redis:6379'
  envs:
    - name: ARGOCD_REPO_SERVER_NAME
      value: argocd-repo-server
    - name: ARGOCD_HELM_ALLOW_CONCURRENCY
      value: true
  probes:
    readinessProbe:
      path: "/healthz"
      port: 8084
    livenessProbe:
      path: "/healthz?full=true"
      port: 8084
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /tmp
      ramDisk: false
      readOnly: false
    - name: gpg-keys
      type: emptyDir
      mountPath: /app/config/gpg/keys
      ramDisk: false
      readOnly: false

service:
  ports:
    - name: http
      port: 8081
      protocol: TCP
    - name: http-metrics
      port: 8084
      protocol: TCP
