workload:
  envs:
    - name: ES_Serilog__MinimumLevel__Default
      value: Information
    - name: ES_Reflector__Watcher__Timeout
      value: ''
    - name: ES_Reflector__Kubernetes__SkipTlsVerify
      value: '"false"'
  image:
    registry: "http://docker-registry.docker-registry.svc.cluster.local:5000"
    repository: emberstack/kubernetes-reflector
    tag: 7.1.288
  resources:
    preset: nano
  storage:
    - mountPath: /tmp
      name: tmp
      readOnly: false
      type: emptyDir

service:
  enabled: false

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - configmaps
            - secrets
          verbs:
            - '*'
        - apiGroups:
            - ''
          resources:
            - namespaces
          verbs:
            - watch
            - list
