global:
  chart: "reflector"
  repository: "https://emberstack.github.io/helm-charts"
  version: "7.1.*"

replicaCount: 2
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
