workload:
  image:
    repository: emberstack/kubernetes-reflector
    tag: 7.1.288
  envs:
    - name: ES_Serilog__MinimumLevel__Default
      value: Information
    - name: ES_Reflector__Watcher__Timeout
      value: ''
    - name: ES_Reflector__Kubernetes__SkipTlsVerify
      value: false
  probes:
    readinessProbe:
      path: "/healthz"
      port: 25080
    livenessProbe:
      path: "/healthz"
      port: 25080
  storage:
    - mountPath: /tmp
      name: tmp
      readOnly: false
      type: emptyDir

service:
  ports:
    - name: http
      port: 25080
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - configmaps
            - secrets
          verbs:
            - '*'
        - apiGroups:
            - ''
          resources:
            - namespaces
          verbs:
            - watch
            - list
