workload:
  enabled: true
  image:
    registry: "docker.io"
    repository: "emberstack/kubernetes-reflector"
    tag: "7.1.288"
  envs:
    - name: ES_Serilog__MinimumLevel__Default
      value: "Information"
    - name: ES_Reflector__Kubernetes__SkipTlsVerify
      value: "false"
  replicaCount: 2
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
    runAsGroup: 1000
    readOnlyRootFilesystem: false
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: reflector
            topologyKey: kubernetes.io/hostname
          weight: 100
  strategy:
    type: RollingUpdate
    minAvailable: 1
    maxUnavailable: 1

pdb:
  enabled: true
  maxUnavailable: "1"

service:
  enabled: true
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 25080

serviceAccount:
  enabled: true
  automountServiceAccountToken: true

rbac:
  enabled: true
  type: ClusterRole
  rules:
    - apiGroups: [""]
      resources: ["configmaps", "secrets"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["watch", "list"]
