workload:
  image:
    repository: "grafana/grafana"
    tag: "11.4.0"
  replicaCount: 1
  envsSecret:
    - name: GF_SECURITY_ADMIN_USER
      secret: grafana
      key: GF_SECURITY_ADMIN_USER
    - name: GF_SECURITY_ADMIN_PASSWORD
      secret: grafana
      key: GF_SECURITY_ADMIN_PASSWORD
  # Unhash to enable postgres when storage is setup
  #   - name: GF_DATABASE_HOST
  #     secret: grafana-database-app
  #     key: host
  #   - name: GF_DATABASE_NAME
  #     secret: grafana-database-app
  #     key: dbname
  #   - name: GF_DATABASE_USER
  #     secret: grafana-database-app
  #     key: username
  #   - name: GF_DATABASE_PASSWORD
  #     secret: grafana-database-app
  #     key: password
  resources:
    preset: "micro"
  storage:
    - configMapName: grafana
      mountPath: /etc/grafana
      name: config
      type: configMap
    - name: tmp
      type: emptyDir
      mountPath: /var/lib/grafana

autoscaling:
  enabled: false

service:
  ports:
    - name: http
      protocol: TCP
      port: 3000

configMap:
  enabled: true
  data:
    grafana.ini: |
      [analytics]
      check_for_updates = false
      [grafana_net]
      url = https://grafana.net
      [log]
      mode = console
      [server]
      domain = ''
      # [database]
      # type = postgres

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: grafana.openjamlab.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: true
        secretName: "letsencrypt-wildcard-certificate"
      backend:
        service:
          name: "grafana"
          port: 3000

secret:
  enabled: true

# postgres:
#   enabled: false
#   replicas: 3
#   version: 17.2
#   size: "5Gi"

extraObjects:
  - |
    apiVersion: grafana.integreatly.org/v1beta1
    kind: Grafana
    metadata:
      name: grafana
      labels:
        dashboards: "grafana"
    spec:
      external:
        url: http://grafana.grafana.svc.cluster.local:3000
        adminUser:
          name: grafana
          key: GF_SECURITY_ADMIN_USER
        adminPassword:
          name: grafana
          key: GF_SECURITY_ADMIN_PASSWORD
