workload:
  annotations:
    match-regex.version-checker.io/grafana: '(\d+)\.(\d+)\.(\d+)'
  image:
    registry: "docker.io"
    repository: "grafana/grafana"
    tag: "12.0.2"
  envsSecret:
    - name: GF_SECURITY_ADMIN_USER
      secret: grafana
      key: ADMIN_USER
    - name: GF_SECURITY_ADMIN_PASSWORD
      secret: grafana
      key: ADMIN_PASSWORD
    - name: GF_DATABASE_HOST
      secret: grafana-postgres-app
      key: host
    - name: GF_DATABASE_NAME
      secret: grafana-postgres-app
      key: dbname
    - name: GF_DATABASE_USER
      secret: grafana-postgres-app
      key: username
    - name: GF_DATABASE_PASSWORD
      secret: grafana-postgres-app
      key: password
    - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      secret: grafana
      key: CLIENT_SECRET
  probes:
    readinessProbe:
      path: "/api/health"
      port: 3000
    livenessProbe:
      path: "/api/health"
      port: 3000
  storage:
    - name: config
      type: configMap
      mountPath: /etc/grafana
      configMapName: grafana
    - name: data
      type: emptyDir
      mountPath: /var/lib/grafana

autoscaling:
  enabled: false

service:
  ports:
    - name: http
      protocol: TCP
      port: 3000

configMap:
  enabled: true
  configMaps:
    - name: "grafana"
      data:
        grafana.ini: |
          [analytics]
          check_for_updates = false
          [grafana_net]
          url = https://grafana.net
          [log]
          mode = console
          [server]
          root_url = "https://grafana.projectwhitebox.com"
          [database]
          type = postgres
          [auth]
          disable_login_form = true
          [auth.generic_oauth]
          enabled = true
          allow_sign_up = true
          auto_login = false
          client_id = Caq9JwH7MhEoirm4TfQl4xt8WUXKT7wLnmf0vLS9
          scopes = openid email profile
          auth_url = https://auth.projectwhitebox.com/application/o/authorize/
          token_url = https://auth.projectwhitebox.com/application/o/token/
          api_url = https://auth.projectwhitebox.com/application/o/userinfo/
          role_attribute_path = contains(groups, 'Grafana Administrator') && 'Admin || 'Viewer''
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: grafana.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "grafana"
          port: 3000

grafana:
  folder:
    enabled: true
    folders:
      - name: "system"
        title: "System"
  dashboard:
    enabled: true
    dashboards:
      - name: kubernetes-global
        title: "Kubernetes / Global"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/grafana/dashboards/kubernetes-global.json"
        folder: "System"
      - name: kubernetes-pods
        title: "Kubernetes / Pods"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/grafana/dashboards/kubernetes-pods.json"
        folder: "System"
      - name: kubernetes-api-server
        title: "Kubernetes / API Server"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/grafana/dashboards/kubernetes-api-server.json"
        folder: "System"
      - name: compute-cluster
        title: "Compute / Cluster"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/grafana/dashboards/compute-cluster.json"
        folder: "System"
      - name: compute-nodes
        title: "Compute / Nodes"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/grafana/dashboards/compute-nodes.json"
        folder: "System"
      - name: kubernetes-storage
        title: "Kubernetes / Storage"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/grafana/dashboards/kubernetes-storage.json"
        folder: "System"

extraObjects:
  - |
    apiVersion: grafana.integreatly.org/v1beta1
    kind: Grafana
    metadata:
      name: grafana
      labels:
        dashboards: "grafana"
    spec:
      external:
        url: http://grafana.grafana.svc.cluster.local:3000
        adminUser:
          name: grafana
          key: ADMIN_USER
        adminPassword:
          name: grafana
          key: ADMIN_PASSWORD
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: grafana
      namespace: grafana
    spec:
      encryptedData:
        ADMIN_PASSWORD: AgB95AEu39XhhRww2l6+exw9BShycBomrA2OHJo2hUz+72CsDyGrMK2ptSh1sVD21NggMXkUOAisoht5KPQRShJfddPTzqzCkjt5q8sWM+O7IOVHER6xDEQAs3gbyBZhLKl0Zmoa6UE2nmV45d2mfayo7vCDhVPSUaVBk/v2fXyiww1TaOAk4uAgIwEYdBPik81O1l+09nOiiK/P0FwCSHJ5zatIIxz3hKPCQ4rGUasvavDYEyGbWvJpl+izrcqpXxG7S7Uw3whwpXfGRIjUlom2ex88B+DdAND0Lhqpmo3lHrNuYZLQqyXokLyVCP3Hb1OQBPMRBU+72yH6AdcQsfbA5oOPNYM/pvSQE1PO/dxDd2b6ecTKUnC0Gn6d5Ctk0g0hj3G4xPFPdFoZz6bNSpcT+ArSly3eNajuaUv/Yg315KO0Rs1oaWaMG0A4N3ay0ghiEJIS4JPphP7AZwVqKzDPCmPp8U3EkH7ryVfI2odVyGVX7v+tdBY9jM/KI4D1agVv0+xcA35YbtMKkVF+L79JY7T4iNttmANYSTwCE9TLjFDwTv/di7Q/gYuKyleVeEXxdLRSOCdRkJSbxFJ9DTD2seZdQMguYV2Mb2m/xsU/NJI9JZQyccdqNVGly7af0/20K1Mhm+nIAUoFut9VtSUE+VMeNmTpEl3ers21JRERpqKhlVuAftaHbp6YuFJMPMWZCj7YYCNBJyJ9Kkv/MBt7QpEgQFOUa/whwjJdqK6yv6mVO5pyWgSASS3+slZVYXhki23ChBWx1QiwSU1X9nzP
        ADMIN_USER: AgAbwSg+BW3f2cjY9ZWmKr4YDRlrTgLo6a0E5hGnhXvw+bsYy/gDQXy3e32iKYy2/qtjJNdmd2g3vxzDkmfXPnFZdF/q6iqR4uuCTI8SDa1ecfw34Zo/2SGTJlXB+wTsVbKyj3eYNnYeqwSLfzpFB4n0ocNFjwmThkAHMOA4WR0O4P679W/aM4EVR5LQMH8r1UUBGgRTOK4tbrrfphfMWE/iSbg4cRa5sobnGea/ysUkJ8kXWqkEdC9KKirydf5iXAjnmuVQHaUeEdY6jxCXCoXicKGsj/FOro4v3LKqmZxO5nu27eZ6bmhzp7sIHl2qrwwjpqCuQn9PJosIFiGFbKtp3xneYzPqweva8iT6pBmGE58720kRdDnlwyFWOJHdZpkxucXbbhjLlQCHf3K6UTD/7fe9TbF3/EV+2xeYiOa7TuZxgtryangtgb3KtqgWIwMuAGzXv0awwh94p6SJo9QpBAaGOXdxAXYRXkE5d+vYV4QTpeavR9BiewbjQHAXUjk83uJ+Vh7Rg12uY8Uk3oiL7cQqz9TfV3BH8k5nE+bH/0nHZmf8VrciGlS3gJIzWoNPBT2fhPXulZRXKuGfEQ9pp4G3mRzaTh54UynJYFNSSSEbaeQMn24LPX62XWlNJvsEZdTwk6aYwS3lSsJreR0RtOK1kRVojOV/XEslCfQLOWotfUU3QPR6tQ2O1Ygfoef03LxT0Q==
        CLIENT_SECRET: AgACkYFMH6sUR6J4qby7ZaGgGnSVDk2ldcwwTMFRmD3DyNTP5YtYe/F9u3ecMyXHO77ddvU2hqMpNrGb1ge6LIb8socguoMalIAPD/YY4iGO+Qvlzc7XfIS7Sj6cpGvht++uOPJjZ2inH/v3A8VUH9eg9KfE/d1JAfJXZDDLiHJf/HXuT2VogCyTBvzQUSRR13MT8sZ7ZnrrT049t1VcYVfOr+AvifPGlJgsKP8NYD9gscXx2GwPTDfkPJU0YtFKSajwbmCl8NNHXCujIMn3E1ujWpXV2+n0RvhFU0d60jSHHGt7ZuXqrW1jImpHBkTeZjG3xLuzYgZOoHHP643OzMIM/ALoTdvRgnEmGdJO/LZGh5Zcyyt0G8GToWjJjETFDvARQKo4wQ/I7CtQFMdtT7xqBHF8+KD2JT46HxG5ecF+b3tKtZZITD7STR6U6yyd4oKQOY10bAoXUrvgdldtLKKLjQ0Mt2wgXRxk2pqR1arPnzdDmRfpVX/+b4gou+Op7q1Pz/+laTMmC/za54Uko12GHFfcpufdisdfrxkNvkN6pLwUG6z1RUvmEqf49dFmljgp7VO8uAakmrbkctc2MjSZ3cqUsIZxbUfuZH0Pa3F0L/Tqt7yFZrvFvSnyZ7cA16u90OmWJzgdMN0dM0OngLx+oYUPpIPCrYtUanMXyrsZyCb1d/GTEIO3aI4uRr+W8Ga9wa8aRRlE79Eb22n5DVTLLxk2/JY6auyo+pe4WZ6bsORmePPeFQo86lydvrDvJhFvE6c72+6XcKy6KN6BssDDHeRXlANBCyISnTIlONU7GeSPU2Ab0igwq4wONR/n0YBEa96ShV7uU5Z7a4ZWWnEnZVuEkHijjngQFCBSUrpjVA==
      template:
        metadata:
          name: grafana
          namespace: grafana
        type: Opaque
