workload:
  image:
    repository: "grafana/grafana"
    tag: "11.4.0"
  replicaCount: 2
  envsSecret:
    - name: GF_DATABASE_HOST
      secret: grafana-app
      key: host
    - name: GF_DATABASE_NAME
      secret: grafana-app
      key: name
    - name: GF_DATABASE_USERNAME
      secret: grafana-app
      key: username
    - name: GF_DATABASE_PASSWORD
      secret: grafana-app
      key: password
  resources:
    preset: "micro"
  storage:
    - configMapName: grafana
      mountPath: /etc/grafana
      name: config
      type: configMap
    - name: tmp
      type: emptyDir
      mountPath: /var/lib/grafana

autoscaling:
  enabled: false

service:
  ports:
    - name: http
      protocol: TCP
      port: 3000

configMap:
  enabled: true
  data:
    grafana.ini: |
      [analytics]
      check_for_updates = false
      [grafana_net]
      url = https://grafana.net
      [log]
      mode = console
      [server]
      domain = ''
      [database]
      type = postgres

ingress:
  enabled: true
  entryPoints:
    - internalwebsecure
    - internalweb
  port: http
  prefix: "grafana"
  tls: true
