workload:
  image:
    repository: "grafana/grafana"
    tag: "11.4.0"
  replicaCount: 2
  envsSecret:
    - name: POSTGRES_PASSWORD
      secret: grafana-postgres
      key: POSTGRES_PASSWORD
  resources:
    preset: "micro"
  storage:
    - name: tmp
      type: emptyDir
      mountPath: /var/lib/grafana

autoscaling:
  enabled: false

service:
  ports:
    - name: http
      protocol: TCP
      port: 3000

configMap:
  enabled: true
  data:
    grafana.ini: |
      [analytics]
      check_for_updates = false
      [grafana_net]
      url = https://grafana.net
      [log]
      mode = console
      [paths]
      data = /var/lib/grafana/
      logs = /var/log/grafana
      plugins = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning
      [server]
      domain = ''
      [database]
      type = postgres
      host = grafana-postgres.grafana.svc.cluster.local:5432
      name = grafana
      user = grafana
      password = $__env{POSTGRES_PASSWORD}

ingress:
  enabled: true
  entryPoints:
    - internalwebsecure
    - internalweb
  port: http
  prefix: "grafana"
  tls: true

postgres:
  enabled: true
  replicas: 2
