namespace: "argo-rollouts"
installCRDs: true
autoPatching:
  enabled: true
  annotations:
    argocd-image-updater.argoproj.io/image-list: "argo-rollouts-controller=quay.io/argoproj/argo-rollouts:~v1"
workload:
  image:
    repository: quay.io/argoproj/argo-rollouts
    tag: v1.8.3
  resources:
    preset: ""
    custom:
      requests:
        cpu: "25m"
        memory: "256Mi"
        ephemeral-storage: "16Mi"
      limits:
        memory: "256Mi"
        ephemeral-storage: "16Mi"
  args:
  - '--healthzPort=8080'
  - '--metricsport=8090'
  - '--loglevel=info'
  - '--logformat=text'
  - '--kloglevel=0'
  - '--leader-elect'
  probes:
    readinessProbe:
      path: "/metrics"
      port: 8090
    livenessProbe:
      path: "/healthz"
      port: 8080
  # storage:
  # - name: plugin-bin
  #   type: emptyDir
  #   mountPath: /home/argo-rollouts/plugin-bin
  #   ramDisk: false
  #   readOnly: false
  # - name: tmp
  #   type: emptyDir
  #   mountPath: /tmp
  #   ramDisk: false
  #   readOnly: false
service:
  enabled: false
autoscaling:
  enabled: false
rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
      - apiGroups:
        - argoproj.io
        resources:
        - rollouts
        - rollouts/status
        - rollouts/finalizers
        verbs:
        - get
        - list
        - watch
        - update
        - patch
      - apiGroups:
        - argoproj.io
        resources:
        - analysisruns
        - analysisruns/finalizers
        - experiments
        - experiments/finalizers
        verbs:
        - create
        - get
        - list
        - watch
        - update
        - patch
        - delete
      - apiGroups:
        - argoproj.io
        resources:
        - analysistemplates
        - clusteranalysistemplates
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - apps
        resources:
        - replicasets
        verbs:
        - create
        - get
        - list
        - watch
        - update
        - patch
        - delete
      - apiGroups:
        - ''
        - apps
        resources:
        - deployments
        - podtemplates
        verbs:
        - get
        - list
        - watch
        - update
      - apiGroups:
        - ''
        resources:
        - services
        verbs:
        - get
        - list
        - watch
        - patch
        - create
        - delete
      - apiGroups:
        - coordination.k8s.io
        resources:
        - leases
        verbs:
        - create
        - get
        - update
      - apiGroups:
        - ''
        resources:
        - secrets
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ''
        resources:
        - configmaps
        verbs:
        - get
        - list
        - watch
        - create
        - update
      - apiGroups:
        - ''
        resources:
        - pods
        verbs:
        - list
        - update
        - watch
      - apiGroups:
        - ''
        resources:
        - pods/eviction
        verbs:
        - create
      - apiGroups:
        - ''
        resources:
        - events
        verbs:
        - create
        - update
        - patch
      - apiGroups:
        - networking.k8s.io
        - extensions
        resources:
        - ingresses
        verbs:
        - create
        - get
        - list
        - watch
        - update
        - patch
      - apiGroups:
        - batch
        resources:
        - jobs
        verbs:
        - create
        - get
        - list
        - watch
        - update
        - patch
        - delete
      - apiGroups:
        - networking.istio.io
        resources:
        - virtualservices
        - destinationrules
        verbs:
        - watch
        - get
        - update
        - patch
        - list
      - apiGroups:
        - split.smi-spec.io
        resources:
        - trafficsplits
        verbs:
        - create
        - watch
        - get
        - update
        - patch
      - apiGroups:
        - getambassador.io
        - x.getambassador.io
        resources:
        - mappings
        - ambassadormappings
        verbs:
        - create
        - watch
        - get
        - update
        - list
        - delete
      - apiGroups:
        - ''
        resources:
        - endpoints
        verbs:
        - get
      - apiGroups:
        - elbv2.k8s.aws
        resources:
        - targetgroupbindings
        verbs:
        - list
        - get
      - apiGroups:
        - appmesh.k8s.aws
        resources:
        - virtualservices
        verbs:
        - watch
        - get
        - list
      - apiGroups:
        - appmesh.k8s.aws
        resources:
        - virtualnodes
        - virtualrouters
        verbs:
        - watch
        - get
        - list
        - update
        - patch
      - apiGroups:
        - traefik.containo.us
        - traefik.io
        resources:
        - traefikservices
        verbs:
        - watch
        - get
        - update
      - apiGroups:
        - apisix.apache.org
        resources:
        - apisixroutes
        verbs:
        - watch
        - get
        - update
      - apiGroups:
        - projectcontour.io
        resources:
        - httpproxies
        verbs:
        - get
        - list
        - watch
        - update
      - apiGroups:
        - networking.gloo.solo.io
        resources:
        - routetables
        verbs:
        - '*'
      - apiGroups:
        - gateway.networking.k8s.io
        resources:
        - httproutes
        - tcproutes
        - tlsroutes
        - udproutes
        - grpcroutes
        verbs:
        - get
        - list
        - watch
        - update
