namespace: "kube-image-keeper"
installCRDs: true

workload:
  image:
    registry: ghcr.io
    repository: enix/kube-image-keeper
    tag: 1.13.1
  command:
    - manager
  args:
    - '-proxy-port=7439'
    - '-registry-endpoint=kube-image-keeper-registry.kube-image-keeper.svc.cluster.local:5000'
    - '-leader-elect'
    - '-expiry-delay=30'
    - '-max-concurrent-cached-image-reconciles=3'
    - '-zap-log-level=INFO'
    - '-ignore-pull-policy-always=true'
    - '-arch=amd64'
  probes:
    readinessProbe:
      port: 8081
    livenessProbe:
      path: "/healthz"
      port: 8081
  storage:
    - name: kube-image-keeper-controller-certificate
      type: secret
      mountPath: /tmp/k8s-webhook-server/serving-certs
      secretName: kube-image-keeper-controller-certificate

service:
  ports:
    - name: http
      port: 9443
      protocol: TCP
    - name: http-metrics
      port: 8080
      protocol: TCP

certificate:
  enabled: true
  spec:
    dnsNames:
      - kube-image-keeper-controller.kube-image-keeper.svc
      - kube-image-keeper-controller.kube-image-keeper.svc.cluster.local
    issuerRef:
      kind: Issuer
      name: kube-image-keeper-controller
    secretName: kube-image-keeper-controller-certificate

issuer:
  enabled: true
  type: Issuer
  spec:
    selfSigned: {}

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - create
            - patch
        - apiGroups:
            - ''
          resources:
            - pods
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - ''
          resources:
            - serviceaccounts
          verbs:
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - pods/finalizers
          verbs:
            - update
        - apiGroups:
            - ''
          resources:
            - pods/status
          verbs:
            - get
            - patch
            - update
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - kuik.enix.io
          resources:
            - cachedimages
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - kuik.enix.io
          resources:
            - cachedimages/finalizers
          verbs:
            - update
        - apiGroups:
            - kuik.enix.io
          resources:
            - cachedimages/status
          verbs:
            - get
            - patch
            - update
        - apiGroups:
            - kuik.enix.io
          resources:
            - repositories
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - kuik.enix.io
          resources:
            - repositories/finalizers
          verbs:
            - update
        - apiGroups:
            - kuik.enix.io
          resources:
            - repositories/status
          verbs:
            - get
            - patch
            - update
        - apiGroups:
            - ''
          resources:
            - configmaps
          verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - create
            - patch

grafana:
  dashboard:
    enabled: true
    dashboards:
      - name: kubernetes-image-cache
        title: "Kubernetes / Image Cache"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/kube-image-keeper-controller/dashboards/kubernetes-image-cache.json"
        folder: "System"

extraObjects:
  - |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: secret-name
      namespace: kube-image-keeper
    spec:
      encryptedData:
        accessKey: AgBWNct8PTXXlCP7CP7LN4I0fPg8Qukdmveaek6rBaxSlSZ7nAYxWCq8viiGEjdUghGHTIBwrVcr3I6X1FDHU06pUVSl3tBBPgq1xl8x8zyM5FHdhaOegxjAnGW5eXTgonQMtFFdeCW32+J+TgKvlw488Sy0lwozmnCyYtIY5z/tXRks1VoJd0E7IiFuk6mfC3hw7kcn6PKV2S+JTq0pS08o+PWxygbYx+OxbELE6sX/XcXHRtDGXZ2VAmoUALHHEoGJ5ST3DMIo4q6Lh9rIGEH/q1Tt5qHA+HdXImVgf3HzD62APZF4l7jtMTQW8sOsjtIr8pFgiuiaLloU7m0Qu61yg/JW+Jsxe4SHgq+CgyZaxobXxAfyCLHfjFQ1ANyPAugS2FayMi/Ly2VaxStW4Rlge7g3FJdvWmM6xIHGCs1Lnf31ie+/ko9s0elctMOqUj8xDMs7YS1MgRNS7ZewQfha8DLbknmTf38hNHJ6tNRgRCL9djW4fDzEA8msR05/9gT1m3wg21HMQ2DZeOfxg+2N9gO+K3FZScFtro7MKoqRNLYl0b4nKySzPE9CwPMMU61QA7l4u8RIJ0WB1B+Lf46rueszAC5xyGBUli52ywKVKaMZt7eZWGv2ZkQOf7FsAgNRGNWpooyU+JWOBEKtP1O/L8wziyhDlmocm9L5GlerWfRl0DH04gLiKuZsnSijePC6Yeh+VcMwhkY6gsOrZNXZ7UdvSuc=
        secretKey: AgCJlEsCCag+plvtujO0vm6Y42d3Ip2gS0uO2OdL1Gf/CN7C2huG+5wNzxcNvJtrFUJ9a2F8iRIMS0Z1aDO812NEshnVirImBwUkdcSfRRwDuYHTnCAblwYH1CqxgbBYbM9/gfv3m4ZN76NmkFZ9dFK69U4RTQt829xZwxraAmbNnt44alQZFHb6VC9oHfGTdNSDSzhonUrE79u/U7kwDmO9MLeDt/QJPqd3/pOyOIk7+S7JKqYx2HtypoRIV/pAaFk7y42PQC2Abvr2Ad127XFmN7hUdzMqjXSNiaQqgbt9kvhPh0ed845+eqbALNhGixGCrnNFliNl0mchndWCk69qevBaWjsaVURJTv9UwrEW7sQ2H8YYBF2zTwZOpXlIZFZQa7RpMb6g8ZoxTRtGznjbc8lBstETOt772JiEyndtCLeJjHVzUnytVi5wya47OuEwEaaPzE+dR1Lbp51RE1Ev1rNX9nllKVciMbom0eH8xhwCTGV6lCqW5EuoNWJZenfxE84RrsX9DMi8cv4ZhKSKt0t7xWqmCkbNUwZw+h5x8PCWOSL0SusdLgA9gQguY2OzVJQ0wGjAy6GJFJsh0FjkFwYjYtJ3w+P/V6IFoRDpdMwQI3wxPUEYufmzY3txl/Nw0FKLvnbs53uEUO/OCZmKB19ZXOAWp7Kf6jbW7nQErFABLFVj57bm/I0lxd43/BC/MfTSHhSyzNOsDSIF4PrW66xqjKhRXu0sK75TfHr5yy6wVPnMxqpI
      template:
        metadata:
          name: secret-name
          namespace: kube-image-keeper
        type: Opaque
  - |
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    metadata:
      annotations:
        cert-manager.io/inject-ca-from: kube-image-keeper/kube-image-keeper-controller
      name: kube-image-keeper-controller
    webhooks:
      - admissionReviewVersions:
          - v1
          - v1beta1
        clientConfig:
          service:
            name: kube-image-keeper-controller
            namespace: kube-image-keeper
            path: /mutate-core-v1-pod
            port: 9443
        failurePolicy: Ignore
        name: mpod.kb.io
        namespaceSelector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
                - kube-system
                - kube-image-keeper
                - openebs
                - minio
        objectSelector:
          matchExpressions:
            - key: kube-image-keeper.enix.io/image-caching-policy
              operator: NotIn
              values:
                - ignore
        reinvocationPolicy: IfNeeded
        rules:
          - apiGroups:
              - ''
            apiVersions:
              - v1
            operations:
              - CREATE
              - UPDATE
            resources:
              - pods
        sideEffects: None
      - admissionReviewVersions:
          - v1
        clientConfig:
          service:
            name: kube-image-keeper-controller
            namespace: kube-image-keeper
            path: /mutate-kuik-enix-io-v1alpha1-cachedimage
            port: 9443
        failurePolicy: Fail
        name: mcachedimage.kb.io
        rules:
          - apiGroups:
              - kuik.enix.io
            apiVersions:
              - v1alpha1
            operations:
              - CREATE
              - UPDATE
            resources:
              - cachedimages
        sideEffects: None
