workload:
  image:
    registry: ghcr.io
    repository: fallenbagel/jellyseerr
    tag: 2.7.0
  probes:
    readinessProbe:
      type: tcpSocket
      port: 5055
    livenessProbe:
      type: tcpSocket
      port: 5055
  envsSecret:
    - name: DB_HOST
      secret: jellyseerr-postgres-app
      key: host
    - name: DB_USER
      secret: jellyseerr-postgres-app
      key: username
    - name: DB_PASS
      secret: jellyseerr-postgres-app
      key: password
    - name: DB_PORT
      secret: jellyseerr-postgres-app
      key: port
    - name: DB_NAME
      secret: jellyseerr-postgres-app
      key: dbname
  envs:
    - name: "DB_TYPE"
      value: "postgres"
  storage:
    - name: jellyseerr-config
      type: pvc
      mountPath: /app/config
      claimName: "jellyseerr-config"
  resources:
    preset: ""
    custom:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "10000m"
        memory: "5Gi"

service:
  ports:
    - name: http
      port: 5055
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure, externalweb, externalwebsecure"
  hosts:
    - host: request.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "jellyseerr"
          port: 5055

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: jellyseerr-config
    spec:
      capacity:
        storage: 1Ti
      accessModes:
        - ReadWriteMany
      nfs:
        server: 10.0.0.10
        path: "/mnt/data-pool/jellyseerr"
      mountOptions:
        - nfsvers=4.1 
        - hard      
        - noatime
        - rsize=1048576 
        - wsize=1048576 
        - proto=tcp
        - async
        - nconnect=8
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: jellyseerr-config
      namespace: jellyseerr
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: ""
      resources:
        requests:
          storage: 1Ti
      volumeName: jellyseerr-config
