workload:
  type: "StatefulSet"
  image:
    registry: ghcr.io
    repository: home-operations/radarr
    tag: 5.26.0
  envsSecret:
    - name: RADARR__POSTGRES__HOST
      secret: radarr-postgres-app
      key: host
    - name: RADARR__POSTGRES__USER
      secret: radarr-postgres-app
      key: username
    - name: RADARR__POSTGRES__PASSWORD
      secret: radarr-postgres-app
      key: password
  envs:
    - name: "RADARR__POSTGRES__PORT"
      value: "5432"
  probes:
    readinessProbe:
      type: tcpSocket
      port: 7878
    livenessProbe:
      type: tcpSocket
      port: 7878
  storage:
    - name: config
      type: emptyDir
      mountPath: /config
    - name: radarr-downloads
      type: pvc
      mountPath: /downloads
      claimName: "radarr-downloads"
    - name: radarr-movies
      type: pvc
      mountPath: /media/movies
      claimName: "radarr-movies"
    - name: radarr-tv
      type: pvc
      mountPath: /media/tv
      claimName: "radarr-tv"
    - name: radarr-anime
      type: pvc
      mountPath: /media/anime
      claimName: "radarr-anime"

service:
  ports:
    - name: http
      port: 7878
      protocol: TCP

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: newradarr.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "radarr"
          port: 7878

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: radarr-downloads
    spec:
      capacity:
        storage: 1Ti
      accessModes:
        - ReadWriteMany
      nfs:
        server: 10.0.0.10
        path: "/mnt/data-pool/downloads"
      mountOptions:
        - nfsvers=4.1 
        - hard      
        - noatime
        - rsize=1048576 
        - wsize=1048576 
        - proto=tcp
        - sync
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: sabnzbd-downloads
      namespace: sabnzbd
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: ""
      resources:
        requests:
          storage: 1Ti
      volumeName: sabnzbd-downloads
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: radarr-movies
    spec:
      capacity:
        storage: 1Ti
      accessModes:
        - ReadWriteMany
      nfs:
        server: 10.0.0.10
        path: "/mnt/media-pool/movies"
      mountOptions:
        - nfsvers=4.1 
        - hard      
        - noatime
        - rsize=1048576 
        - wsize=1048576 
        - proto=tcp
        - sync
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: radarr-movies
      namespace: sabnzbd
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: ""
      resources:
        requests:
          storage: 1Ti
      volumeName: radarr-movies
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: radarr-tv
    spec:
      capacity:
        storage: 1Ti
      accessModes:
        - ReadWriteMany
      nfs:
        server: 10.0.0.10
        path: "/mnt/media-pool/tv"
      mountOptions:
        - nfsvers=4.1 
        - hard      
        - noatime
        - rsize=1048576 
        - wsize=1048576 
        - proto=tcp
        - sync
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: radarr-tv
      namespace: sabnzbd
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: ""
      resources:
        requests:
          storage: 1Ti
      volumeName: radarr-tv
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: radarr-anime
    spec:
      capacity:
        storage: 1Ti
      accessModes:
        - ReadWriteMany
      nfs:
        server: 10.0.0.10
        path: "/mnt/media-pool/anime"
      mountOptions:
        - nfsvers=4.1 
        - hard      
        - noatime
        - rsize=1048576 
        - wsize=1048576 
        - proto=tcp
        - sync
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: radarr-anime
      namespace: sabnzbd
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: ""
      resources:
        requests:
          storage: 1Ti
      volumeName: radarr-anime
