installCRDs: true

workload:
  image:
    registry: ghcr.io
    repository: ot-container-kit/redis-operator/redis-operator
    tag: v0.19.0
  command:
    - /manager
  args:
    - --leader-elect
  probes:
    readinessProbe:
      type: httpGet
      path: "/readyz"
      port: 8081
      scheme: "HTTP"
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
      initialDelaySeconds: 15
    livenessProbe:
      type: httpGet
      path: "/healthz"
      port: 8081
      scheme: "HTTP"
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
      initialDelaySeconds: 15
  resources:
    preset: nano

service:
  ports:
    - name: http
      port: 9443
      protocol: TCP
    - name: http-metrics
      port: 8080
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - redis.redis.opstreelabs.in
          resources:
            - rediss
            - redisclusters
            - redisreplications
            - redis
            - rediscluster
            - redissentinel
            - redissentinels
            - redisreplication
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - nonResourceURLs:
            - '*'
          verbs:
            - get
        - apiGroups:
            - apiextensions.k8s.io
          resources:
            - customresourcedefinitions
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - redis.redis.opstreelabs.in
          resources:
            - redis/finalizers
            - rediscluster/finalizers
            - redisclusters/finalizers
            - redissentinel/finalizers
            - redissentinels/finalizers
            - redisreplication/finalizers
            - redisreplications/finalizers
          verbs:
            - update
        - apiGroups:
            - redis.redis.opstreelabs.in
          resources:
            - redis/status
            - rediscluster/status
            - redisclusters/status
            - redissentinel/status
            - redissentinels/status
            - redisreplication/status
            - redisreplications/status
          verbs:
            - get
            - patch
            - update
        - apiGroups:
            - ''
          resources:
            - secrets
            - pods/exec
            - pods
            - services
            - configmaps
            - events
            - persistentvolumeclaims
            - namespace
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - apps
          resources:
            - statefulsets
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - policy
          resources:
            - poddisruptionbudgets
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
