namespace: "longhorn-system"

workload:
  enabled: false

service:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "internalweb, internalwebsecure"
  hosts:
    - host: longhorn.projectwhitebox.com
      path: /
      pathType: "Prefix"
      tls:
        enabled: false
      backend:
        service:
          name: "longhorn-frontend"
          port: 80

extraObjects:
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: config
    spec:
      capacity:
        storage: 100Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: longhorn-static
      csi:
        driver: driver.longhorn.io
        fsType: ext4
        volumeHandle: config
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: media-1
    spec:
      capacity:
        storage: 7.81 Ti
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: longhorn-static
      csi:
        driver: driver.longhorn.io
        fsType: ext4
        volumeHandle: media-1
  - |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: media-2
    spec:
      capacity:
        storage: 7.81 Ti
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: longhorn-static
      csi:
        driver: driver.longhorn.io
        fsType: ext4
        volumeHandle: media-2
