{
 "title": "Kube Image Keeper",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controllers up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_image_keeper_controller_up{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CachedImages count per status",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(status) (sum by(status, instance) (kube_image_keeper_controller_cached_images{ status!=\"Synchronizing\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CachedImages count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(instance) (kube_image_keeper_controller_cached_images{}))",
     "legendFormat": "{{cached}}"
    }
   ]
  },
  {
   "title": "Images in local registry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(instance) (kube_image_keeper_controller_cached_images{cached=\"true\"}))",
     "legendFormat": "{{cached}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (kube_image_keeper_controller_containers_with_cached_image{cached=\"true\"}) / count(kube_pod_container_info{})",
     "legendFormat": "Rewritten by Kuik"
    },
    { "expression": "1 - $A", "type": "math" }
   ]
  },
  {
   "title": "CachedImages expiring",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(instance) (kube_image_keeper_controller_cached_images{expiring=\"true\"}))",
     "legendFormat": "{{cached}}"
    }
   ]
  },
  {
   "title": "Images not in local registry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(instance) (kube_image_keeper_controller_cached_images{cached=\"false\"}))",
     "legendFormat": "{{cached}}"
    }
   ]
  },
  {
   "title": "Proxies up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_image_keeper_proxy_build_info{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxies Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(statusCode) (kube_image_keeper_proxy_http_requests_total{ cacheHit=\"true\", statusCode=\"200\"}) / sum by(statusCode) (kube_image_keeper_proxy_http_requests_total{ statusCode=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failling containers",
   "type": "stat",
   "description": "Containers rewritten by kuik",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(status) (sum by(status, instance) (kube_image_keeper_controller_containers_with_cached_image{status!~\"Ready|Pulling\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kuik version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (kube_image_keeper_controller_build_info{})"
    }
   ]
  },
  {
   "title": "Cached images details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Image put in cache",
     "type": "timeseries",
     "description": "Images put in cache by controller",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job) (increase(kube_image_keeper_controller_image_put_in_cache_total{}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Images removed from cache",
     "type": "timeseries",
     "description": "Image removed from cache by controller",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job) (increase(kube_image_keeper_controller_image_removed_from_cache_total{}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Successful cached images by source registries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(upstream_registry) (increase(kube_image_keeper_controller_image_caching_request{ successful=\"true\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unsuccessful cached images by source registries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(upstream_registry) (increase(kube_image_keeper_controller_image_caching_request{successful=\"false\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(statusCode) (increase(kube_image_keeper_proxy_http_requests_total{}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests to local registry",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(kube_image_keeper_proxy_http_requests_total{cacheHit=\"true\"}[$__rate_interval]))",
       "legendFormat": "Requests total"
      }
     ]
    },
    {
     "title": "Requests to source registries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(kube_image_keeper_proxy_http_requests_total{cacheHit=\"false\"}[$__rate_interval]))",
       "legendFormat": "Requests total"
      }
     ]
    },
    {
     "title": "Requests to local registry (by source registries)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(registry) (increase(kube_image_keeper_proxy_http_requests_total{cacheHit=\"true\"}[$__rate_interval]))",
       "legendFormat": "{{registry}}"
      }
     ]
    },
    {
     "title": "Requests to source registries (by source registries)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(registry) (increase(kube_image_keeper_proxy_http_requests_total{cacheHit=\"false\"}[$__rate_interval]))",
       "legendFormat": "{{registry}}"
      }
     ]
    }
   ]
  }
 ]
}