namespace: "thanos"

workload:
  type: StatefulSet
  image:
    registry: quay.io
    repository: thanos/thanos
    tag: v0.31.0
  args:
    - 'store'
    - '--objstore.config-file=/etc/config/thanos.yaml'
    - '--ignore-deletion-marks-delay=24h'
    - '--log.level=info'
    - '--log.format=logfmt'
    - '--grpc-address=0.0.0.0:10901'
    - '--http-address=0.0.0.0:10902'
    - '--data-dir=/data'
  probes:
    readinessProbe:
      path: "/-/ready"
      port: 10902
    livenessProbe:
      path: "/-/ready"
      port: 10902
  storage:
    - name: config
      type: configMap
      mountPath: /etc/config
      configMapName: prometheus
    - name: data
      type: emptyDir
      mountPath: /data
      sizeLimit: 15Gi
      ramDisk: false
      readOnly: false

service:
  clusterIP: "None"
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
    - name: http
      port: 10902
      protocol: TCP
    - name: remote-write
      port: 19291
      protocol: TCP
