namespace: "thanos"

workload:
  annotations:
    override-url.version-checker.io/thanos-store: quay.io/thanos/thanos
  type: StatefulSet
  image:
    registry: quay.io
    repository: thanos/thanos
    tag: v0.31.0
  args:
    - 'store'
    - '--objstore.config-file=/etc/config/thanos.yaml'
    - '--ignore-deletion-marks-delay=24h'
    - '--log.level=info'
    - '--log.format=logfmt'
    - '--grpc-address=0.0.0.0:10901'
    - '--http-address=0.0.0.0:10902'
    - '--data-dir=/data'
  probes:
    readinessProbe:
      type: httpGet
      path: "/-/ready"
      port: 9093
      scheme: "HTTP"
    livenessProbe:
      type: httpGet
      path: "/-/ready"
      port: 9093
      scheme: "HTTP"
  resources:
    preset: micro
  storage:
    - configMapName: prometheus
      mountPath: /etc/config
      name: config
      type: configMap
    - mountPath: /data
      name: data
      ramDisk: false
      readOnly: false
      sizeLimit: 15Gi
      type: emptyDir

autoscaling:
  enabled: false

service:
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
    - name: http
      port: 10902
      protocol: TCP
    - name: remote-write
      port: 19291
      protocol: TCP
  clusterIP: "None"

