service:
  enabled: false

serviceAccount:
  enabled: false

workload:
  enabled: false

pdb:
  enabled: false

extraObjects:
  - |
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: grafana
    spec:
      description: "Test Grafana"
      imageName: ghcr.io/cloudnative-pg/postgresql:17.2
      instances: 3
      bootstrap:
        initdb:
          database: grafana
          owner: grafana
      enableSuperuserAccess: false
      storage:
        storageClass: "hostpath-csi"
        size: 5Gi
      resources:
        requests:
          cpu: "50m"
          memory: "100Mi"
      affinity:
        enablePodAntiAffinity: true
        topologyKey: kubernetes.io/hostname
