namespace: "grafana"

service:
  enabled: false

serviceAccount:
  enabled: false

workload:
  enabled: false

pdb:
  enabled: false

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: grafana-postgres
    spec:
      description: "Grafana Database"
      imageName: ghcr.io/cloudnative-pg/postgresql:17.5
      instances: 3
      postgresql:
        synchronous:
          method: any
          number: 1
          dataDurability: required
      affinity:
        enablePodAntiAffinity: true
        topologyKey: kubernetes.io/hostname
        podAntiAffinityType: required
      bootstrap:
        initdb:
          database: grafana
          owner: grafana
      enableSuperuserAccess: false
      storage:
        pvcTemplate:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: "local-ssd-disk"
          volumeMode: Filesystem
      resources:
        requests:
          cpu: "10m"
          memory: "10Mi"
