namespace: "grafana"

service:
  enabled: false

serviceAccount:
  enabled: false

workload:
  enabled: false

pdb:
  enabled: false

autoscaling:
  enabled: false

extraObjects:
  - |
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: grafana-postgres
      labels:
        kube-image-keeper.enix.io/image-caching-policy: ignore
    spec:
      description: "Grafana Database"
      imageName: ghcr.io/cloudnative-pg/postgresql:17.5
      instances: 1
      inheritedMetadata:
        labels:
          kube-image-keeper.enix.io/image-caching-policy: ignore
      bootstrap:
        initdb:
          database: grafana
          owner: grafana
      enableSuperuserAccess: false
      storage:
        pvcTemplate:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi
          storageClassName: "openebs"
          volumeMode: Filesystem
      resources:
        requests:
          cpu: "10m"
          memory: "256Mi"
        limits:
          memory: "256Mi"
