namespace: "argocd-test"
installCRDs: false

workload:
  replicaCount: 1
  type: StatefulSet
  image:
    registry: quay.io
    repository: argoproj/argocd
    tag: v2.14.2
  command:
    - /usr/local/bin/argocd-repo-server
  args:
    - /usr/local/bin/argocd-application-controller
    - --metrics-port=8082
    - '--redis=argocd-cache.argocd-test.svc.cluster.local:6379'
  resources:
    preset: nano
  storage:
    - mountPath: /tmp
      name: tmp
      ramDisk: false
      readOnly: false
      type: emptyDir
    - mountPath: /app/config/gpg/keys/
      name: gpg-keys
      ramDisk: false
      readOnly: false
      type: emptyDir

service:
  ports:
    - name: http-metrics
      port: 8082
      protocol: TCP

autoscaling:
  enabled: false

rbac:
  enabled: true
  roles:
    role:
      rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - configmaps
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - patch
          - delete
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          - applicationsets
          - appprojects
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - list
    clusterRole:
      rules:
        - apiGroups:
            - '*'
          resources:
            - '*'
          verbs:
            - '*'
        - nonResourceURLs:
            - '*'
          verbs:
            - '*'
