namespace: "kyverno"

workload:
  annotations:
    override-url.version-checker.io/kyverno-reports-controller: reg.kyverno.io/kyverno/reports-controller
  image:
    registry: "reg.kyverno.io"
    repository: "kyverno/reports-controller"
    tag: "v1.13.3"
  args:
    - '--disableMetrics=false'
    - '--otelConfig=prometheus'
    - '--metricsPort=8000'
    - '--resyncPeriod=15m'
    - '--admissionReports=true'
    - '--aggregateReports=true'
    - '--policyReports=true'
    - '--validatingAdmissionPolicyReports=false'
    - '--backgroundScan=true'
    - '--backgroundScanWorkers=2'
    - '--backgroundScanInterval=1h'
    - '--skipResourceFilters=true'
    - '--enableConfigMapCaching=true'
    - '--enableDeferredLoading=true'
    - '--maxAPICallResponseLength=2000000'
    - '--loggingFormat=text'
    - '--v=2'
    - '--omitEvents=PolicyApplied,PolicySkipped'
    - '--enablePolicyException=false'
    - '--allowInsecureRegistry=false'
    - '--registryCredentialHelpers=default,google,amazon,azure,github'
    - '--enableReporting=validate,mutate,mutateExisting,imageVerify,generate'
  probes:
    readinessProbe:
      path: "/metrics"
      port: 8000
    livenessProbe:
      path: "/metrics"
      port: 8000
  envs:
    - name: KYVERNO_SERVICEACCOUNT_NAME
      value: kyverno-reports-controller
    - name: KYVERNO_DEPLOYMENT
      value: kyverno-reports-controller
    - name: INIT_CONFIG
      value: kyverno-admission-controller
    - name: METRICS_CONFIG
      value: kyverno-admission-controller
    - name: TUF_ROOT
      value: /.sigstore
  envsFromField:
    - name: KYVERNO_NAMESPACE
      fieldPath: metadata.namespace
    - name: KYVERNO_POD_NAME
      fieldPath: metadata.name
  storage:
    - mountPath: /.sigstore
      name: sigstore
      ramDisk: false
      readOnly: false
      sizeLimit: 5Gi
      type: emptyDir

service:
  ports:
    - name: https
      protocol: TCP
      port: 9443
    - name: http-metrics
      protocol: TCP
      port: 8000

rbac:
  enabled: true
  roles:
    role:
      rules:
        - apiGroups:
            - ''
          resourceNames:
            - kyverno-admission-controller
          resources:
            - configmaps
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - create
        - apiGroups:
            - coordination.k8s.io
          resourceNames:
            - kyverno-reports-controller
          resources:
            - leases
          verbs:
            - delete
            - get
            - patch
            - update
    clusterRole:
      rules:
        - apiGroups:
            - apiextensions.k8s.io
          resources:
            - customresourcedefinitions
          verbs:
            - get
        - apiGroups:
            - ''
          resources:
            - configmaps
            - namespaces
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - kyverno.io
          resources:
            - globalcontextentries
            - globalcontextentries/status
            - policyexceptions
            - policies
            - clusterpolicies
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
            - deletecollection
        - apiGroups:
            - reports.kyverno.io
          resources:
            - ephemeralreports
            - clusterephemeralreports
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
            - deletecollection
        - apiGroups:
            - wgpolicyk8s.io
          resources:
            - policyreports
            - policyreports/status
            - clusterpolicyreports
            - clusterpolicyreports/status
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
            - deletecollection
        - apiGroups:
            - ''
            - events.k8s.io
          resources:
            - events
          verbs:
            - create
            - patch

extraObjects:
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: kyverno-reports-controller:view
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view
    subjects:
      - kind: ServiceAccount
        name: kyverno-reports-controller
        namespace: kyverno
