installCRDs: true

workload:
  image:
    repository: "bitnami/sealed-secrets-controller"
    tag: "0.29.0"
  args:
    - '--update-status'
    - '--key-prefix'
    - sealed-secrets-key
    - '--listen-addr'
    - ':8080'
    - '--listen-metrics-addr'
    - ':8081'
  probes:
    readinessProbe:
      port: 8080
    livenessProbe:
      path: "/healthz"
      port: 8080
  storage:
    - name: tmp-dashboards
      type: emptyDir
      mountPath: /tmp/dashboards

service:
  ports:
    - name: http
      protocol: TCP
      port: 8080
    - name: http-metrics
      protocol: TCP
      port: 8081

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
            - bitnami.com
          resources:
            - sealedsecrets
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - bitnami.com
          resources:
            - sealedsecrets/status
          verbs:
            - update
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - get
            - list
            - create
            - update
            - delete
            - watch
        - apiGroups:
            - ''
          resources:
            - events
          verbs:
            - create
            - patch
    role:
      rules:
        - apiGroups:
            - ''
          resourceNames:
            - sealed-secrets
          resources:
            - services
          verbs:
            - get
        - apiGroups:
            - ''
          resourceNames:
            - 'http:sealed-secrets:'
            - http:sealed-secrets:http
            - sealed-secrets
          resources:
            - services/proxy
          verbs:
            - create
            - get
        - apiGroups:
            - ''
          resourceNames:
            - sealed-secrets-key
          resources:
            - secrets
          verbs:
            - get
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - create
            - list
