workload:
  type: DaemonSet
  image:
    registry: "registry.k8s.io"
    repository: "node-problem-detector/node-problem-detector"
    tag: "v0.8.19"
  command:
    - '/bin/sh'
    - '-c'
  args:
    - 'exec /node-problem-detector'
    - '--logtostderr'
    - '--config.system-log-monitor=/config/kernel-monitor.json'
    - '--prometheus-address=0.0.0.0' 
    - '--prometheus-port=20257'
    - '--k8s-exporter-heartbeat-period=5m0s'
  resources:
    preset: "nano"
  storage:
    - name: log
      type: hostPath
      mountPath: /var/log
      hostPath: /var/log
      readOnly: true
    - name: localtime
      type: hostPath
      mountPath: /etc/localtime
      hostPath: /etc/localtime
      readOnly: true
  priorityClassName: "system-node-critical"

service:
  ports:
    - name: metrics
      protocol: TCP
      port: 20257

serviceMonitor:
  enabled: true

rbac:
  enabled: true
  type: "ClusterRole"
    rules:
      - apiGroups:
          - ''
        resources:
          - nodes
        verbs:
          - get
      - apiGroups:
          - ''
        resources:
          - nodes/status
        verbs:
          - patch
      - apiGroups:
          - ''
        resources:
          - events
        verbs:
          - create
          - patch
          - update
