{
 "title": "Kubernetes / Grafana Operator",
 "description": "prometheus operator ",
 "tags": [
  "kubernetes",
  "prometheus",
  "grafana",
  "grafana-operator"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CR Initial Sync Durations",
   "type": "stat",
   "description": "Time in ms to sync Custom Resources after operator restart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafana_operator_dashboards_initial_sync_duration)",
     "legendFormat": "Dashboards"
    },
    {
     "expr": "sum(grafana_operator_datasources_initial_sync_duration)",
     "legendFormat": "Datasources"
    },
    {
     "expr": "sum(grafana_operator_folders_initial_sync_duration)",
     "legendFormat": "Folders"
    }
   ]
  },
  {
   "title": "CR Reconciles",
   "type": "timeseries",
   "description": "Reconciles per Grafana instance",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(grafana_operator_reconciler_reconciles[5m])",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{service=\"grafana-operator/grafana-operator/\"}[5m])) by (pod, name)",
     "legendFormat": "{{name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (workqueue_depth{service=\"grafana-operator/grafana-operator/\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{service=\"grafana-operator/grafana-operator/\"}[5m])) by (pod, name, le))",
     "legendFormat": "{{name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(rest_client_requests_total{service=\"grafana-operator/grafana-operator/\"}[5m]))",
     "legendFormat": "2xx - {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(rest_client_requests_total{service=\"grafana-operator/grafana-operator/\"}[5m]))",
     "legendFormat": "3xx - {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(rest_client_requests_total{service=\"grafana-operator/grafana-operator/\"}[5m]))",
     "legendFormat": "4xx - {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(rest_client_requests_total{service=\"grafana-operator/grafana-operator/\"}[5m]))",
     "legendFormat": "5xx - {{pod}}"
    }
   ]
  },
  {
   "title": "Grafana API Requests",
   "type": "timeseries",
   "description": "Requests against the Grafana api per instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by (method, instance_name) (rate(grafana_operator_grafana_api_requests{service=\"grafana-operator/grafana-operator/\"}[5m]))",
     "legendFormat": "{{method}} - {{instance_name}}"
    }
   ]
  }
 ]
}