namespace: "prometheus"

global:
  chart: "kube-prometheus-stack"
  repository: "https://prometheus-community.github.io/helm-charts"
  version: "68.*.*"

cleanPrometheusOperatorObjectNames: true

crds:
  enabled: false

prometheusOperator:
  enabled: false

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

grafana:
  enabled: true

prometheus:
  enabled: false
