workload:
  annotations:
    override-url.version-checker.io/node-exporter: quay.io/prometheus/node-exporter
  type: DaemonSet
  image:
    registry: "quay.io"
    repository: "prometheus/node-exporter"
    tag: "v1.8.2"
  args:
    - '--web.listen-address=0.0.0.0:9100'
    - '--path.procfs=/host/proc'
    - '--path.sysfs=/host/sys'
    - '--path.rootfs=/host/root'
    - '--path.udev.data=/host/root/run/udev/data'
  probes:
    readinessProbe:
      type: httpGet
      path: "/metrics"
      port: 9100
      scheme: "HTTP"
    livenessProbe:
      type: httpGet
      path: "/metrics"
      port: 9100
      scheme: "HTTP"
  resources:
    preset: "nano"
  storage:
    - name: proc
      type: hostPath
      mountPath: /host/proc
      hostPath: /proc
      readOnly: true
    - name: sys
      type: hostPath
      mountPath: /host/sys
      hostPath: /sys
      readOnly: true
    - name: root
      type: hostPath
      mountPath: /host/root
      hostPath: /
      readOnly: true

pdb:
  enabled: false

autoscaling:
  enabled: false

service:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9100

grafana:
  dashboard:
    enabled: true
    dashboards:
      - name: node-information
        title: "Node Information"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/node-exporter/dashboards/node-information.json"
        folder: "System"
