autoPatching:
  enabled: true
  annotations:
    argocd-image-updater.argoproj.io/image-list: "node-exporter=quay.io/prometheus/node-exporter:~v1"
workload:
  type: DaemonSet
  image:
    repository: "quay.io/prometheus/node-exporter"
    tag: "v1.9.1"
  args:
  - '--web.listen-address=0.0.0.0:9100'
  - '--path.procfs=/host/proc'
  - '--path.sysfs=/host/sys'
  - '--path.rootfs=/host/root'
  - '--path.udev.data=/host/root/run/udev/data'
  probes:
    readinessProbe:
      path: "/metrics"
      port: 9100
    livenessProbe:
      path: "/metrics"
      port: 9100
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  storage:
  - name: proc
    type: hostPath
    mountPath: /host/proc
    hostPath: /proc
    readOnly: true
  - name: sys
    type: hostPath
    mountPath: /host/sys
    hostPath: /sys
    readOnly: true
  - name: root
    type: hostPath
    mountPath: /host/root
    hostPath: /
    readOnly: true
service:
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9100
