workload:
  type: DaemonSet
  image:
    registry: "quay.io"
    repository: "prometheus/node-exporter"
    tag: "latest"
  args:
    - '--web.listen-address=0.0.0.0:9100'
    - '--path.procfs=/host/proc'
    - '--path.sysfs=/host/sys'
    - '--path.rootfs=/host/root'
    - '--path.udev.data=/host/root/run/udev/data'
  resources:
    preset: "nano"
  priorityClassName: "system-node-critical"
  storage:
    - name: proc
      type: hostPath
      mountPath: /proc
      hostPath: /proc
      readOnly: true
    - name: sys
      type: hostPath
      mountPath: /sys
      hostPath: /sys
      readOnly: true
    - name: root
      type: hostPath
      mountPath: /
      hostPath: /
      readOnly: true

serviceAccount:
  enabled: false

autoscaling:
  enabled: false

pdb:
  enabled: false

service:
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
