workload:
  type: DaemonSet
  image:
    registry: "quay.io"
    repository: "prometheus/node-exporter"
    tag: "latest"
  args:
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - --path.rootfs=/host/root
    - --path.udev.data=/host/root/run/udev/data
    - --web.listen-address=0.0.0.0:8200
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    privileged: true
  resources:
    preset: "nano"
  priorityClassName: "system-node-critical"

autoscaling:
  enabled: false

pdb:
  enabled: false

service:
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
