namespace: "prometheus"

global:
  chart: "kube-prometheus-stack"
  repository: "https://prometheus-community.github.io/helm-charts"
  version: "68.*.*"

cleanPrometheusOperatorObjectNames: true

crds:
  enabled: false

nodeExporter:
  enabled: true
