global:
  name: "cert-manager"
  repository: "https://charts.jetstack.io"
  version: "1.16.*"

  leaderElection:
    namespace: {{ .Release.Namespace }}
crds:
  enabled: true
  keep: false

extraObjects:
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: "{{ template "cert-manager.fullname" . }}-acme"
    spec:
      acme:
        email: {{ .Values.global.wildcardCertificate.email }}
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: acme-issuer-key
        solvers:
          - dns01:
              cloudflare:
                email: {{ .Values.global.wildcardCertificate.email }}
                apiTokenSecretRef:
                  name: cloudflare-api-token
                  key: api-token
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: cloudflare-api-token
    type: Opaque
    stringData:
      api-token: {{ .Values.global.wildcardCertificate.apiToken }}
  - |
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: cloudflare-certificate
    spec:
      secretName: "acme-cloudflare-wildcard-certificate"
      dnsNames:
        - '{{ .Values.global.wildcardCertificate.domain }}'
        - '*.{{ .Values.global.wildcardCertificate.domain }}'
      issuerRef:
        name: "{{ template "cert-manager.fullname" . }}-acme"
        kind: ClusterIssuer
      secretTemplate:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""

