global:
  chart: "cert-manager"
  repository: "https://charts.jetstack.io"
  version: "1.16.*"

  leaderElection:
    namespace: "cert-manager"
crds:
  enabled: true
  keep: false

replicaCount: 2
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

webhook:
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

cainjector:
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
