namespace: "kube-system"

workload:
  enabled: false

service:
  ports:
  - name: https-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  selector:
    k8s-app: kube-proxy

autoscaling:
  enabled: false

pdb:
  enabled: false

serviceAccount:
  enabled: false

