workload:
  annotations:
    override-url.version-checker.io/version-checker: quay.io/jetstack/version-checker
  image:
    registry: quay.io
    repository: jetstack/version-checker
    tag: v0.8.5
  command:
    - 'version-checker'
  args:
    - '--metrics-serving-address=0.0.0.0:8080'
    - '--log-level=info'
    - '--image-cache-timeout=30m'
    - '--test-all-containers=true'
  probes:
    readinessProbe:
      type: httpGet
      path: "/readyz"
      port: 8080
      scheme: "HTTP"
    livenessProbe:
      type: httpGet
      path: "/readyz"
      port: 8080
      scheme: "HTTP"
  resources:
    preset: nano

service:
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
          - ""
          resources:
          - "pods"
          verbs:
          - "get"
          - "list"
          - "watch"

grafana:
  dashboard:
    enabled: true
    dashboards:
      - name: kubernetes-imge-drift
        title: "Kubernetes / Image Drift"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/version-checker/dashboards/kubernetes-image-drift.json"
        folder: "System"
