workload:
  image:
    registry: quay.io
    repository: jetstack/version-checker
    tag: v0.9.2
    digest: "sha256:8a08806216fb09a701855f0c7ce3fc8c93b0a4989481b0985683e5d086fe9673"
  command:
    - 'version-checker'
  args:
    - '--metrics-serving-address=0.0.0.0:8080'
    - '--log-level=info'
    - '--image-cache-timeout=30m'
    - '--test-all-containers=true'
  probes:
    livenessProbe:
      path: "/readyz"

service:
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP

rbac:
  enabled: true
  roles:
    clusterRole:
      rules:
        - apiGroups:
          - ""
          resources:
          - "pods"
          verbs:
          - "get"
          - "list"
          - "watch"

grafana:
  dashboard:
    enabled: true
    dashboards:
      - name: kubernetes-image-drift
        title: "Kubernetes / Image Drift"
        url: "https://raw.githubusercontent.com/jamie-stinson/helm-system-monorepo/refs/heads/main/charts/version-checker/dashboards/kubernetes-image-drift.json"
        folder: "System"
